### ISSUE TITLE
[KIEKER-901] Execution traces from big log files

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1090]
JIRA Issue: [KIEKER-901] Execution traces from big log files
Original Reporter: Nils Christian Ehmke
 *** 
<p>As explained in KIEK-699:</p>

<p>There were problems analyzing log files (received within five minutes) and extracting the execution traces. Check whether this is a problem with the log files or with our own tool.</p>

## Checklist:

**Comment by rju** [comment]
author André van Hoorn -- Mon, 25 Feb 2013 18:53:22 +0100
<p>We processed quite big monitoring logs with the tool already. But maybe the problems were caused by 
    <span class="jira-issue-macro resolved" data-jira-key="KIEKER-480" >
                <a href="https://kieker-monitoring.atlassian.net/browse/KIEKER-480" class="jira-issue-macro-key issue-link"  title="Heavy memory use in ExecutionRecordTransformationFilter" >
            <img class="icon" src="https://kieker-monitoring.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />
            KIEKER-480
        </a>
                                                    <span class="aui-lozenge aui-lozenge-subtle aui-lozenge-success jira-macro-single-issue-export-pdf">Done</span>
            </span>
 or 
    <span class="jira-issue-macro resolved" data-jira-key="KIEKER-671" >
                <a href="https://kieker-monitoring.atlassian.net/browse/KIEKER-671" class="jira-issue-macro-key issue-link"  title="GraphElement.origins causes heavy memory usage with large monitoring logs" >
            <img class="icon" src="https://kieker-monitoring.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />
            KIEKER-671
        </a>
                                                    <span class="aui-lozenge aui-lozenge-subtle aui-lozenge-success jira-macro-single-issue-export-pdf">Done</span>
            </span>
. Is it possible to get the log files that caused the problems (student submissions)?</p>

<p>It would be good to have a "large" (whatever this means) log for regression purposes.</p>

**Comment by rju** [comment]
author nils-christian -- Tue, 26 Feb 2013 10:38:52 +0100
<p>It was G07 who had the problem. Maybe jwa can contact them and check whether they still have those files in question. </p>

**Comment by rju** [comment]
author Jan Waller -- Tue, 26 Feb 2013 12:50:02 +0100
<p>Attachment eclipse-project.zip has been added with description: G07 Afg5</p>

**Comment by rju** [comment]
author Jan Waller -- Tue, 26 Feb 2013 12:50:45 +0100
<p>The associated task (in German):<br/>
&gt;In Serie 1 wurde das Kieker Framework vorgestellt. Führt für die Stacks in Aufgabe 4 mit Hilfe von Kieker Performancemessungen durch. Für jede Messung sollen 10 Threads gestartet werden, die zufällig Elemente auf den Stack legen oder von diesem entnehmen. Achtet auch auf eine ausreichende Warmup-Zeit, sowie eine ausreichende anfängliche Stack-Füllung. Die eigentliche Messung soll pro Stack 5 Minuten dauern und es sollen zur gleichen Zeit keine weiteren rechenintensiven Programme ausgeführt werden.<br/>
&gt;a. Wie viele Elemente werden jeweils auf den Stack gelegt bzw. von diesem entnommen?<br/>
&gt;b. Wie lange dauert durchschnittlich eine Ausführung einer Operation?<br/>
&gt;c. Wie viele Versuche werden durchschnittlich und maximal benötigt, bis die Threads Elemente auf den Stack legen bzw. von diesem entfernen können?<br/>
&gt;d. Interpretiert eure Ergebnisse&#33;<br/>
&gt;Gebt bitte auch die folgenden Angaben bzgl. der von euch verwendeten Rechnerkonguration an: Prozessortyp, Hauptspeicher und Betriebssystem.</p>

<p>I added the associated eclipse-project to produce the logs in attachment:eclipse-project.zip.</p>

**Comment by rju** [comment]
author André van Hoorn -- Fri, 1 Mar 2013 13:45:59 +0100
<p>Replying to <span class="error">&#91;jwa|comment:5&#93;</span>:<br/>
&gt; Unrelated to the example posted above, I produced two Kieker logs, once using <tt>OperationExecutionRecords</tt> and once using <tt>BeforeOperationEvent</tt> and <tt>AfterOperationEvent</tt> records. In both cases the records are written using the <tt>BinaryWriter</tt> resulting in 1.2 GiB and 3.2GiB log files, respectively.</p>

<p>Could you provide the example (log files), please. </p>

**Comment by rju** [comment]
author Jan Waller -- Fri, 1 Mar 2013 14:07:34 +0100
<p>Of course <img class="emoticon" src="/images/icons/emoticons/wink.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

<p>But they are a bit large to upload.</p>

**Comment by rju** [comment]
author André van Hoorn -- Fri, 1 Mar 2013 14:21:09 +0100
<p>Replying to <span class="error">&#91;jwa|comment:7&#93;</span>:<br/>
&gt; Of course <img class="emoticon" src="/images/icons/emoticons/wink.png" height="16" width="16" align="absmiddle" alt="" border="0"/><br/>
&gt; <br/>
&gt; But they are a bit large to upload.</p>

<p>Also with tar.gz, bzip2, etc.? Or maybe put it on the storage.</p>

**Comment by rju** [comment]
author André van Hoorn -- Wed, 6 Mar 2013 14:57:37 +0100
<p>Probably the trace timeout. Can be configured with </p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>--max-trace-duration &lt;duration in ms&gt;                             Threshold
                                                                      (in
                                                                      millisecon
                                                                      ds) after
                                                                      which an
                                                                      incomplete
                                                                      trace
                                                                      becomes
                                                                      invalid.
                                                                      Defaults
                                                                      to 600000
                                                                      (10
                                                                      minutes).
</pre>
</div></div>

**Comment by rju** [comment]
author André van Hoorn -- Thu, 4 Apr 2013 17:20:00 +0200
<p>Could reproduce the problem and workaround this by selecting a (<b>really</b> small) trace timeout. Using {{OperationExecutionRecord}}s there's no alternative for playing around with the trace timeout in case of memory problems.</p>

<p>This seems to be an extreme monitoring log with really short traces. Concluding from the TraceAnalysis output, the two monitoring logs are not from a deterministic run. Is this right?</p>

<p>Won't fix for this ticket?</p>

<p>1. <b>Event</b>-based log without max. trace duration</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre> 
avhblade2:0:~/git_work/kieker &lt;master&gt; $ bin/trace-analysis.sh -i ../../monitoring-logs/kieker-ticket-785/kieker-20130301-120755908-UTC-blade1-KIEKER-SPECjbb2013/ --plot-Assembly-Operation-Dependency-Graph response-time -o tmp/
...
#
# Plugin: Trace reconstruction (execution records -&gt; execution traces)
Trace processing summary: 0 total; 0 succeeded; 0 failed.

#
# Plugin: Trace reconstruction (event records -&gt; event record traces)
Trace processing summary: 26787738 total; 26787738 succeeded; 0 failed.

#
# Plugin: Trace reconstruction (event record traces -&gt; execution traces)
Trace processing summary: 26787738 total; 26787738 succeeded; 0 failed.

See 'kieker.log' for details

real    24m40.395s
user    27m21.651s
sys     5m48.138s
</pre>
</div></div>

<p>2. <b>Execution</b>-based log with*out* max. trace duration</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>avhblade2:130:~/git_work/kieker &lt;master&gt; $ time bin/trace-analysis.sh -i ../../monitoring-logs/kieker-ticket-785/kieker-20130301-104850411-UTC-blade1-KIEKER-SPECjbb2013/ --plot-Assembly-Operation-Dependency-Graph response-time -o tmp/
...
Exception in thread "Thread-2" java.lang.OutOfMemoryError: Java heap space
        at java.lang.Class.getDeclaredFields0(Native Method)
        at java.lang.Class.privateGetDeclaredFields(Class.java:2291)
        at java.lang.Class.getDeclaredField(Class.java:1880)
        at kieker.common.record.AbstractMonitoringRecord.typesForClass(AbstractMonitoringRecord.java:255)
        at kieker.analysis.plugin.reader.filesystem.FSDirectoryReader.processBinaryInputFile(FSDirectoryReader.java:319)
        at kieker.analysis.plugin.reader.filesystem.FSDirectoryReader.run(FSDirectoryReader.java:126)
        at java.lang.Thread.run(Thread.java:662)
</pre>
</div></div>

<p>3. <b>Execution</b>-based log <b>with</b> max. trace duration of 60 milliseconds</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>avhblade2:130:~/git_work/kieker &lt;master&gt; $ bin/trace-analysis.sh -i ../../monitoring-logs/kieker-ticket-785/kieker-20130301-104850411-UTC-blade1-KIEKER-SPECjbb2013/ --plot-Assembly-Operation-Dependency-Graph response-time -o tmp/3/ --max-trace-duration 60
...
#
# Plugin: Trace reconstruction (execution records -&gt; execution traces)
Trace processing summary: 23122211 total; 23122211 succeeded; 0 failed.
First timestamp: 1362134930422563616 (Fri, 1 Mar 2013 10:48:50 +0000 (UTC),Fri, 1 Mar 2013 11:48:50 +0100 (local time))
Last timestamp: 1362135111819184310 (Fri, 1 Mar 2013 10:51:51 +0000 (UTC),Fri, 1 Mar 2013 11:51:51 +0100 (local time))

#
# Plugin: Trace reconstruction (event records -&gt; event record traces)
Trace processing summary: 0 total; 0 succeeded; 0 failed.

#
# Plugin: Trace reconstruction (event record traces -&gt; execution traces)
Trace processing summary: 0 total; 0 succeeded; 0 failed.

See 'kieker.log' for details

real    6m45.553s
user    8m59.390s
sys     1m23.925s
</pre>
</div></div>
