### ISSUE TITLE
[KIEKER-670] DescriptionRepository and TraceColorRepository do not provide a valid constructor

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1275]
JIRA Issue: [KIEKER-670] DescriptionRepository and TraceColorRepository do not provide a valid constructor
Original Reporter: Nils Christian Ehmke
 *** 
<p>I just created a kax-file for 
    <span class="jira-issue-macro resolved" data-jira-key="KIEKER-660" >
                <a href="https://kieker-monitoring.atlassian.net/browse/KIEKER-660" class="jira-issue-macro-key issue-link"  title="Plugins - Storing and Delivering Configuration" >
            <img class="icon" src="https://kieker-monitoring.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />
            KIEKER-660
        </a>
                                                    <span class="aui-lozenge aui-lozenge-subtle aui-lozenge-success jira-macro-single-issue-export-pdf">Done</span>
            </span>
 and received following error:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>1    ERROR [main]                   kieker.tools.KaxViz     - Error
kieker.analysis.exception.AnalysisConfigurationException: AbstractRepository: Class 'kieker.tools.traceAnalysis.repository.DescriptionRepository' has to implement a (public) constructor that accepts a single Configuration
	at kieker.analysis.AnalysisController.createAndInitialize(AnalysisController.java:967)
	at kieker.analysis.AnalysisController.loadFromModelProject(AnalysisController.java:263)
	at kieker.analysis.AnalysisController.&lt;init&gt;(AnalysisController.java:202)
	at kieker.analysis.AnalysisController.&lt;init&gt;(AnalysisController.java:169)
	at kieker.analysis.AnalysisController.&lt;init&gt;(AnalysisController.java:150)
	at kieker.tools.KaxViz.main(KaxViz.java:365)
Caused by: java.lang.NoSuchMethodException: kieker.tools.traceAnalysis.repository.DescriptionRepository.&lt;init&gt;(kieker.common.configuration.Configuration)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.getConstructor(Unknown Source)
	at kieker.analysis.AnalysisController.createAndInitialize(AnalysisController.java:960)
	... 5 more
</pre>
</div></div>

[KIEKER-670]: https://kieker-monitoring.atlassian.net/browse/KIEKER-670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Wed, 12 Sep 2012 16:52:57 +0200
<p>As indicated by the title: same problem for <tt>TraceColorRepository</tt>:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>public TraceColorRepository(final Configuration configuration, final Map&lt;Long, Color&gt; colorMap, final Color defaultColor, final Color collisionColor) {
		super(configuration);
		this.colorMap = colorMap;
		this.defaultColor = defaultColor;
		this.collisionColor = collisionColor;
}
</pre>
</div></div>

<p>Required is </p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>public TraceColorRepository(final Configuration configuration) {
...
}
</pre>
</div></div>

**Comment by rju** [comment]
author holgerknoche -- Thu, 13 Sep 2012 16:18:09 +0200
<p>The required constructors have been added, however, the required configuration property does not seem to be saved during KAX export.</p>

**Comment by rju** [comment]
author holgerknoche -- Thu, 13 Sep 2012 17:33:35 +0200
<p>Property export in KAX files has been fixed (
    <span class="jira-issue-macro resolved" data-jira-key="KIEKER-592" >
                <a href="https://kieker-monitoring.atlassian.net/browse/KIEKER-592" class="jira-issue-macro-key issue-link"  title="Configuration properties of repositories are not saved" >
            <img class="icon" src="https://kieker-monitoring.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />
            KIEKER-592
        </a>
                                                    <span class="aui-lozenge aui-lozenge-subtle aui-lozenge-success jira-macro-single-issue-export-pdf">Done</span>
            </span>
).</p>
