### ISSUE TITLE
[KIEKER-704] jUnit Tests with errors in the logs should state that the error is expected

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1279]
JIRA Issue: [KIEKER-704] jUnit Tests with errors in the logs should state that the error is expected
Original Reporter: Jan Waller
 *** 
<p>This statement should be placed near the error in the log.</p>

<p>For instance, the test case <tt>TerminateAfterUnknownTypeNotForBinaryTest</tt> produces this error with no info (one doesn't even see the name of the test):</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>SCHWERWIEGEND: Error reading C:\Temp\junit3745333237454223975\kieker-20120911-145924059-UTC-Osterinsel-KIEKER\kieker-20120911-145924071-UTC-000-Thread-1.bin
kieker.common.exception.MonitoringRecordException: Failed to get record type of name kieker.common.record.controlflow.BranchingRecordXYZ
	at kieker.common.record.AbstractMonitoringRecord.classForName(AbstractMonitoringRecord.java:203)
	at kieker.analysis.plugin.reader.filesystem.FSDirectoryReader.processBinaryInputFile(FSDirectoryReader.java:309)
	at kieker.analysis.plugin.reader.filesystem.FSDirectoryReader.run(FSDirectoryReader.java:124)
	at java.lang.Thread.run(Thread.java:595)
Caused by: java.lang.ClassNotFoundException: kieker.common.record.controlflow.BranchingRecordXYZ
	at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:268)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:164)
	at kieker.common.record.AbstractMonitoringRecord.classForName(AbstractMonitoringRecord.java:201)
	... 3 more
</pre>
</div></div>

<p>more cases exist...</p>

[KIEKER-704]: https://kieker-monitoring.atlassian.net/browse/KIEKER-704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author Jan Waller -- Tue, 11 Sep 2012 17:27:37 +0200
<p>Are all of these errors really expected?</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>11.09.2012 17:21:23 kieker.monitoring.writer.AbstractAsyncThread run
SCHWERWIEGEND: Writer thread will halt
java.io.FileNotFoundException: C:\Temp\junit6326728543337405610\junit4126904075577350476\kieker-20120911-152123588-UTC-Osterinsel-KIEKER\kieker-20120911-152123604-UTC-000-Thread-121.dat (The system cannot find the path specified)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.&lt;init&gt;(FileOutputStream.java:179)
	at java.io.FileOutputStream.&lt;init&gt;(FileOutputStream.java:70)
	at kieker.monitoring.writer.filesystem.async.FsWriterThread.prepareFile(FsWriterThread.java:76)
	at kieker.monitoring.writer.filesystem.async.AbstractFsWriterThread.consume(AbstractFsWriterThread.java:107)
	at kieker.monitoring.writer.AbstractAsyncThread.run(AbstractAsyncThread.java:97)
</pre>
</div></div>

<p>Why can't the system find the path in this case? Is the temp folder already gone while the test is still running?</p>

**Comment by rju** [comment]
author Jan Waller -- Thu, 13 Sep 2012 14:38:20 +0200
<p>Unexpected random error in <tt>kieker.test.tools.junit.writeRead.jmx.BasicJMXWriterReaderTest</tt></p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>13.09.2012 14:29:33 ClientCommunicatorAdmin restart
WARNUNG: Failed to restart: java.io.IOException: Failed to get a RMI stub: javax.naming.CommunicationException [Root exception is java.rmi.UnmarshalException: error unmarshalling return; nested exception is: 
	java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: javax.management.remote.rmi.RMIJRMPServerImpl]
</pre>
</div></div>

**Comment by rju** [comment]
author Jan Waller -- Tue, 9 Oct 2012 14:21:51 +0200
<p>perhaps we can include a special junit Log writer, that can be notified of expected errors and ignore them</p>

**Comment by rju** [comment]
author Jan Waller -- Wed, 10 Oct 2012 16:48:36 +0200
<p>added in 3de01ef3caf49dca872874b8d14a978b3097cc2c</p>
