### ISSUE TITLE
[KIEKER-657] Make log output for invalid traces less verbose

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1280]
JIRA Issue: [KIEKER-657] Make log output for invalid traces less verbose
Original Reporter: Andre van Hoorn
 *** 
<p>A monitoring log with a number of invalid traces lets the size of the <tt>kieker.log</tt> grow considerably in size. The reason is that we log the stack trace in each case, which is not needed here.</p>

<p>Example </p>

<p>{{</p>
{
kieker.tools.traceAnalysis.filter.traceReconstruction.InvalidTraceException: Eois must increment by 1 \--but found sequence &lt;1,5&gt;(Execution: 6425088555885789185[5,1] 1259234925337990000-1259234925465450000 css0::@1:kieker.tpmon.probe.cxf.KiekerTpmonResponseInProbe.handleMessage NULL-SERVLETFILTER)
        at kieker.tools.traceAnalysis.systemModel.ExecutionTrace.toMessageTrace(ExecutionTrace.java:120)
        at kieker.tools.traceAnalysis.filter.traceReconstruction.TraceReconstructionFilter.processExecutionTrace(TraceReconstructionFilter.java:219)
        at kieker.tools.traceAnalysis.filter.traceReconstruction.TraceReconstructionFilter.processTimeoutQueue(TraceReconstructionFilter.java:275)
        at kieker.tools.traceAnalysis.filter.traceReconstruction.TraceReconstructionFilter.inputExecutions(TraceReconstructionFilter.java:192)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at kieker.analysis.plugin.AbstractPlugin.deliver(AbstractPlugin.java:213)
        at kieker.tools.traceAnalysis.filter.executionRecordTransformation.ExecutionRecordTransformationFilter.inputOperationExecutionRecords(ExecutionRecordTransformationFilter.java:66)
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at kieker.analysis.plugin.AbstractPlugin.deliver(AbstractPlugin.java:213)
        at kieker.analysis.plugin.filter.trace.TraceIdFilter.inputOperationExecutionRecord(TraceIdFilter.java:123)
        at kieker.analysis.plugin.filter.trace.TraceIdFilter.inputCombined(TraceIdFilter.java:93)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at kieker.analysis.plugin.AbstractPlugin.deliver(AbstractPlugin.java:213)
        at kieker.analysis.plugin.filter.select.TimestampFilter.inputOperationExecutionRecord(TimestampFilter.java:131)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at kieker.analysis.plugin.AbstractPlugin.deliver(AbstractPlugin.java:213)
        at kieker.analysis.plugin.filter.forward.StringBufferFilter.inputEvent(StringBufferFilter.java:119)
        at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at kieker.analysis.plugin.AbstractPlugin.deliver(AbstractPlugin.java:213)
        at kieker.analysis.plugin.reader.filesystem.FSReader.read(FSReader.java:108)
        at kieker.analysis.AnalysisController$1.run(AnalysisController.java:631)
        at java.lang.Thread.run(Thread.java:662)
3944 ERROR [Thread-0] kieker.tools.traceAnalysis.filter.traceReconstruction.TraceReconstructionFilter     \\- Failed to transform execution trace to message trace (ID:6425088555885789186): TraceId 6425088555885789186 (minTin=1259234927531974000 (Thu, 26 Nov 2009 11:28:47 +0000 (UTC)); maxTout=1259234927980112000 (Thu, 26 Nov 2009 11:28:47 +0000 (UTC)); maxEss=1):
&lt;6425088555885789186[0,0] 1259234927531974000-1259234927980112000 css0::@2:kieker.tpmon.probe.servlet.KiekerRequestRegistrationAndLoggingFilter.doFilter NULL-SERVLETFILTER&gt;
&lt;6425088555885789186[1,1] 1259234927533218000-1259234927842276000 css0::@1:kieker.tpmon.probe.cxf.KiekerTpmonResponseInProbe.handleMessage NULL-SERVLETFILTER&gt;
&lt;6425088555885789186[5,1] 1259234927842615000-1259234927956393000 css0::@1:kieker.tpmon.probe.cxf.KiekerTpmonResponseInProbe.handleMessage NULL-SERVLETFILTER&gt;
}}

[KIEKER-657]: https://kieker-monitoring.atlassian.net/browse/KIEKER-657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Tue, 11 Sep 2012 09:34:07 +0200
<p>Fixed in changeset:b0440171359355203747feedd8128527fd7f5459/kieker-git</p>

<p>Output now </p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2173 ERROR [Thread-1] kieker.tools.traceAnalysis.filter.traceReconstruction.TraceReconstructionFilter     - Failed to transform execution trace to message trace (ID:6425088555885789225). 
Reason:Eois must increment by 1 --but found sequence &lt;1,5&gt;(Execution: 6425088555885789225[5,1] 1259235004993556000-1259235005136122000 css0::1:kieker.tpmon.probe.cxf.KiekerTpmonResponseInProbe.handleMessage NULL-SERVLETFILTER)
 Trace:TraceId 6425088555885789225 (minTin=1259235004857007000 (Thu, 26 Nov 2009 11:30:04 +0000 (UTC)); maxTout=1259235006041971000 (Thu, 26 Nov 2009 11:30:06 +0000 (UTC)); maxEss=1):
&lt;6425088555885789225[0,0] 1259235004857007000-1259235006041971000 css0::2:kieker.tpmon.probe.servlet.KiekerRequestRegistrationAndLoggingFilter.doFilter NULL-SERVLETFILTER&gt;
&lt;6425088555885789225[1,1] 1259235004857749000-1259235004993185000 css0::1:kieker.tpmon.probe.cxf.KiekerTpmonResponseInProbe.handleMessage NULL-SERVLETFILTER&gt;
&lt;6425088555885789225[5,1] 1259235004993556000-1259235005136122000 css0::1:kieker.tpmon.probe.cxf.KiekerTpmonResponseInProbe.handleMessage NULL-SERVLETFILTER&gt;
&lt;6425088555885789225[9,1] 1259235005136372000-1259235005372284000 css0::1:kieker.tpmon.probe.cxf.KiekerTpmonResponseInProbe.handleMessage NULL-SERVLETFILTER&gt;
&lt;6425088555885789225[13,1] 1259235005390912000-1259235005642245000 css0::1:kieker.tpmon.probe.cxf.KiekerTpmonResponseInProbe.handleMessage NULL-SERVLETFILTER&gt;
&lt;6425088555885789225[17,1] 1259235005642750000-1259235005844300000 css0::1:kieker.tpmon.probe.cxf.KiekerTpmonResponseInProbe.handleMessage NULL-SERVLETFILTER&gt;
&lt;6425088555885789225[21,1] 1259235005844603000-1259235006023958000 css0::1:kieker.tpmon.probe.cxf.KiekerTpmonResponseInProbe.handleMessage NULL-SERVLETFILTER&gt;
</pre>
</div></div>
