### ISSUE TITLE
[KIEKER-659] Make sure that all monitoring.properties examples based on the latest template

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1297]
JIRA Issue: [KIEKER-659] Make sure that all monitoring.properties examples based on the latest template
Original Reporter: Andre van Hoorn
 *** 
<p>For example, the JMS example seem to use an outdated version </p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>voorn@pc-vanhoorn:0:~/git_work/kieker/examples/userguide/appendix-JMS &lt;master&gt; $ ant run-monitoring-activemq 
Buildfile: /home/voorn/git_work/kieker/examples/userguide/appendix-JMS/build.xml

-check-files:

clean.monitoring:
   [delete] Deleting: /home/voorn/git_work/kieker/examples/userguide/appendix-JMS/BookstoreMonitoring.jar

-init:
    [mkdir] Created dir: /home/voorn/git_work/kieker/examples/userguide/appendix-JMS/build

-compile:
    [javac] Compiling 5 source files to /home/voorn/git_work/kieker/examples/userguide/appendix-JMS/build
    [mkdir] Created dir: /home/voorn/git_work/kieker/examples/userguide/appendix-JMS/build/META-INF
     [copy] Copying 1 file to /home/voorn/git_work/kieker/examples/userguide/appendix-JMS/build/META-INF

-build-jar-monitoring:
      [jar] Building jar: /home/voorn/git_work/kieker/examples/userguide/appendix-JMS/BookstoreMonitoring.jar
   [delete] Deleting directory /home/voorn/git_work/kieker/examples/userguide/appendix-JMS/build

run-monitoring-activemq:                                                                                                                                                         
     [java] 03.09.2012 14:55:26 kieker.monitoring.core.configuration.ConfigurationFactory createSingletonConfiguration                                                           
     [java] INFO: Loading configuration from JVM-specified location: 'META-INF//kieker.monitoring.properties-activemq'                                                           
     [java] 03.09.2012 14:55:26 kieker.monitoring.core.controller.AbstractController createAndInitialize                                                                         
     [java] SCHWERWIEGEND: ITimeSource: Class 'kieker.monitoring.timer.DefaultSystemTimer' not found                                                                             
     [java] java.lang.ClassNotFoundException: kieker.monitoring.timer.DefaultSystemTimer                                                                                         
     [java]     at java.net.URLClassLoader$1.run(URLClassLoader.java:202)                                                                                                        
     [java]     at java.security.AccessController.doPrivileged(Native Method)                                                                                                    
     [java]     at java.net.URLClassLoader.findClass(URLClassLoader.java:190)                                                                                                    
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:306)                                                                                                         
     [java]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)                                                                                                 
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:247)                                                                                                         
     [java]     at java.lang.Class.forName0(Native Method)                                                                                                                       
     [java]     at java.lang.Class.forName(Class.java:169)                                                                                                                       
     [java]     at kieker.monitoring.core.controller.AbstractController.createAndInitialize(AbstractController.java:90)                                                          
     [java]     at kieker.monitoring.core.controller.TimeSourceController.&lt;init&gt;(TimeSourceController.java:36)                                                                   
     [java]     at kieker.monitoring.core.controller.MonitoringController.&lt;init&gt;(MonitoringController.java:52)                                                                   
     [java]     at kieker.monitoring.core.controller.MonitoringController.createInstance(MonitoringController.java:59)
     [java]     at kieker.monitoring.core.controller.MonitoringController$LazyHolder.&lt;clinit&gt;(MonitoringController.java:260)
     [java]     at kieker.monitoring.core.controller.MonitoringController.getInstance(MonitoringController.java:253)
     [java]     at kieker.examples.userguide.appendixJMS.Bookstore.&lt;clinit&gt;(Unknown Source)
     [java]     at kieker.examples.userguide.appendixJMS.BookstoreStarter.main(Unknown Source)
     [java] 1    WARN  [main] org.apache.activemq.transport.tcp.TcpTransportFactory     - path isn't a valid local location for TcpTransport to use
     [java] 03.09.2012 14:55:27 kieker.monitoring.core.controller.MonitoringController cleanup
     [java] INFO: Shutting down Monitoring Controller (KIEKER)
     [java] 03.09.2012 14:55:27 kieker.monitoring.writer.AbstractAsyncWriter terminate
     [java] INFO: Shutting down writers.
     [java] 03.09.2012 14:55:27 kieker.monitoring.writer.AbstractAsyncWriter terminate
     [java] INFO: Writer shutdown complete.
     [java] Exception in thread "main" java.lang.NullPointerException
     [java]     at kieker.examples.userguide.appendixJMS.Bookstore.searchBook(Unknown Source)
     [java]     at kieker.examples.userguide.appendixJMS.BookstoreStarter.main(Unknown Source)
     [java] Bookstore.main: Starting request 0
     [java] Java Result: 1

BUILD SUCCESSFUL
Total time: 2 seconds
</pre>
</div></div>

[KIEKER-659]: https://kieker-monitoring.atlassian.net/browse/KIEKER-659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author Jan Waller -- Thu, 6 Sep 2012 16:15:14 +0200
<p>Use minimal files instead of replicating the whole configuration.</p>

**Comment by rju** [comment]
author André van Hoorn -- Wed, 3 Oct 2012 15:39:55 +0200
<p>Fixed:</p>

<ul>
	<li>JMS and custom reader/writer examples use minimal configuration (changeset:0818b79dadcf7792fa1051b27997158e3ce88591/kieker-git)</li>
	<li>AspectJ example uses the default configuration copied to the <tt>META-INF</tt> directory during build (changeset:0f5f6a66ec0e19391ccf5110625c6969f248966c/kieker-git)</li>
</ul>
