### ISSUE TITLE
[KIEKER-452] Port compatibility check too restrictive if interface types involved

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1322]
JIRA Issue: [KIEKER-452] Port compatibility check too restrictive if interface types involved
Original Reporter: Andre van Hoorn
 *** 
<p>Example: </p>

<ul>
	<li>Output <tt>outA</tt> of Filter <tt>A</tt> provides events of type <tt>ITypeA</tt> (interface type)</li>
	<li>Input <tt>inB</tt> of Filter <tt>B</tt> accepts events of type <tt>ITypeB</tt> (interface type)</li>
</ul>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>kieker.analysis.exception.AnalysisConfigurationException: Failed to connect plugin 'filterA' (FilterA) to plugin 'filterB' (FilterB).
	at kieker.analysis.plugin.AbstractPlugin.connect(AbstractPlugin.java:359)
	at kieker.analysis.AnalysisController.connect(AnalysisController.java:427)
	at com.tielefeld.opad.filter.CompleteOPADFlowTest.setUp(CompleteOPADFlowTest.java:65)

...
</pre>
</div></div>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>0    INFO  NameFilter     - Started NameFilter filtering for names: [take_it]
 Thread=main3    WARN  LogImplCommonsLogging     - Third step: Make sure the ports are compatible. Not compatible.
 Thread=main
</pre>
</div></div>

<p>However, in order to pass, for example, an Event of Type <tt>TypeAB</tt> implementing  both <tt>ITypeA</tt> and <tt>ITypeB</tt>. The same would hold if either <tt>ITypeA</tt> or <tt>ITypeB</tt> (both not possible in Java) were concrete (or abstract) classes.</p>

[KIEKER-452]: https://kieker-monitoring.atlassian.net/browse/KIEKER-452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Thu, 5 Jul 2012 15:41:54 +0200
<p>Jan committed a fix in changeset:208569b1bcdd5498eda616abe399cfa6d94b9235/kieker-git</p>
