### ISSUE TITLE
[KIEKER-419] Logging Sigar error when no Sigar native lib in java.library.path

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1330]
JIRA Issue: [KIEKER-419] Logging Sigar error when no Sigar native lib in java.library.path
Original Reporter: Andre van Hoorn
 *** 
<p>Instantiating Sigar via <tt>new Sigar()</tt> without a suitable native lib (e.g., <tt>libsigar-x86-linux.so</tt>) does not throw an Exception but returns a <tt>Sigar</tt> instance (which seems to be safe to use but, of course, does not provide measurement data). Sigar does log the following stack trace---however, only in <tt>DEBUG</tt> log level. Using the default configuration, this log message is visible with the JDK logger, but not (for example) with log4j.</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>[java] org.hyperic.sigar.SigarException: no libsigar-x86-linux.so in java.library.path
     [java]     at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
     [java]     at org.hyperic.sigar.Sigar.&lt;clinit&gt;(Sigar.java:100)
     [java]     at kieker.monitoring.probe.sigar.SigarSamplerFactory.&lt;init&gt;(SigarSamplerFactory.java:54)
     [java]     at kieker.monitoring.probe.sigar.SigarSamplerFactory.&lt;clinit&gt;(SigarSamplerFactory.java:40)
     [java]     at kieker.examples.userguide.appendixSigar.MonitoringStarter.main(Unknown Source)
</pre>
</div></div>

<p>It would be good, if Kieker provided a meaningful log message already, when the instantiation of Sigar fails in the <tt>SigarSamplerFactory</tt>.</p>

[KIEKER-419]: https://kieker-monitoring.atlassian.net/browse/KIEKER-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Fri, 8 Jun 2012 11:19:34 +0200
<p>Fixed in 1df1ebb8216b22b2217189bb65bf68c4840c7e5b</p>

<p>(btw: thanks to Sönke for reporting this&#33;)</p>

<p>After creating a Sigar instance, checks the return value of <tt>getNativeLibrary()</tt>. If <tt>null</tt>, the following error message is logged:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>"No Sigar native lib in java.library.path. See Sigar log for details (maybe only visible on Debug log-level)."
</pre>
</div></div>

<p>Tested with the Sigar example from the user guide:</p>

<h2><a name="1.Nonativelib%28errorreportedproperly%3Bnofurthererrors%29"></a>1. No native lib (error reported properly; no further errors)</h2>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>avanhoornavanhoorn-thinkpad:0:~/git_work/kieker/examples/userguide/appendix-Sigar &lt;master&gt; $ ll lib/
total 420
lrwxrwxrwx 1 avanhoorn avanhoorn     44 2012-06-08 10:40 kieker-1.6-SNAPSHOT_emf.jar -&gt; ../../../../dist/kieker-1.6-SNAPSHOT_emf.jar
-rw-r--r-- 1 avanhoorn avanhoorn 428580 2012-06-08 10:13 sigar-1.6.4.jar
avanhoornavanhoorn-thinkpad:0:~/git_work/kieker/examples/userguide/appendix-Sigar &lt;master&gt; $ ant
Buildfile: build.xml

-check-files:

clean.monitoring:
   [delete] Deleting: /home/avanhoorn/git_work/kieker/examples/userguide/appendix-Sigar/SigarMonitoring.jar

-init:
    [mkdir] Created dir: /home/avanhoorn/git_work/kieker/examples/userguide/appendix-Sigar/build

-compile:
    [javac] Compiling 2 source files to /home/avanhoorn/git_work/kieker/examples/userguide/appendix-Sigar/build
    [mkdir] Created dir: /home/avanhoorn/git_work/kieker/examples/userguide/appendix-Sigar/build/META-INF

-build-jar-monitoring:
      [jar] Building jar: /home/avanhoorn/git_work/kieker/examples/userguide/appendix-Sigar/SigarMonitoring.jar
   [delete] Deleting directory /home/avanhoorn/git_work/kieker/examples/userguide/appendix-Sigar/build

run-monitoring:
     [java] Monitoring CPU and Mem/Swap for 30 seconds in 5 seconds steps () with an offset of two seconds
     [java] Jun 8, 2012 11:14:35 AM kieker.monitoring.core.configuration.ConfigurationFactory createSingletonConfiguration
     [java] INFO: Loading properties from properties file in classpath: 'META-INF/kieker.monitoring.properties'
     [java] Jun 8, 2012 11:14:35 AM kieker.monitoring.core.configuration.ConfigurationFactory loadConfigurationFromResource
     [java] WARNING: File 'META-INF/kieker.monitoring.properties' not found in classpath
     [java] Jun 8, 2012 11:14:35 AM kieker.monitoring.core.controller.MonitoringController createInstance
     [java] INFO: Current State of kieker.monitoring (1.6-SNAPSHOT) Status: 'enabled'
     [java]     Name: 'KIEKER-SINGLETON'; Hostname: 'avanhoorn-thinkpad'; experimentID: '1'
     [java] JMXController: JMX disabled
     [java] RegistryController: 0 strings registered.
     [java] TimeSource: 'kieker.monitoring.timer.SystemNanoTimer'
     [java]     Time in nanoseconds (with nanoseconds precision) since Thu Jan 01 01:00:00 CET 1970'
     [java] ProbeController:  not yet implemented.
     [java] WriterController:
     [java]     Number of Inserts: '0'
     [java]     Automatic assignment of logging timestamps: 'true'
     [java] Writer: 'kieker.monitoring.writer.filesystem.AsyncFsWriter'
     [java]     Configuration:
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.QueueFullBehavior='0'
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.flush='true'
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.QueueSize='10000'
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.customStoragePath='.'
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.MaxShutdownDelay='-1'
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.storeInJavaIoTmpdir='true'
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.maxEntriesInFile='25000'
     [java]     Records lost: 0
     [java]     Writer Threads (1): 
     [java]             Finished: 'false'; Writing to Directory: '/tmp/kieker-20120608-091435811-UTC-avanhoorn-thinkpad-KIEKER-SINGLETON'
     [java] Sampling Controller: Periodic Sensor available: Current Poolsize: '0'; Scheduled Tasks: '0'
     [java] 
     [java] no libsigar-x86-linux.so in java.library.path
     [java] org.hyperic.sigar.SigarException: no libsigar-x86-linux.so in java.library.path
     [java]     at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
     [java]     at org.hyperic.sigar.Sigar.&lt;clinit&gt;(Sigar.java:100)
     [java]     at kieker.monitoring.probe.sigar.SigarSamplerFactory.&lt;init&gt;(SigarSamplerFactory.java:54)
     [java]     at kieker.monitoring.probe.sigar.SigarSamplerFactory.&lt;clinit&gt;(SigarSamplerFactory.java:40)
     [java]     at kieker.examples.userguide.appendixSigar.MonitoringStarter.main(Unknown Source)
     [java] Jun 8, 2012 11:14:35 AM kieker.monitoring.probe.sigar.SigarSamplerFactory &lt;init&gt;
     [java] SEVERE: Error instantiating Sigar. Make sure that the Sigar native libs are in java.library.path. See Sigar log (Debug-level) for details.
     [java] Terminating
     [java] Jun 8, 2012 11:15:05 AM kieker.monitoring.core.controller.MonitoringController cleanup
     [java] INFO: Shutting down Monitoring Controller (KIEKER-SINGLETON)
     [java] Jun 8, 2012 11:15:05 AM kieker.monitoring.writer.AbstractAsyncWriter terminate
     [java] INFO: Shutting down writers.
     [java] Jun 8, 2012 11:15:05 AM kieker.monitoring.writer.AbstractAsyncWriter terminate
     [java] INFO: Writer shutdown complete.

BUILD SUCCESSFUL
Total time: 31 seconds
avanhoornavanhoorn-thinkpad:0:~/git_work/kieker/examples/userguide/appendix-Sigar &lt;master&gt; $ ll /tmp/kieker-20120608-091435811-UTC-avanhoorn-thinkpad-KIEKER-SINGLETON
total 0
-rw-r--r-- 1 avanhoorn avanhoorn 0 2012-06-08 11:14 kieker.map
</pre>
</div></div>

<h2><a name="2.Nativelibinpath%28noerror%2Clogwritten%29"></a>2. Native lib in path (no error, log written)</h2>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>avanhoornavanhoorn-thinkpad:0:~/git_work/kieker/examples/userguide/appendix-Sigar/lib &lt;master&gt; $ cp ../../../../lib/sigar-native-libs/libsigar-x86-linux.so .
avanhoornavanhoorn-thinkpad:0:~/git_work/kieker/examples/userguide/appendix-Sigar/lib &lt;master&gt; $ cd ../
avanhoornavanhoorn-thinkpad:0:~/git_work/kieker/examples/userguide/appendix-Sigar &lt;master&gt; $ ant
Buildfile: build.xml

...

run-monitoring:
     [java] Monitoring CPU and Mem/Swap for 30 seconds in 5 seconds steps () with an offset of two seconds
     [java] Jun 8, 2012 11:09:34 AM kieker.monitoring.core.configuration.ConfigurationFactory createSingletonConfiguration
     [java] INFO: Loading properties from properties file in classpath: 'META-INF/kieker.monitoring.properties'
     [java] Jun 8, 2012 11:09:34 AM kieker.monitoring.core.configuration.ConfigurationFactory loadConfigurationFromResource
     [java] WARNING: File 'META-INF/kieker.monitoring.properties' not found in classpath
     [java] Jun 8, 2012 11:09:35 AM kieker.monitoring.core.controller.MonitoringController createInstance
     [java] INFO: Current State of kieker.monitoring (1.6-SNAPSHOT) Status: 'enabled'
     [java]     Name: 'KIEKER-SINGLETON'; Hostname: 'avanhoorn-thinkpad'; experimentID: '1'
     [java] JMXController: JMX disabled
     [java] RegistryController: 0 strings registered.
     [java] TimeSource: 'kieker.monitoring.timer.SystemNanoTimer'
     [java]     Time in nanoseconds (with nanoseconds precision) since Thu Jan 01 01:00:00 CET 1970'
     [java] ProbeController:  not yet implemented.
     [java] WriterController:
     [java]     Number of Inserts: '0'
     [java]     Automatic assignment of logging timestamps: 'true'
     [java] Writer: 'kieker.monitoring.writer.filesystem.AsyncFsWriter'
     [java]     Configuration:
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.QueueFullBehavior='0'
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.flush='true'
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.QueueSize='10000'
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.customStoragePath='.'
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.MaxShutdownDelay='-1'
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.storeInJavaIoTmpdir='true'
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.maxEntriesInFile='25000'
     [java]     Records lost: 0
     [java]     Writer Threads (1): 
     [java]             Finished: 'false'; Writing to Directory: '/tmp/kieker-20120608-090934991-UTC-avanhoorn-thinkpad-KIEKER-SINGLETON'
     [java] Sampling Controller: Periodic Sensor available: Current Poolsize: '0'; Scheduled Tasks: '0'
     [java] 
     [java] Terminating
     [java] Jun 8, 2012 11:10:05 AM kieker.monitoring.core.controller.MonitoringController cleanup
     [java] INFO: Shutting down Monitoring Controller (KIEKER-SINGLETON)
     [java] Jun 8, 2012 11:10:05 AM kieker.monitoring.writer.AbstractAsyncWriter terminate
     [java] INFO: Shutting down writers.
     [java] Jun 8, 2012 11:10:05 AM kieker.monitoring.writer.AbstractAsyncWriter terminate
     [java] INFO: Writer shutdown complete.

BUILD SUCCESSFUL
Total time: 31 seconds
</pre>
</div></div>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>avanhoornavanhoorn-thinkpad:1:~/git_work/kieker/examples/userguide/appendix-Sigar &lt;master&gt; $ head /tmp/kieker-20120608-090934991-UTC-avanhoorn-thinkpad-KIEKER-SINGLETON/kieker-20120608-090937587-UTC--000-Thread-1.dat 
$0;1339146577585509297;1339146577584596821;avanhoorn-thinkpad;0;0.02040816326530612;0.02040816326530612;0.0;0.0;0.0;0.04081632653061224;0.9591836734693877
$0;1339146577585652053;1339146577585640110;avanhoorn-thinkpad;1;0.0;0.0;0.0;0.0;0.0;0.0;1.0
$1;1339146577587657825;1339146577587573666;avanhoorn-thinkpad;4046700544;1561874432;2484826112;3999260672;0;3999260672
$0;1339146582081565857;1339146582081547699;avanhoorn-thinkpad;0;0.026607538802660754;0.031042128603104215;0.1286031042128603;0.0;0.0;0.18625277161862527;0.8137472283813747
$0;1339146582081606505;1339146582081597216;avanhoorn-thinkpad;1;0.008492569002123142;0.0021231422505307855;0.0;0.0;0.0;0.010615711252653927;0.9893842887473461
$1;1339146582082156365;1339146582082148613;avanhoorn-thinkpad;4046700544;1562091520;2484609024;3999260672;0;3999260672
$0;1339146587081469698;1339146587081450491;avanhoorn-thinkpad;0;0.04809619238476954;0.03206412825651302;0.01002004008016032;0.0;0.0;0.09018036072144288;0.9098196392785571
$0;1339146587081510904;1339146587081501615;avanhoorn-thinkpad;1;0.037037037037037035;0.04093567251461988;0.0;0.0;0.0;0.07797270955165692;0.9220272904483431
$1;1339146587082201914;1339146587082194092;avanhoorn-thinkpad;4046700544;1561714688;2484985856;3999260672;0;3999260672
$0;1339146592081494221;1339146592081473339;avanhoorn-thinkpad;0;0.08151093439363817;0.015904572564612324;0.041749502982107355;0.0;0.0019880715705765406;0.13916500994035785;0.856858846918489
</pre>
</div></div>
