### ISSUE TITLE
[KIEKER-699] Kieker Feedback from SEPVS Lecture (German)

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1338]
JIRA Issue: [KIEKER-699] Kieker Feedback from SEPVS Lecture (German)
Original Reporter: Jan Waller
 *** 
<p>Welche Probleme und Unklarheiten gab es bei der Verwendung von Kieker in Serie~1 und Serie~5? Gebt ein kurzes Feedback oder notiert Fragen&#33;</p>

[KIEKER-699]: https://kieker-monitoring.atlassian.net/browse/KIEKER-699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Wed, 16 May 2012 16:10:42 +0200
<p>Can we have this in english? <img class="emoticon" src="/images/icons/emoticons/wink.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

**Comment by rju** [comment]
author 557058:bdfe6e3a-bee5-45d9-89fc-6a6cea154b38 unknown Jira user -- Tue, 29 May 2012 01:49:56 +0200
<p>Zunächst direkt zum Quick Start Example: Hier würde ich schon auf die Instrumentierung mit Hilfe von Annotations stärker eingehen. Vielleicht kann man dieses Kapitel etwas ergänzen und ebenfalls zeigen, wie das Beispiel mit AOP aussehen würde. Auch um direkt zu zeigen, dass es erheblich weniger Aufwand ist, eine Anwendung zu instrumentieren, als dieses Kapitel beim blosen überfliegen vermuten lässt.</p>

<p>Ansonsten war die Instrumentierung der 1. Serie relativ easy zu machen, wenn man direkt zur AOP-basierten Untersuchung gesprungen ist. (Deshalb der Hinweis oben) Dies ging sogar ohne weiteres lesen der Einführung oder weiterer Kapitel. Dies könnte möglicherweise aber auch an der Einführung in Kieker aus der Vorlesung Softwarearchitektur liegen.</p>

**Comment by rju** [comment]
author 557058:8c40af5c-75e1-458e-9731-7131de0cae2f unknown Jira user -- Tue, 29 May 2012 09:12:45 +0200
<p>Zu Serie 1:<br/>
Wenn man weiß an welcher Stelle man suchen muss, ist es relativ einfach zu benutzen. Man muss nicht mal den kompletten Text aus dem Kapitel lesen. Es reicht, wenn man ihn überfliegt. Eine Sache vermisse ich (ich hoffe, dass ich es nicht übersehen habe): Eine genaue Beschreibung über den Aufbau der Log-Datei. An einer Stelle werden nur einzelne Spalten angesprochen, die für das Beispiel aus dem Guide wichtig sind. Falls es doch so eine Beschreibung geben sollte, dann wäre es gut, wenn man an der eben beschriebenen Stelle einen Verweis auf die komplette Beschreibung macht.</p>

<p>Zu Serie 5:<br/>
Ich habe nichts gefunden, wie man bei der Bytecode-Instrumentierung (über aop.xml) nur einzelne Methoden instrumentieren kann. Kapitel 5 zeigt nur, wie man einzelne Klassen annotieren kann. Außerdem hatte ich große Probleme beim Benutzen der trace-analysis.sh&#33; Obwohl ich nur Log-Daten über 5 min hatte, hat es das Tool nicht geschafft daraus die Execution Traces zu berechnen, obwohl ich die Speichereinstellungen für die JVM erhöht habe.</p>

**Comment by rju** [comment]
author 557058:0b822d96-e17d-4bf2-b9a7-48aa32d389f1 unknown Jira user -- Mon, 4 Jun 2012 11:26:19 +0200
<p>Bei der Verwendung von Kieker in Serie 1 und 5 sind wir streng nach der Anleitung vorgegangen. Dabei traten für Aufgabe 1 keine nennenswerten Probleme auf. Das Einbetten in Eclipse als Jar-Datei war komfortabel, der Import in den annotierten Klassen verständlich.</p>

<p>Etwas seltsam war das Erstellen der Konfigurationsdateien. Diese lagen im Kieker-Zip, dass man herunterladen konnte soweit wir uns erinnern nicht in einem Verzeichnis, wie das, welches man zum Kompilieren benötigt, sondern in mehreren Verzeichnissen. Das zusammensuchen der Demo-Konfiguration ist also verbesserungswürdig.</p>

<p>Bei der Verwendung für Aufgabe 5 dachten wir zunächst, wir könnten die Konfiguration 1:1 übernehmen, allerdings gab es dann folgende Fehlermeldung:</p>

<p>Mai 28, 2012 10:47:49 PM kieker.monitoring.writer.AbstractAsyncWriter newMonitoringRecord<br/>
Schwerwiegend: Failed to retrieve new monitoring record.<br/>
java.lang.IllegalStateException: Queue full<br/>
        at java.util.AbstractQueue.add(Unknown Source)<br/>
        at java.util.concurrent.ArrayBlockingQueue.add(Unknown Source)<br/>
        at kieker.monitoring.writer.AbstractAsyncWriter.newMonitoringRecord(AbstractAsyncWriter.java:135)<br/>
        at kieker.monitoring.core.controller.WriterController.newMonitoringRecord(WriterController.java:110)<br/>
        at kieker.monitoring.core.controller.MonitoringController.newMonitoringRecord(MonitoringController.java:202)<br/>
        at kieker.monitoring.probe.aspectj.operationExecution.AbstractOperationExecutionAspect.operation(AbstractOperationExecutionAspect.java:92)<br/>
        at stacks.Stack.pop(Stack.java:92)<br/>
        at misc.runMe$StackOperator.run(runMe.java:28)</p>

<p>Wie in der Fehlermeldung beschrieben ist die queue voll. In der Konfigurationsdatei gibt es aber zum Glück die Option, das Verhalten bei voller Queue festzulegen. Der sprechende Name der Option, und die Kommentierung sorgten dafür, dass nicht einmal ein Blick ins Handbuch erforderlich war, um ein Ausführen zu ermöglichen. kieker.monitoring.writer.filesystem.AsyncFsWriter.QueueFullBehavior=1 sorgt zwar dafür, dass die Ausführung temporär angehalten wird, um die queue zu leeren, aber das spielt bei der Demoanwendung in der Übungsaufgabe ja keine Rolle (nicht zeitkritisch).</p>

**Comment by rju** [comment]
author 557058:0aabfb8b-bfa6-4b05-8dd4-75cc398d13f3 unknown Jira user -- Mon, 4 Jun 2012 11:27:33 +0200
<ul>
	<li>Man musste in der Dateiablage des Kieker suchen wo welche Datei genau zu finden ist.</li>
	<li>Der Hinweis aus Übung 1 dass man in Kapitel 5.1.1 des Userguides eine einfache Form der Instrumentierung findet, war sehr hilfreich.</li>
	<li>Bei der Auswertung war es zunächst mühsam die Ergebnisdatei im Temp-Verzeichnis zu finden. Nach dem Fund war eine weitere Auswertung der „Zahlenkollonen“ nötig. Im Userguide ist – unserer Meinung nach – die Ergebnisdatei nicht gut genug dokumentiert (es wurde nur kurz erwähnt was welche Zahl zu bedeuten hat).</li>
</ul>

**Comment by rju** [comment]
author Jan Waller -- Mon, 4 Jun 2012 12:39:10 +0200
<p>These remarks should be included in further iterations of the Userguide and/or the developer guide.</p>

**Comment by rju** [comment]
author André van Hoorn -- Mon, 3 Sep 2012 12:26:13 +0200
<p>see also 
    <span class="jira-issue-macro" data-jira-key="KIEKER-977" >
                <a href="https://kieker-monitoring.atlassian.net/browse/KIEKER-977" class="jira-issue-macro-key issue-link"  title="Restructure user guide" >
            <img class="icon" src="https://kieker-monitoring.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />
            KIEKER-977
        </a>
                                                    <span class="aui-lozenge aui-lozenge-subtle aui-lozenge-complete jira-macro-single-issue-export-pdf">Open</span>
            </span>
</p>

**Comment by rju** [comment]
author André van Hoorn -- Tue, 15 Jan 2013 17:08:25 +0100
<p>Next step: Turn into tickets and close this one</p>

**Comment by rju** [comment]
author nils-christian -- Mon, 25 Feb 2013 17:23:36 +0100
<p>Replying to <span class="error">&#91;G05|comment:2&#93;</span>:<br/>
&gt; Eine Beispielausgabe und deren Analyse sollte in der Dokumentation vorhanden sein, damit man sich dort orientieren und mit seinen Ergebnissen vergleichen kann.<br/>
&gt; </p>

<p>I am not sure whether I understand the problem. There are example outputs in the appendix.</p>

<p>&gt; Ebenso sollte erwähnt werden, dass man den Pfad zum Java JDK in die Umgebungsvariable von Windows integrieren muss. Dies geschieht unter Windows 7 leider nicht mehr automatisch und somit lassen sich die angegebenen Befehle zunächst nicht ausführen.</p>

<p>I don't think that we should put this into the user guide. If one uses Kieker, they should know how to use Java and how to put this into the path etc. This can't be our job, I think.</p>

<p>Replying to <span class="error">&#91;G02|comment:3&#93;</span>:<br/>
&gt; Zunächst direkt zum Quick Start Example: Hier würde ich schon auf die Instrumentierung mit Hilfe von Annotations stärker eingehen. Vielleicht kann man dieses Kapitel etwas ergänzen und ebenfalls zeigen, wie das Beispiel mit AOP aussehen würde. Auch um direkt zu zeigen, dass es erheblich weniger Aufwand ist, eine Anwendung zu instrumentieren, als dieses Kapitel beim blosen überfliegen vermuten lässt.</p>

<p>Does this make sense? To show the AOP thing directly in the Quick Start Example?</p>

<p>&gt; <br/>
&gt; Ansonsten war die Instrumentierung der 1. Serie relativ easy zu machen, wenn man direkt zur AOP-basierten Untersuchung gesprungen ist. (Deshalb der Hinweis oben) Dies ging sogar ohne weiteres lesen der Einführung oder weiterer Kapitel. Dies könnte möglicherweise aber auch an der Einführung in Kieker aus der Vorlesung Softwarearchitektur liegen.</p>

<p>Replying to <span class="error">&#91;G07|comment:4&#93;</span>:<br/>
&gt; Zu Serie 1:<br/>
&gt; Wenn man weiß an welcher Stelle man suchen muss, ist es relativ einfach zu benutzen. Man muss nicht mal den kompletten Text aus dem Kapitel lesen. Es reicht, wenn man ihn überfliegt. Eine Sache vermisse ich (ich hoffe, dass ich es nicht übersehen habe): Eine genaue Beschreibung über den Aufbau der Log-Datei. An einer Stelle werden nur einzelne Spalten angesprochen, die für das Beispiel aus dem Guide wichtig sind. Falls es doch so eine Beschreibung geben sollte, dann wäre es gut, wenn man an der eben beschriebenen Stelle einen Verweis auf die komplette Beschreibung macht.</p>

<p>Well, this is shown, but I think we should explain the structure a little bit more.</p>

<p>&gt; <br/>
&gt; Zu Serie 5:<br/>
&gt; Ich habe nichts gefunden, wie man bei der Bytecode-Instrumentierung (über aop.xml) nur einzelne Methoden instrumentieren kann. Kapitel 5 zeigt nur, wie man einzelne Klassen annotieren kann. </p>

<p>Well, the <tt>OperationExecutionMonitoringProbe</tt> annotation is explained...</p>

<p>&gt; Außerdem hatte ich große Probleme beim Benutzen der trace-analysis.sh&#33; Obwohl ich nur Log-Daten über 5 min hatte, hat es das Tool nicht geschafft daraus die Execution Traces zu berechnen, obwohl ich die Speichereinstellungen für die JVM erhöht habe.</p>

<p>This was indeed a big problem in this series, if I remember correctly. The log files were too big. Maybe we should check whether it was a problem with the log files or with our own tool.</p>

<p>Replying to <span class="error">&#91;G03|comment:5&#93;</span>:<br/>
&gt; Bei der Verwendung von Kieker in Serie 1 und 5 sind wir streng nach der Anleitung vorgegangen. Dabei traten für Aufgabe 1 keine nennenswerten Probleme auf. Das Einbetten in Eclipse als Jar-Datei war komfortabel, der Import in den annotierten Klassen verständlich.<br/>
&gt; <br/>
&gt; Etwas seltsam war das Erstellen der Konfigurationsdateien. Diese lagen im Kieker-Zip, dass man herunterladen konnte soweit wir uns erinnern nicht in einem Verzeichnis, wie das, welches man zum Kompilieren benötigt, sondern in mehreren Verzeichnissen. Das zusammensuchen der Demo-Konfiguration ist also verbesserungswürdig.</p>

<p>Which files do they mean exactly?</p>

<p>&gt; <br/>
&gt; Bei der Verwendung für Aufgabe 5 dachten wir zunächst, wir könnten die Konfiguration 1:1 übernehmen, allerdings gab es dann folgende Fehlermeldung:<br/>
&gt; <br/>
&gt; Mai 28, 2012 10:47:49 PM kieker.monitoring.writer.AbstractAsyncWriter newMonitoringRecord<br/>
&gt; Schwerwiegend: Failed to retrieve new monitoring record.<br/>
&gt; java.lang.IllegalStateException: Queue full<br/>
&gt;         at java.util.AbstractQueue.add(Unknown Source)<br/>
&gt;         at java.util.concurrent.ArrayBlockingQueue.add(Unknown Source)<br/>
&gt;         at kieker.monitoring.writer.AbstractAsyncWriter.newMonitoringRecord(AbstractAsyncWriter.java:135)<br/>
&gt;         at kieker.monitoring.core.controller.WriterController.newMonitoringRecord(WriterController.java:110)<br/>
&gt;         at kieker.monitoring.core.controller.MonitoringController.newMonitoringRecord(MonitoringController.java:202)<br/>
&gt;         at kieker.monitoring.probe.aspectj.operationExecution.AbstractOperationExecutionAspect.operation(AbstractOperationExecutionAspect.java:92)<br/>
&gt;         at stacks.Stack.pop(Stack.java:92)<br/>
&gt;         at misc.runMe$StackOperator.run(runMe.java:28)<br/>
&gt; 		<br/>
&gt; Wie in der Fehlermeldung beschrieben ist die queue voll. In der Konfigurationsdatei gibt es aber zum Glück die Option, das Verhalten bei voller Queue festzulegen. Der sprechende Name der Option, und die Kommentierung sorgten dafür, dass nicht einmal ein Blick ins Handbuch erforderlich war, um ein Ausführen zu ermöglichen. kieker.monitoring.writer.filesystem.AsyncFsWriter.QueueFullBehavior=1 sorgt zwar dafür, dass die Ausführung temporär angehalten wird, um die queue zu leeren, aber das spielt bei der Demoanwendung in der Übungsaufgabe ja keine Rolle (nicht zeitkritisch).</p>

<p>I remember this problem as well. But it is good to read that they could solve the problem without looking into the user guide.</p>


<p>Replying to <span class="error">&#91;G08|comment:6&#93;</span>:<br/>
&gt; * Man musste in der Dateiablage des Kieker suchen wo welche Datei genau zu finden ist.</p>

<p>I think we mentioned this already somewhere. That we should maybe put the jar files directly into the example directories.</p>

<p>&gt; * Der Hinweis aus Übung 1 dass man in Kapitel 5.1.1 des Userguides eine einfache Form der Instrumentierung findet, war sehr hilfreich.<br/>
&gt; * Bei der Auswertung war es zunächst mühsam die Ergebnisdatei im Temp-Verzeichnis zu finden. Nach dem Fund war eine weitere Auswertung der „Zahlenkollonen“ nötig. Im Userguide ist – unserer Meinung nach – die Ergebnisdatei nicht gut genug dokumentiert (es wurde nur kurz erwähnt was welche Zahl zu bedeuten hat).</p>

<p>As mentioned above. We should explain this a little bit more.</p>

**Comment by rju** [comment]
author nils-christian -- Mon, 25 Feb 2013 17:25:21 +0100
<p>To summarize this:</p>
<ul>
	<li>Explain the structure of our log files more precisely.</li>
	<li>Put the jar files directly into the example directories; Check whether all files can be found easily <img class="emoticon" src="/images/icons/emoticons/help_16.png" height="16" width="16" align="absmiddle" alt="" border="0"/></li>
	<li>Maybe restructure our quick start chapter.</li>
</ul>

**Comment by rju** [comment]
author Jan Waller -- Mon, 25 Feb 2013 17:50:36 +0100
<p>Nils Christian Ehmke<br/>
Can you extract the tasks into new tickets and close this one?</p>

**Comment by rju** [comment]
author nils-christian -- Mon, 25 Feb 2013 17:59:05 +0100
<p>
    <span class="jira-issue-macro resolved" data-jira-key="KIEKER-641" >
                <a href="https://kieker-monitoring.atlassian.net/browse/KIEKER-641" class="jira-issue-macro-key issue-link"  title="Explain the structure of the log files" >
            <img class="icon" src="https://kieker-monitoring.atlassian.net/images/icons/issuetypes/genericissue.png" />
            KIEKER-641
        </a>
                                                    <span class="aui-lozenge aui-lozenge-subtle aui-lozenge-success jira-macro-single-issue-export-pdf">Done</span>
            </span>
<br/>

    <span class="jira-issue-macro resolved" data-jira-key="KIEKER-163" >
                <a href="https://kieker-monitoring.atlassian.net/browse/KIEKER-163" class="jira-issue-macro-key issue-link"  title="Restructure Quick Start Example" >
            <img class="icon" src="https://kieker-monitoring.atlassian.net/images/icons/issuetypes/genericissue.png" />
            KIEKER-163
        </a>
                                                    <span class="aui-lozenge aui-lozenge-subtle aui-lozenge-success jira-macro-single-issue-export-pdf">Done</span>
            </span>
<br/>

    <span class="jira-issue-macro resolved" data-jira-key="KIEKER-892" >
                <a href="https://kieker-monitoring.atlassian.net/browse/KIEKER-892" class="jira-issue-macro-key issue-link"  title="Check files locations" >
            <img class="icon" src="https://kieker-monitoring.atlassian.net/images/icons/issuetypes/genericissue.png" />
            KIEKER-892
        </a>
                                                    <span class="aui-lozenge aui-lozenge-subtle aui-lozenge-success jira-macro-single-issue-export-pdf">Done</span>
            </span>
<br/>

    <span class="jira-issue-macro resolved" data-jira-key="KIEKER-901" >
                <a href="https://kieker-monitoring.atlassian.net/browse/KIEKER-901" class="jira-issue-macro-key issue-link"  title="Execution traces from big log files" >
            <img class="icon" src="https://kieker-monitoring.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />
            KIEKER-901
        </a>
                                                    <span class="aui-lozenge aui-lozenge-subtle aui-lozenge-success jira-macro-single-issue-export-pdf">Done</span>
            </span>
</p>

<p>Those should be the important points.</p>
