### ISSUE TITLE
[KIEKER-164] Problems shutting down monitoring using the Shutdownhook (in a Spring deployment scenario)

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1348]
JIRA Issue: [KIEKER-164] Problems shutting down monitoring using the Shutdownhook (in a Spring deployment scenario)
Original Reporter: Andre van Hoorn
 *** 
<p>Sönke reported a problem that occurs during shutdown in a Spring deployment scenario:<br/>
1. Letting monitoring being shut down using the (always enabled) <tt>Shutdownhook</tt>, this <tt>Shutdownhook</tt> blocks until the configured timeout elapses.<br/>
1. When additionally adding an explicit call the <tt>MonitoringController</tt>'s <tt>terminate</tt> method, a <tt>NullPointerException</tt> occurs.</p>

<p>One of the suggestions Sönke made was that the <tt>Shutdownhook</tt> should not be enabled automatically, but that this should be configurable via a <tt>Configuration</tt> property.</p>

[KIEKER-164]: https://kieker-monitoring.atlassian.net/browse/KIEKER-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Mon, 23 Apr 2012 19:34:24 +0200
<p>For Kieker's JPetStore example, I could not reproduce this issue:</p>

<p>1. Starting the Tomcat including JPetStore</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>avanhoornavanhoorn-thinkpad:0:~/svn_work/phd_vanhoorn/talks/120424-ICPE-Demo/kieker-1.5-binaries/examples/JavaEEServletContainerExample/Tomcat6.0.18WithJpetStore-withInstrumentedJPetStore $ bin/startup.sh 
Using default value for HEAPSIZEINIT 256m
Using default value for HEAPSIZEMAX 384m
Using CATALINA_BASE:   /home/avanhoorn/svn_work/phd_vanhoorn/talks/120424-ICPE-Demo/kieker-1.5-binaries/examples/JavaEEServletContainerExample/Tomcat6.0.18WithJpetStore-withInstrumentedJPetStore
Using CATALINA_HOME:   /home/avanhoorn/svn_work/phd_vanhoorn/talks/120424-ICPE-Demo/kieker-1.5-binaries/examples/JavaEEServletContainerExample/Tomcat6.0.18WithJpetStore-withInstrumentedJPetStore
Using CATALINA_TMPDIR: /home/avanhoorn/svn_work/phd_vanhoorn/talks/120424-ICPE-Demo/kieker-1.5-binaries/examples/JavaEEServletContainerExample/Tomcat6.0.18WithJpetStore-withInstrumentedJPetStore/temp
Using JRE_HOME:       /usr
</pre>
</div></div>

<p>2. Performed some clicks in the JPetStore</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>avanhoornavanhoorn-thinkpad:0:~/svn_work/phd_vanhoorn/talks/120424-ICPE-Demo/kieker-1.5-binaries/examples/JavaEEServletContainerExample/Tomcat6.0.18WithJpetStore-withInstrumentedJPetStore $ cat logs/access_log.txt 
0:0:0:0:0:0:0:1 [23/Apr/2012:13:23:16 -0400] GET /jpetstore/shop/index.shtml "" 200 4644 1782F3E1304FE2316A9B2BCB738BE6CB 1717
0:0:0:0:0:0:0:1 [23/Apr/2012:13:23:17 -0400] GET /jpetstore/shop/viewCategory.shtml "?categoryId=DOGS" 200 3711 1782F3E1304FE2316A9B2BCB738BE6CB 191
</pre>
</div></div>

<p>3. Shutting the Tomcat</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>avanhoornavanhoorn-thinkpad:0:~/svn_work/phd_vanhoorn/talks/120424-ICPE-Demo/kieker-1.5-binaries/examples/JavaEEServletContainerExample/Tomcat6.0.18WithJpetStore-withInstrumentedJPetStore $ bin/shutdown.sh 
Using default value for HEAPSIZEINIT 256m
Using default value for HEAPSIZEMAX 384m
Using CATALINA_BASE:   /home/avanhoorn/svn_work/phd_vanhoorn/talks/120424-ICPE-Demo/kieker-1.5-binaries/examples/JavaEEServletContainerExample/Tomcat6.0.18WithJpetStore-withInstrumentedJPetStore
Using CATALINA_HOME:   /home/avanhoorn/svn_work/phd_vanhoorn/talks/120424-ICPE-Demo/kieker-1.5-binaries/examples/JavaEEServletContainerExample/Tomcat6.0.18WithJpetStore-withInstrumentedJPetStore
Using CATALINA_TMPDIR: /home/avanhoorn/svn_work/phd_vanhoorn/talks/120424-ICPE-Demo/kieker-1.5-binaries/examples/JavaEEServletContainerExample/Tomcat6.0.18WithJpetStore-withInstrumentedJPetStore/temp
Using JRE_HOME:       /usr
</pre>
</div></div>

<p>4. Inspecting the logs</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>avanhoornavanhoorn-thinkpad:0:~/svn_work/phd_vanhoorn/talks/120424-ICPE-Demo/kieker-1.5-binaries/examples/JavaEEServletContainerExample/Tomcat6.0.18WithJpetStore-withInstrumentedJPetStore $ cat logs/catalina.out 
[StandardClassLoader1d2068d] warning javax.* types are not being woven because the weaver option '-Xset:weaveJavaxPackages=true' has not been specified
Apr 23, 2012 1:23:03 PM org.apache.catalina.core.AprLifecycleListener init
INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/lib/jvm/java-6-sun-1.6.0.26/jre/lib/i386/server:/usr/lib/jvm/java-6-sun-1.6.0.26/jre/lib/i386:/usr/lib/jvm/java-6-sun-1.6.0.26/jre/../lib/i386:/usr/lib/R/lib:/usr/lib/R/bin::/usr/local/lib/R/site-library/rJava/jri/:/usr/java/packages/lib/i386:/lib:/usr/lib
Apr 23, 2012 1:23:03 PM org.apache.coyote.http11.Http11Protocol init
INFO: Initializing Coyote HTTP/1.1 on http-8081
Apr 23, 2012 1:23:03 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 563 ms
Apr 23, 2012 1:23:03 PM org.apache.catalina.core.StandardService start
INFO: Starting service Catalina
Apr 23, 2012 1:23:03 PM org.apache.catalina.core.StandardEngine start
INFO: Starting Servlet Engine: Apache Tomcat/6.0.18
Apr 23, 2012 1:23:03 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive jpetstore.war
Apr 23, 2012 1:23:04 PM kieker.monitoring.core.configuration.ConfigurationFactory createSingletonConfiguration
INFO: Loading configuration from JVM-specified location: '/home/avanhoorn/svn_work/phd_vanhoorn/talks/120424-ICPE-Demo/kieker-1.5-binaries/examples/JavaEEServletContainerExample/Tomcat6.0.18WithJpetStore-withInstrumentedJPetStore/lib/META-INF/kieker.monitoring.properties'
Apr 23, 2012 1:23:04 PM kieker.monitoring.core.controller.MonitoringController createInstance
INFO: Current State of kieker.monitoring (1.5) Status: 'enabled'
        Name: 'KIEKER'; Hostname: 'avanhoorn-thinkpad'; experimentID: '1'
JMXController: JMX disabled
RegistryController: 0 strings registered.
TimeSource: 'kieker.monitoring.timer.SystemNanoTimer'
        Time in nanoseconds (with nanoseconds precision) since Wed Dec 31 19:00:00 EST 1969'
WriterController:
        Number of Inserts: '0'
        Automatic assignment of logging timestamps: 'true'
Writer: 'kieker.monitoring.writer.filesystem.AsyncFsWriter'
        Configuration:
                kieker.monitoring.writer.filesystem.AsyncFsWriter.QueueFullBehavior='0'
                kieker.monitoring.writer.filesystem.AsyncFsWriter.flush='true'
                kieker.monitoring.writer.filesystem.AsyncFsWriter.QueueSize='10000'
                kieker.monitoring.writer.filesystem.AsyncFsWriter.customStoragePath='.'
                kieker.monitoring.writer.filesystem.AsyncFsWriter.MaxShutdownDelay='-1'
                kieker.monitoring.writer.filesystem.AsyncFsWriter.storeInJavaIoTmpdir='true'
                kieker.monitoring.writer.filesystem.AsyncFsWriter.maxEntriesInFile='25000'
        Records lost: 0
        Writer Threads (1): 
                Finished: 'false'; Writing to Directory: '/home/avanhoorn/svn_work/phd_vanhoorn/talks/120424-ICPE-Demo/kieker-1.5-binaries/examples/JavaEEServletContainerExample/Tomcat6.0.18WithJpetStore-withInstrumentedJPetStore/temp/kieker-20120423-172304877-UTC-avanhoorn-thinkpad-KIEKER'
Sampling Controller: Periodic Sensor available: Current Poolsize: '0'; Scheduled Tasks: '0'

Apr 23, 2012 1:23:04 PM kieker.monitoring.core.registry.ControlFlowRegistry &lt;clinit&gt;
INFO: First threadId will be 6468154227322519552
Apr 23, 2012 1:23:04 PM kieker.monitoring.probe.servlet.SessionAndTraceRegistrationFilter init
WARNING: Filter configuration 'logFilterExecution' not set. Using the value: true
Apr 23, 2012 1:23:05 PM org.apache.struts.validator.ValidatorPlugIn initResources
INFO: Loading validation rules file from '/WEB-INF/validator-rules.xml'
Apr 23, 2012 1:23:05 PM org.apache.struts.validator.ValidatorPlugIn initResources
INFO: Loading validation rules file from '/WEB-INF/validation.xml'
Apr 23, 2012 1:23:06 PM org.apache.coyote.http11.Http11Protocol start
INFO: Starting Coyote HTTP/1.1 on http-8081
Apr 23, 2012 1:23:06 PM org.apache.jk.common.ChannelSocket init
INFO: JK: ajp13 listening on /0.0.0.0:8009
Apr 23, 2012 1:23:06 PM org.apache.jk.server.JkMain start
INFO: Jk running ID=0 time=0/43  config=null
Apr 23, 2012 1:23:06 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 2531 ms
Apr 23, 2012 1:23:22 PM org.apache.coyote.http11.Http11Protocol pause
INFO: Pausing Coyote HTTP/1.1 on http-8081
Apr 23, 2012 1:23:23 PM org.apache.catalina.core.StandardService stop
INFO: Stopping service Catalina
Apr 23, 2012 1:23:23 PM org.apache.coyote.http11.Http11Protocol destroy
INFO: Stopping Coyote HTTP/1.1 on http-8081
Apr 23, 2012 1:23:23 PM kieker.monitoring.core.controller.MonitoringController$1 run
INFO: ShutdownHook notifies controller to initiate shutdown
Apr 23, 2012 1:23:23 PM kieker.monitoring.core.controller.MonitoringController cleanup
INFO: Shutting down Monitoring Controller (KIEKER)
Apr 23, 2012 1:23:23 PM kieker.monitoring.writer.AbstractAsyncWriter terminate
INFO: Shutting down writers.
Apr 23, 2012 1:23:23 PM kieker.monitoring.writer.AbstractAsyncWriter terminate
INFO: Writer shutdown complete.
</pre>
</div></div>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>avanhoornavanhoorn-thinkpad:0:~/svn_work/phd_vanhoorn/talks/120424-ICPE-Demo/kieker-1.5-binaries/examples/JavaEEServletContainerExample/Tomcat6.0.18WithJpetStore-withInstrumentedJPetStore $ cat logs/localhost.2012-04-23.log 
Apr 23, 2012 1:23:05 PM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: contextInitialized()
Apr 23, 2012 1:23:05 PM org.apache.catalina.core.ApplicationContext log
INFO: SessionListener: contextInitialized()
Apr 23, 2012 1:23:23 PM org.apache.catalina.session.StandardSession writeObject
WARNING: Cannot serialize session attribute catalogBean for session 1782F3E1304FE2316A9B2BCB738BE6CB
java.io.NotSerializableException: org.apache.struts.beanaction.DefaultActionInterceptor
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1164)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1518)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1483)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1400)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1158)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:330)
        at org.apache.catalina.session.StandardSession.writeObject(StandardSession.java:1517)
        at org.apache.catalina.session.StandardSession.writeObjectData(StandardSession.java:959)
        at org.apache.catalina.session.StandardManager.doUnload(StandardManager.java:517)
        at org.apache.catalina.session.StandardManager.unload(StandardManager.java:463)
        at org.apache.catalina.session.StandardManager.stop(StandardManager.java:667)
        at org.apache.catalina.core.StandardContext.stop(StandardContext.java:4519)
        at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:924)
        at org.apache.catalina.startup.HostConfig.undeployApps(HostConfig.java:1191)
        at org.apache.catalina.startup.HostConfig.stop(HostConfig.java:1162)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:313)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
        at org.apache.catalina.core.ContainerBase.stop(ContainerBase.java:1086)
        at org.apache.catalina.core.ContainerBase.stop(ContainerBase.java:1098)
        at org.apache.catalina.core.StandardEngine.stop(StandardEngine.java:448)
        at org.apache.catalina.core.StandardService.stop(StandardService.java:584)
        at org.apache.catalina.core.StandardServer.stop(StandardServer.java:744)
        at org.apache.catalina.startup.Catalina.stop(Catalina.java:628)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:603)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:288)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:413)
Apr 23, 2012 1:23:23 PM org.apache.catalina.core.ApplicationContext log
INFO: SessionListener: contextDestroyed()
Apr 23, 2012 1:23:23 PM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: contextDestroyed()
</pre>
</div></div>

**Comment by rju** [comment]
author André van Hoorn -- Mon, 23 Apr 2012 19:34:54 +0200
<p>Now also the right ticket for this:</p>

<p>Sönke: Could you please provide us with the stack trace? Also: Does this problem occur also outside Eclipse.</p>

**Comment by rju** [comment]
author Jan Waller -- Fri, 27 Apr 2012 09:55:02 +0200
<p>05de12ee3e35009b556000128800094d5670dd17</p>

<p>Added a configuration parameter to disable the shutdown hook.</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre># Whether a shutdown hook should be registered.
# This ensures that necessary cleanup steps are finished and no 
# information is lost due to asynchronous writers.
# This should usually not be set to false.
kieker.monitoring.useShutdownHook=true
</pre>
</div></div>

**Comment by rju** [comment]
author Jan Waller -- Fri, 27 Apr 2012 09:55:46 +0200
<p>We need a reassign to nobody <img class="emoticon" src="/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

**Comment by rju** [comment]
author Sönke Reimer -- Thu, 10 May 2012 14:51:57 +0200
<p>Andre:<br/>
What I can see so far, it's exact the same problem outside eclipse.<br/>
I used tomcat 6.0.14 with jdk 1.5.0_15 and kieker 1.5</p>

<p>If I let the ShutdownHook termine monitoring, tomcat hangs on shutdown, if I terminate monitoring additionally in spring, the following exception occurres due to statecontroller being 'null' in MonitorController instance on isMonitoringTerminated():</p>

<p>The following exception occurres, when I try to terminate Kieker on spring shutdown:</p>


<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>13:56:47,696 INFO  [(,,),(),() MonitoringController] Shutting down Monitoring Controller (KIEKER-SINGLETON)
13:56:47,696 DEBUG [(,,),(),() StateController] Shutting down State Controller
13:56:47,696 DEBUG [(,,),(),() TimeSourceController] Shutting down TimeSource Controller
13:56:47,696 DEBUG [(,,),(),() SamplingController] Shutting down Sampling Controller
13:56:47,696 DEBUG [(,,),(),() WriterController] Shutting down Writer Controller
13:56:47,696 INFO  [(,,),(),() AbstractAsyncWriter] Shutting down writers, waiting at most 5000 milliseconds.
13:56:47,696 DEBUG [(,,),(),() AbstractAsyncThread] Terminating writer thread, 0 entries remaining
13:56:47,698 INFO  [(,,),(),() AbstractAsyncWriter] Writer shutdown complete.
13:56:47,698 DEBUG [(,,),(),() AbstractAsyncThread] Writer thread finished
13:56:47,698 DEBUG [(,,),(),() RegistryController] Shutting down Registry Controller
10.05.2012 13:56:49 org.apache.coyote.http11.Http11Protocol destroy
INFO: Stopping Coyote HTTP/1.1 on http-8080
Exception in thread "Thread-3" java.lang.NullPointerException
	at kieker.monitoring.core.controller.MonitoringController.isMonitoringTerminated(MonitoringController.java:170)
	at kieker.monitoring.core.controller.MonitoringController$1.run(MonitoringController.java:105)
</pre>
</div></div>


<p>So I will use the new configuration parameter with 'false'.</p>

**Comment by rju** [comment]
author André van Hoorn -- Mon, 3 Sep 2012 13:50:14 +0200
<p>We should try to figure out, why Tomcat hangs when Kieker's shutdown hook is used ... </p>

<p>(at least, we have a work-around)</p>
