### ISSUE TITLE
[KIEKER-577] Error executing JMS Example with ActiveMQ 5.5.1 under Windows

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1370]
JIRA Issue: [KIEKER-577] Error executing JMS Example with ActiveMQ 5.5.1 under Windows
Original Reporter: Andre van Hoorn
 *** 
<p>Executing the JMS example with ActiveMQ 5.5.1 under Windows, Nils reported the following error:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>[java] Warnung: Failed to lookup queue 'queue1' via JNDI
 [java] javax.naming.NameNotFoundException: queue1
 [java]     at
org.apache.activemq.jndi.ReadOnlyContext.lookup(ReadOnlyContext.java:235)
 [java]     at javax.naming.InitialContext.lookup(InitialContext.java:411)
 [java]     at
kieker.analysis.plugin.reader.jms.JMSReader.read(JMSReader.java:131)
 [java]     at
kieker.analysis.AnalysisController$1.run(AnalysisController.java:619)
 [java]     at java.lang.Thread.run(Thread.java:722)
 [java]
</pre>
</div></div>

**Comment by rju** [comment]
author André van Hoorn -- Wed, 11 Apr 2012 17:08:20 +0200
<p>Fixed in fcdfa59aa04c26cbd351e9401cf54d36509895ad:</p>

<p>Actually this wasn't a bug but a misleading logging of a stack trace of a caught exception:<br/>
The stack trace was dumped while attempting to connect with an alternative method, which in the end works for ActiveMQ and HornetQ. I cleaned up the error reporting in the JMS reader/writer. </p>

<p>Nils Christian Ehmke: Could you test this again, please? If the problem is not fixed, please reopen.</p>

**Comment by rju** [comment]
author André van Hoorn -- Wed, 11 Apr 2012 22:27:38 +0200
<p>According to Nils, the following WARNING occurring for ActiveMQ/HornetQ still seems to be confusing</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>avanhoornavanhoorn-thinkpad:0:~/git_work/kieker/examples/userguide/appendix-JMS &lt;master&gt; $ ant run-analysis-activemq 
...

run-analysis-activemq:
     [java] jms-connection-factory:org.apache.activemq.jndi.ActiveMQInitialContextFactory
     [java] jms-provider-url:      tcp://127.0.0.1:61616/
     [java] jms-queue:             queue1
     [java] 
     [java] 0    WARN  [Thread-1] org.apache.activemq.transport.tcp.TcpTransportFactory     - path isn't a valid local location for TcpTransport to use
     [java] Apr 11, 2012 10:17:22 PM kieker.analysis.plugin.reader.jms.JMSReader read
     [java] WARNING: Failed to lookup queue 'queue1' via JNDI: queue1
     [java] Apr 11, 2012 10:17:22 PM kieker.analysis.plugin.reader.jms.JMSReader read
     [java] INFO: Attempting to create queue ...
     [java] Apr 11, 2012 10:17:22 PM kieker.analysis.plugin.reader.jms.JMSReader read
     [java] INFO: Listening to destination:queue://queue1 at tcp://127.0.0.1:61616/ !
     [java] ***
     [java] 
     [java] 
     [java] Apr 11, 2012 10:17:23 PM kieker.analysis.plugin.reader.jms.JMSReader read
     [java] INFO: JMSReader started and waits for incomming monitoring events!

</pre>
</div></div>

<p>In 22c60e0c30888e5e5c518bb1c6a929684fafeead, removed this WARNING (the remaining one is printed by ActiveMQ):</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>...
     [java] jms-connection-factory:org.apache.activemq.jndi.ActiveMQInitialContextFactory
     [java] jms-provider-url:      tcp://127.0.0.1:61616/
     [java] jms-queue:             queue1
     [java] 
     [java] 0    WARN  [Thread-1] org.apache.activemq.transport.tcp.TcpTransportFactory     - path isn't a valid local location for TcpTransport to use
     [java] Apr 11, 2012 10:23:19 PM kieker.analysis.plugin.reader.jms.JMSReader read
     [java] INFO: Listening to destination:queue://queue1 at tcp://127.0.0.1:61616/ !
     [java] ***
     [java] 
     [java] 
     [java] Apr 11, 2012 10:23:19 PM kieker.analysis.plugin.reader.jms.JMSReader read
     [java] INFO: JMSReader started and waits for incoming monitoring events!
...
</pre>
</div></div>
