### ISSUE TITLE
[KIEKER-479] Non-Working FSReader?

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1397]
JIRA Issue: [KIEKER-479] Non-Working FSReader?
Original Reporter: Nils Christian Ehmke
 *** 
<p>It seems like the FSReader is not working properly. Trying to execute a simple task via the TraceAnalysis-Tool:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>Exception in thread "Thread-1" java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at kieker.analysis.reader.filesystem.FSDirectoryReader.processNormalInputFile(FSDirectoryReader.java:230)
        at kieker.analysis.reader.filesystem.FSDirectoryReader.run(FSDirectoryReader.java:124)
        at java.lang.Thread.run(Thread.java:722)

</pre>
</div></div>

<p>(Or are there now problems with "old" monitored data due to the modified structure of the records?)</p>

[KIEKER-479]: https://kieker-monitoring.atlassian.net/browse/KIEKER-479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Thu, 22 Mar 2012 16:28:27 +0100
<p>This is probably caused by the changes in KIEK-282:</p>

<p>We had to switch from the arrays functions provided by <tt>Arrays</tt> (Java 1.6+) to those provided by <tt>System</tt></p>

**Comment by rju** [comment]
author Jan Waller -- Thu, 22 Mar 2012 19:03:03 +0100
<p>fixed in 4c2380d6b925384bbc78d2ee5f218a097d4407bf</p>
