### ISSUE TITLE
[KIEKER-460] Uncaught exception in FSDirectoryReader for invalid records

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1488]
JIRA Issue: [KIEKER-460] Uncaught exception in FSDirectoryReader for invalid records
Original Reporter: Andre van Hoorn
 *** 
<p>Currently, an (uncaught) Exception is thrown:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>$ ${KIEKER_HOME}/bin/trace-analysis.sh -i /path/to/kieker-20111220-074333689-UTC-HOST-KIEKER/ -o out/ -p kieker-20111220-074333689-HOST-AP032- --plot-Deployment-Component-Dependency-Graph
#
# Configuration
--inputdirs: /path/to/kieker-20111220-074333689-UTC-HOST-KIEKER/
--outputdir: out//
--output-filename-prefix: kieker-20111220-074333689-UTC-HOST-
--plot-Deployment-Sequence-Diagrams: false
--plot-Assembly-Sequence-Diagrams: false
--plot-Deployment-Component-Dependency-Graph: true
--plot-Assembly-Component-Dependency-Graph: false
--plot-Container-Dependency-Graph: false
--plot-Deployment-Operation-Dependency-Graph: false
--plot-Assembly-Operation-Dependency-Graph: false
--plot-Aggregated-Deployment-Call-Tree: false
--plot-Aggregated-Assembly-Call-Tree: false
--plot-Call-Trees: false
--print-Message-Traces: false
--print-Execution-Traces: false
--print-invalid-Execution-Traces: false
--print-Deployment-Equivalence-Classes: false
--print-Assembly-Equivalence-Classes: false
--select-traces: &lt;select all&gt;
--ignore-invalid-traces: false
--max-trace-duration: 600000 ms
--ignore-executions-before-date: Thu, 1 Jan 1970 00:00:00 +0000 (UTC) (Thu, 1 Jan 1970 01:00:00 +0100 (local time))
--ignore-executions-after-date: Fri, 11 Apr 2262 23:47:16 +0000 (UTC) (Sat, 12 Apr 2262 01:47:16 +0200 (local time))
--short-labels: false
Exception in thread "Reader thread for /path/to/kieker-20111220-074333689-UTC-HOST-KIEKER/" java.lang.ArrayIndexOutOfBoundsException: 5
        at kieker.analysis.reader.filesystem.FSDirectoryReader.fromStringToTypedArray(FSDirectoryReader.java:336)
        at kieker.analysis.reader.filesystem.FSDirectoryReader.processInputFile(FSDirectoryReader.java:284)
        at kieker.analysis.reader.filesystem.FSDirectoryReader.read(FSDirectoryReader.java:133)
        at kieker.analysis.reader.filesystem.FSReaderCons$1.run(FSReaderCons.java:115)
        at java.lang.Thread.run(Thread.java:662)

</pre>
</div></div>

<p>(Note that this occurred with Kieker 1.4)</p>

[KIEKER-460]: https://kieker-monitoring.atlassian.net/browse/KIEKER-460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Thu, 19 Jan 2012 13:16:13 +0100
<p>Also, the causing line should be printed to the log.</p>

**Comment by rju** [comment]
author Jan Waller -- Tue, 14 Feb 2012 22:04:55 +0100
<p>This should not be possible in Kieker 1.5+</p>
