### ISSUE TITLE
[KIEKER-366] JUnit errors in branch 1.5-analysis: java.lang.annotation.AnnotationFormatError

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1493]
JIRA Issue: [KIEKER-366] JUnit errors in branch 1.5-analysis: java.lang.annotation.AnnotationFormatError
Original Reporter: Andre van Hoorn
 *** 
<p>Currently 41 of all JUnit tests terminate with an <tt>AnnotationFormatError</tt>:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>testNamedPipeReaderReceivesFromPipe	Error	Unexpected end of annotations.

java.lang.annotation.AnnotationFormatError: Unexpected end of annotations.
at java.lang.Class.initAnnotationsIfNecessary(Class.java:3070)
at java.lang.Class.getAnnotation(Class.java:3029)
at kieker.analysis.plugin.AbstractPlugin.(AbstractPlugin.java:77)
at kieker.analysis.reader.AbstractReaderPlugin.(AbstractReaderPlugin.java:21)
at kieker.analysis.reader.namedRecordPipe.PipeReader.(PipeReader.java:64)
at kieker.test.analysis.junit.reader.namedRecordPipe.TestPipeReader.testNamedPipeReaderReceivesFromPipe(Unknown 
</pre>
</div></div>

<p>Executed the JUnit tests with ant from the command line:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>voornpc-vanhoorn:0:~/git_work/kieker &lt;1.5-analysis&gt; $ ant run-tests-junit 
Buildfile: build.xml

...

run-tests-junit:
   [delete] Deleting directory /home/voorn/git_work/kieker/tmp/junit-results
    [mkdir] Created dir: /home/voorn/git_work/kieker/tmp/junit-results
    [junit] Log file : /home/voorn/git_work/kieker/./serenity/serenity.log
    [junit] Log4j stream : sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream19ee1ac
    [junit] Running kieker.test.analysis.junit.AnalysisTest
    [junit] Tests run: 5, Failures: 0, Errors: 5, Time elapsed: 0,345 sec
    [junit] TEST kieker.test.analysis.junit.AnalysisTest FAILED
    [junit] Running kieker.test.analysis.junit.plugin.GeneralPluginTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Time elapsed: 0,024 sec
    [junit] TEST kieker.test.analysis.junit.plugin.GeneralPluginTest FAILED
    [junit] Running kieker.test.analysis.junit.plugin.SilentCountingRecordConsumerTest
    [junit] Tests run: 3, Failures: 0, Errors: 3, Time elapsed: 0,015 sec
    [junit] TEST kieker.test.analysis.junit.plugin.SilentCountingRecordConsumerTest FAILED
    [junit] Running kieker.test.analysis.junit.reader.namedRecordPipe.TestPipeReader
    [junit] Tests run: 1, Failures: 0, Errors: 1, Time elapsed: 0,014 sec
    [junit] TEST kieker.test.analysis.junit.reader.namedRecordPipe.TestPipeReader FAILED
    [junit] Running kieker.test.common.junit.TestOperationExecutionRecord
    [junit] Tests run: 4, Failures: 0, Errors: 0, Time elapsed: 0,134 sec
    [junit] Running kieker.test.monitoring.junit.core.TestAutoSetLoggingTimestamp
    [junit] Tests run: 2, Failures: 0, Errors: 0, Time elapsed: 0,417 sec
    [junit] Running kieker.test.monitoring.junit.core.TestControllerConstruction
    [junit] Tests run: 2, Failures: 0, Errors: 0, Time elapsed: 0,237 sec
    [junit] Running kieker.test.monitoring.junit.core.TestMonitoringControllerRecordsPassedInMonitoringStates
    [junit] Tests run: 3, Failures: 0, Errors: 0, Time elapsed: 0,023 sec
    [junit] Running kieker.test.monitoring.junit.core.TestMonitoringControllerStateTransitions
    [junit] Tests run: 6, Failures: 0, Errors: 0, Time elapsed: 0,047 sec
    [junit] Running kieker.test.monitoring.junit.core.TestPeriodicSampling
    [junit] Tests run: 1, Failures: 0, Errors: 0, Time elapsed: 16,626 sec
    [junit] Running kieker.test.monitoring.junit.core.configuration.TestConfigurationFactoryMethods
    [junit] Tests run: 5, Failures: 0, Errors: 0, Time elapsed: 0,026 sec
    [junit] Running kieker.test.monitoring.junit.writer.namedRecordPipe.TestPipeWriter
    [junit] Tests run: 1, Failures: 0, Errors: 0, Time elapsed: 0,006 sec
    [junit] Running kieker.test.tools.junit.ToolsTest
    [junit] Tests run: 23, Failures: 0, Errors: 15, Time elapsed: 0,073 sec
    [junit] TEST kieker.test.tools.junit.ToolsTest FAILED
    [junit] Running kieker.test.tools.junit.currentTimeEventGeneratorFilter.TestCurrentTimeEventGenerator
    [junit] Tests run: 6, Failures: 0, Errors: 6, Time elapsed: 0,007 sec
    [junit] TEST kieker.test.tools.junit.currentTimeEventGeneratorFilter.TestCurrentTimeEventGenerator FAILED
    [junit] Running kieker.test.tools.junit.traceAnalysis.plugins.TestTimestampFilter
    [junit] Tests run: 4, Failures: 0, Errors: 4, Time elapsed: 0,006 sec
    [junit] TEST kieker.test.tools.junit.traceAnalysis.plugins.TestTimestampFilter FAILED
    [junit] Running kieker.test.tools.junit.traceAnalysis.plugins.TestTraceEquivalenceFilterAssemblyEquivalence
    [junit] Tests run: 1, Failures: 0, Errors: 1, Time elapsed: 0,069 sec
    [junit] TEST kieker.test.tools.junit.traceAnalysis.plugins.TestTraceEquivalenceFilterAssemblyEquivalence FAILED
    [junit] Running kieker.test.tools.junit.traceAnalysis.plugins.TestTraceIdFilter
    [junit] Tests run: 2, Failures: 0, Errors: 2, Time elapsed: 0,004 sec
    [junit] TEST kieker.test.tools.junit.traceAnalysis.plugins.TestTraceIdFilter FAILED
    [junit] Running kieker.test.tools.junit.traceAnalysis.plugins.TestTraceReconstructionFilter
    [junit] Tests run: 3, Failures: 0, Errors: 3, Time elapsed: 0,006 sec
    [junit] TEST kieker.test.tools.junit.traceAnalysis.plugins.TestTraceReconstructionFilter FAILED
    [junit] Running kieker.test.tools.junit.traceAnalysis.systemModel.TestExecutionTraceBookstore
    [junit] Tests run: 8, Failures: 0, Errors: 0, Time elapsed: 0,01 sec
    [junit] 08:06:18,083 WARN  Transformer$1.run(118) - Starting accumulation : Thu Jan 19 08:06:18 CET 2012
    [junit] 08:06:25,332 WARN  Transformer$1.run(122) - Accumlulator : 7240
    [junit] 08:06:25,342 WARN  Transformer$1.run(126) - Cleaner : 9
    [junit] 08:06:25,608 WARN  Transformer$1.run(130) - Aggregator : 266
    [junit] 08:06:27,322 WARN  Transformer$1.run(134) - Close database : 1713
    [junit] 08:06:27,322 WARN  Transformer$1.run(139) - Finished accumulation : Thu Jan 19 08:06:27 CET 2012, duration : 9239 millis
    [junit] 08:06:27,323 WARN  Transformer$1.run(140) - Total memory : 148, max memory : 954, free memory : 78
    [junit] Tests FAILED

-test.junit.report:
[junitreport] Processing /home/voorn/git_work/kieker/tmp/junit-results/TESTS-TestSuites.xml to /tmp/null1373811620
[junitreport] Loading stylesheet jar:file:/usr/share/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 1304ms
[junitreport] Deleting: /tmp/null1373811620
     [echo] To see the test report, open tmp/junit-results//index.html in your Web browser.

BUILD SUCCESSFUL
Total time: 40 seconds
</pre>
</div></div>

[KIEKER-366]: https://kieker-monitoring.atlassian.net/browse/KIEKER-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Thu, 19 Jan 2012 08:14:01 +0100
<p>Forget to mention: This concerns the Kieker version in the <tt>1.5-analysis</tt> branch&#33;</p>

**Comment by rju** [comment]
author André van Hoorn -- Thu, 19 Jan 2012 09:57:39 +0100
<p>The tests run successfully in Eclipse ...</p>

**Comment by rju** [comment]
author Jan Waller -- Thu, 19 Jan 2012 13:01:10 +0100
<p>The problem seems to be <tt>fork="true"</tt> in JUnit.</p>

<p>Without this paramater everything works.</p>

<p>Fixed in 1.5-analysis a4135c1</p>
