### ISSUE TITLE
[KIEKER-323] SigarException: Sigar native libs in java.library.path

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1536]
JIRA Issue: [KIEKER-323] SigarException: Sigar native libs in java.library.path
Original Reporter: Andre van Hoorn
 *** 
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>voornpc-vanhoorn:0:~/tmp/kieker-1.4-RC2/examples/userguide/appendix-Sigar $ ant run-monitoring 
Buildfile: build.xml

-check-files:

clean.monitoring:
   [delete] Deleting: /tmp/kieker-1.4-RC2/examples/userguide/appendix-Sigar/SigarMonitoring.jar

-init:
    [mkdir] Created dir: /tmp/kieker-1.4-RC2/examples/userguide/appendix-Sigar/build

-compile:
    [javac] Compiling 2 source files to /tmp/kieker-1.4-RC2/examples/userguide/appendix-Sigar/build
    [mkdir] Created dir: /tmp/kieker-1.4-RC2/examples/userguide/appendix-Sigar/build/META-INF

-build-jar-monitoring:
      [jar] Building jar: /tmp/kieker-1.4-RC2/examples/userguide/appendix-Sigar/SigarMonitoring.jar
   [delete] Deleting directory /tmp/kieker-1.4-RC2/examples/userguide/appendix-Sigar/build

run-monitoring:
     [java] Monitoring CPU and Mem/Swap for 30 seconds in 5 seconds steps () with an offset of two seconds
     [java] 13.10.2011 16:15:48 kieker.monitoring.core.configuration.Configuration createSingletonConfiguration
     [java] INFO: Loading properties from properties file in classpath: 'META-INF/kieker.monitoring.properties'
     [java] 13.10.2011 16:15:48 kieker.monitoring.core.configuration.Configuration loadConfigurationFromResource
     [java] WARNUNG: File 'META-INF/kieker.monitoring.properties' not found in classpath
     [java] 13.10.2011 16:15:48 kieker.monitoring.core.controller.MonitoringController createInstance
     [java] INFO: Current State of kieker.monitoring (1.4-RC2-20111013) Status: 'enabled'
     [java]     Name: 'KIEKER-SINGLETON'; Hostname: 'pc-vanhoorn'; experimentID: '1'
     [java] JMXController: JMX disabled
     [java] WriterController:
     [java]     Number of Inserts: '0'
     [java]     Automatic assignment of logging timestamps: 'true'
     [java] Writer: 'kieker.monitoring.writer.filesystem.AsyncFsWriter'
     [java]     Configuration:
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.QueueFullBehavior='0'
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.flush='true'
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.QueueSize='10000'
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.customStoragePath='.'
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.MaxShutdownDelay='-1'
     [java]             kieker.monitoring.writer.filesystem.AsyncFsWriter.storeInJavaIoTmpdir='true'
     [java]     Records lost: 0
     [java]     Writer Threads (1): 
     [java]             Finished: 'false'; Writing to Directory: '/tmp/kieker-20111013-141548251-UTC-pc-vanhoorn-KIEKER-SINGLETON'
     [java] Sampling Controller: Periodic Sensor available: Current Poolsize: '0'; Scheduled Tasks: '0'
     [java] 
     [java] no libsigar-x86-linux.so in java.library.path
     [java] org.hyperic.sigar.SigarException: no libsigar-x86-linux.so in java.library.path
     [java]     at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
     [java]     at org.hyperic.sigar.Sigar.&lt;clinit&gt;(Sigar.java:100)
     [java]     at kieker.monitoring.probe.sigar.SigarSamplerFactory.&lt;init&gt;(SigarSamplerFactory.java:48)
     [java]     at kieker.monitoring.probe.sigar.SigarSamplerFactory.&lt;init&gt;(SigarSamplerFactory.java:36)
     [java]     at kieker.monitoring.probe.sigar.SigarSamplerFactory$LazyHolder.&lt;clinit&gt;(SigarSamplerFactory.java:95)
     [java]     at kieker.monitoring.probe.sigar.SigarSamplerFactory.getInstance(SigarSamplerFactory.java:64)
     [java]     at periodicSigarExample.MonitoringStarter.main(Unknown Source)
^C     [java] 13.10.2011 16:15:52 kieker.monitoring.core.controller.MonitoringController$1 run
voornpc-vanhoorn:130:~/tmp/kieker-1.4-RC2/examples/userguide/appendix-Sigar $ cd lib/
</pre>
</div></div>

[KIEKER-323]: https://kieker-monitoring.atlassian.net/browse/KIEKER-323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Thu, 13 Oct 2011 16:47:28 +0200
<p>In this setting, symbolic links to <em>libsigar-x86-linux.so</em> and <em>sigar-1.6.4.jar</em> where created in the example's <em>lib/</em> directory (pointing to <em>lib/libsigar-x86-linux.so</em> and <em>lib/sigar-native-libs/libsigar-x86-linux.so</em> in Kieker's binary release archive). The problem seems to be the resolution of the symbolic link, where both files are not in the same directory. </p>

<p>Work arounds:<br/>
1. Physically copy the files<br/>
1. OR: Add the file system location of <em>libsigar-x86-linux.so</em> to the <em>LD_LIBRARY_PATH</em></p>
