### ISSUE TITLE
[KIEKER-321] Kieker configuration files used in tests not included in source release archives

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1539]
JIRA Issue: [KIEKER-321] Kieker configuration files used in tests not included in source release archives
Original Reporter: Andre van Hoorn
 *** 
<p>This causes the following JUnit test cases to fail:</p>

<ul>
	<li>kieker.test.monitoring.junit.core.configuration.TestConfigurationFactoryMethods.testCreationSingletonConfigurationVariants</li>
	<li>kieker.test.monitoring.junit.core.configuration.TestConfigurationFactoryMethods.testCreationfromFile</li>
</ul>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>testCreationSingletonConfigurationVariants	Failure	expected:&lt;KIEKER-[TEST]&gt; but was:&lt;KIEKER-[SINGLETON]&gt;

junit.framework.ComparisonFailure: expected: but was:
at kieker.test.monitoring.junit.core.configuration.TestConfigurationFactoryMethods.testCreationSingletonConfigurationVariants(Unknown Source)
	0.006

testCreationfromFile	Failure	expected:&lt;KIEKER[-TEST]&gt; but was:&lt;KIEKER[]&gt;

junit.framework.ComparisonFailure: expected: but was:
at kieker.test.monitoring.junit.core.configuration.TestConfigurationFactoryMethods.testCreationfromFile(Unknown Source)
	0.001
</pre>
</div></div>

[KIEKER-321]: https://kieker-monitoring.atlassian.net/browse/KIEKER-321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Thu, 13 Oct 2011 14:59:18 +0200
<p>Fixed in r2171/kieker:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>oornpc-vanhoorn:0:~/svn_work/kieker/software/kieker/branches/1.4-RC $ tar -tzf dist/release/kieker-1.4-RC2_sources.tar.gz | grep test/monitoring/META-INF/
kieker-1.4-RC2/test/monitoring/META-INF/kieker.monitoring.properties.test
</pre>
</div></div>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>voornpc-vanhoorn:0:~/svn_work/kieker/software/kieker/branches/1.4-RC $ unzip -l dist/release/kieker-1.4-RC2_sources.zip | grep test/monitoring/META-INF/ | awk '{ print $4 }'
kieker-1.4-RC2/test/monitoring/META-INF/
kieker-1.4-RC2/test/monitoring/META-INF/kieker.monitoring.properties.test
</pre>
</div></div>
