### ISSUE TITLE
[KIEKER-31] JMS writer fails to connect to JNDI provider

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1812]
JIRA Issue: [KIEKER-31] JMS writer fails to connect to JNDI provider
Original Reporter: Andre van Hoorn
 *** 
<p>Running the monitoring component of the userguide example <em>appendix-JMS</em>, the JMS writer reports the following error.</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>    [java] 88   INFO  [main] kieker.monitoring.writer.jms.JMSWriterThread     - org.exolab.jms.jndi.InitialContextFactory
     [java] 90   ERROR [main] kieker.monitoring.writer.jms.JMSWriterThread     - NamingException Exception while initializing JMS Writer
     [java] 91   ERROR [main] kieker.monitoring.core.controller.WriterController     - Error initializing writer
     [java] javax.naming.ConfigurationException: Cannot connect to JNDI provider - java.naming.provider.url not set 
     [java]     at org.exolab.jms.jndi.InitialContextFactory.getInitialContext(InitialContextFactory.java:128)
     [java]     at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:667)
     [java]     at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:288)
     [java]     at javax.naming.InitialContext.addToEnvironment(InitialContext.java:515)
     [java]     at kieker.monitoring.writer.jms.JMSWriterThread.&lt;init&gt;(AsyncJMSWriter.java:77)
     [java]     at kieker.monitoring.writer.jms.AsyncJMSWriter.init(AsyncJMSWriter.java:43)
     [java]     at kieker.monitoring.writer.AbstractMonitoringWriter.setController(AbstractMonitoringWriter.java:80)
     [java]     at kieker.monitoring.core.controller.WriterController.init(WriterController.java:38)
     [java]     at kieker.monitoring.core.controller.AbstractController.setMonitoringController(AbstractController.java:22)
     [java]     at kieker.monitoring.core.controller.MonitoringController.createInstance(MonitoringController.java:46)
     [java]     at kieker.monitoring.core.controller.MonitoringController$LazyHolder.&lt;clinit&gt;(MonitoringController.java:244)
     [java]     at kieker.monitoring.core.controller.MonitoringController.getInstance(MonitoringController.java:236)
     [java]     at bookstoreApplication.Bookstore.&lt;clinit&gt;(Unknown Source)
     [java]     at bookstoreApplication.BookstoreStarter.main(Unknown Source)
     [java] 93   INFO  [main] kieker.monitoring.core.controller.WriterController     - Shutting down Writer Controller                                                                          
     [java] 93   INFO  [main] kieker.monitoring.writer.AbstractAsyncWriter     - Writer shutdown complete                                                                                       
     [java] 93   INFO  [main] kieker.monitoring.core.controller.MonitoringController     - Shutting down Monitoring Controller (KIEKER)                                                         
     [java] 93   INFO  [main] kieker.monitoring.core.controller.StateController     - Shutting down State Controller
     [java] 93   INFO  [main] kieker.monitoring.core.controller.TimeSourceController     - Shutting down TimeSource Controller
     [java] 93   INFO  [main] kieker.monitoring.core.controller.SamplingController     - Shutting down Sampling Controller

</pre>
</div></div>

[KIEKER-31]: https://kieker-monitoring.atlassian.net/browse/KIEKER-31?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Fri, 22 Apr 2011 13:05:16 +0200
<p>Fixed in <span class="error">&#91;/changeset/1585/kieker&#93;</span></p>

<p>In the &#33;AsyncJMSWriter, replaced </p>


<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>final Context context = new InitialContext();
context.addToEnvironment(Context.INITIAL_CONTEXT_FACTORY, contextFactoryType);
context.addToEnvironment(Context.PROVIDER_URL, providerUrl);
</pre>
</div></div>

<p>by </p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>final Hashtable&lt;String, String&gt; properties = new Hashtable&lt;String, String&gt;();
properties.put(Context.INITIAL_CONTEXT_FACTORY, contextFactoryType);
properties.put(Context.PROVIDER_URL, providerUrl);
final Context context = new InitialContext(properties);
</pre>
</div></div>
