### ISSUE TITLE
[KIEKER-1922] Update Github Builds

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1917]
JIRA Issue: [KIEKER-1922] Update Github Builds
Original Reporter: David Georg Reichelt
 *** 
<p>Github Action builds should build with all Java LTS versions and the newest non-LTS version. Therefore, Java 17 (and, if already available, 18) should be added.</p>

[KIEKER-1922]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author DaGeRe -- Fri, 13 May 2022 10:51:48 +0200
<p>I created a PR: <a href="https://github.com/kieker-monitoring/kieker/pull/361" title="smart-link" class="external-link" rel="nofollow noreferrer">https://github.com/kieker-monitoring/kieker/pull/361</a> </p>

**Comment by rju** [comment]
author rju -- Fri, 13 May 2022 12:03:25 +0200
<p>The only failing test seems to be:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2022-05-13T09:07:56.2373344Z kieker.monitoring.core.controller.tcp.SingleSocketRecordReaderTest &gt; testOnBufferReceived FAILED
2022-05-13T09:07:56.2374364Z     java.lang.reflect.InaccessibleObjectException: Unable to make java.lang.Object java.nio.ByteBuffer.base() accessible: module java.base does not "opens java.nio" to unnamed module 470e2030
2022-05-13T09:07:56.2375726Z         at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
2022-05-13T09:07:56.2394127Z         at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
2022-05-13T09:07:56.2395032Z         at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
2022-05-13T09:07:56.2396040Z         at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
2022-05-13T09:07:56.2397213Z         at org.powermock.reflect.internal.WhiteboxImpl.doGetAllMethods(WhiteboxImpl.java:1508)
2022-05-13T09:07:56.2397968Z         at org.powermock.reflect.internal.WhiteboxImpl.getAllMethods(WhiteboxImpl.java:1482)
2022-05-13T09:07:56.2398901Z         at org.powermock.reflect.internal.WhiteboxImpl.getMethods(WhiteboxImpl.java:1750)
2022-05-13T09:07:56.2399844Z         at org.powermock.reflect.internal.WhiteboxImpl.getMethods(WhiteboxImpl.java:1789)
2022-05-13T09:07:56.2400722Z         at org.powermock.reflect.internal.WhiteboxImpl.getBestMethodCandidate(WhiteboxImpl.java:1008)
2022-05-13T09:07:56.2401440Z         at org.powermock.core.MockInvocation.findMethodToInvoke(MockInvocation.java:58)
2022-05-13T09:07:56.2402045Z         at org.powermock.core.MockInvocation.init(MockInvocation.java:35)
2022-05-13T09:07:56.2402614Z         at org.powermock.core.MockInvocation.&lt;init&gt;(MockInvocation.java:22)
2022-05-13T09:07:56.2403309Z         at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:155)
2022-05-13T09:07:56.2403975Z         at org.powermock.core.MockGateway.methodCall(MockGateway.java:138)
2022-05-13T09:07:56.2404818Z         at kieker.monitoring.core.controller.tcp.SingleSocketRecordReaderTest.testOnBufferReceived(SingleSocketRecordReaderTest.java:69)</pre>
</div></div>

**Comment by rju** [comment]
author rju -- Fri, 13 May 2022 12:11:15 +0200
<p>It could be a powermock problem. Here is some insight in it <a href="https://stackoverflow.com/questions/69896191/powermock-compatibility-with-jdk-17" title="smart-link" class="external-link" rel="nofollow noreferrer">https://stackoverflow.com/questions/69896191/powermock-compatibility-with-jdk-17</a> </p>

<p>Maybe we should remove Powermock tests? </p>

**Comment by rju** [comment]
author rju -- Fri, 20 May 2022 09:16:39 +0200
<p>Check if they can be ported to mockito.</p>

**Comment by rju** [comment]
author rju -- Sun, 29 May 2022 15:28:38 +0200
<p>There were only a few Powermock tests. I removed powermock. Some tests work regardless of powermock. Some were obsolete and testing deprecated TeeTime code. So I removed it.</p>
