### ISSUE TITLE
[KIEKER-1890] kieker.monitoring.probe.aspectj.operation.ExecutionAbstractOperationExecutionAspect fails if static methods are instrumented

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1949]
JIRA Issue: [KIEKER-1890] kieker.monitoring.probe.aspectj.operation.ExecutionAbstractOperationExecutionAspect fails if static methods are instrumented
Original Reporter: David Georg Reichelt
 *** 
<p>For cases where a static method is instrumented, the current implementation of AbstractOperationExecution aspect fails since the static method is recorded on method end but not on method start. I stumbled over this in a Peass test<br/>
{{2021-07-22T10:19:19.9332786Z Exception in thread "main" java.util.EmptyStackException<br/>
2021-07-22T10:19:19.9333548Z 	at java.util.Stack.peek(Stack.java:102)<br/>
2021-07-22T10:19:19.9334170Z 	at java.util.Stack.pop(Stack.java:84)<br/>
2021-07-22T10:19:19.9337087Z 	at kieker.monitoring.probe.aspectj.operationExecution.AbstractOperationExecutionAspect.afterOperation(AbstractOperationExecutionAspect.java:117)<br/>
2021-07-22T10:19:19.9340293Z 	at de.peass.example.CallerLongFor.main(CallerLongFor.java:22)}}<br/>
(<a href="https://pipelines.actions.githubusercontent.com/IdogOhCgAyWsD98Fg3Lp1e2agKgDPOjyskGkRz6KSOzPR4VvhB/_apis/pipelines/1/runs/884/signedlogcontent/3?urlExpires=2021-07-22T10%3A25%3A21.5824957Z&amp;urlSigningMethod=HMACV1&amp;urlSignature=9osre6PWPxeijkax%2Bcc4nkRmu%2BKSvIjKWDujpqLmtsQ%3D)," class="external-link" rel="nofollow noreferrer">https://pipelines.actions.githubusercontent.com/IdogOhCgAyWsD98Fg3Lp1e2agKgDPOjyskGkRz6KSOzPR4VvhB/_apis/pipelines/1/runs/884/signedlogcontent/3?urlExpires=2021-07-22T10%3A25%3A21.5824957Z&amp;urlSigningMethod=HMACV1&amp;urlSignature=9osre6PWPxeijkax%2Bcc4nkRmu%2BKSvIjKWDujpqLmtsQ%3D),</a> but this is currently not covered by Kiekers own integration tests. <tt>this(thisObject)</tt> is not required in the aspect and removing it should solve the problem.</p>

<p>Nevertheless, I'll extend the tests and fix this today.</p>

[KIEKER-1890]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Fri, 8 Oct 2021 14:54:25 +0200
<p>Moved to 1.16. <a href="https://kieker-monitoring.atlassian.net/secure/ViewProfile.jspa?accountId=557058%3A62e50ed6-5f61-4540-a49c-a43b84d72ea5" class="user-hover" rel="557058:62e50ed6-5f61-4540-a49c-a43b84d72ea5" data-account-id="557058:62e50ed6-5f61-4540-a49c-a43b84d72ea5" accountid="557058:62e50ed6-5f61-4540-a49c-a43b84d72ea5" rel="noreferrer">David Georg Reichelt</a> what is the status? There seems to be an attached merge. </p>

**Comment by rju** [comment]
author DaGeRe -- Fri, 8 Oct 2021 15:28:42 +0200
<p>From my point of view, this should be done after the merge of <a href="https://github.com/kieker-monitoring/kieker/pull/319" title="smart-link" class="external-link" rel="nofollow noreferrer">https://github.com/kieker-monitoring/kieker/pull/319</a> </p>

**Comment by rju** [comment]
author DaGeRe -- Fri, 8 Oct 2021 15:28:58 +0200
<p>This is done after the merge <a href="https://github.com/kieker-monitoring/kieker/pull/319" class="external-link" rel="nofollow noreferrer">https://github.com/kieker-monitoring/kieker/pull/319</a></p>
