### ISSUE TITLE
[KIEKER-1875] Default Writer Requires Additional Dependency

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1964]
JIRA Issue: [KIEKER-1875] Default Writer Requires Additional Dependency
Original Reporter: David Georg Reichelt
 *** 
<p>When starting a kieker instrumented application with the javaagent like -javaagent:~/.m2/repository/net/kieker-monitoring/kieker/1.15-SNAPSHOT/kieker-1.15-SNAPSHOT-aspectj.jar (or with source instrumentation), many projects get exceptions like this:</p>

<p>{{Exception in thread "main" java.lang.ExceptionInInitializerError<br/>
	at kieker.monitoring.core.controller.MonitoringController.getInstance(MonitoringController.java:404)<br/>
	at kieker.monitoring.probe.aspectj.flow.operationExecution.AbstractAspect.&lt;clinit&gt;(AbstractAspect.java:42)<br/>
	at org.openjdk.jmh.runner.ForkedMain.main(ForkedMain.java:55)<br/>
Caused by: java.lang.IllegalStateException: java.lang.ClassNotFoundException: org.jctools.queues.MpscArrayQueue<br/>
	at kieker.monitoring.core.controller.WriterController.newQueue(WriterController.java:247)<br/>
	at kieker.monitoring.core.controller.WriterController.&lt;init&gt;(WriterController.java:110)<br/>
	at kieker.monitoring.core.controller.MonitoringController.&lt;init&gt;(MonitoringController.java:72)<br/>
	at kieker.monitoring.core.controller.MonitoringController.createInstance(MonitoringController.java:92)<br/>
	at kieker.monitoring.core.controller.MonitoringController$SingletonHelper.&lt;clinit&gt;(MonitoringController.java:412)<br/>
	... 3 more<br/>
Caused by: java.lang.ClassNotFoundException: org.jctools.queues.MpscArrayQueue<br/>
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)<br/>
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)<br/>
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)<br/>
	at java.base/java.lang.Class.forName0(Native Method)<br/>
	at java.base/java.lang.Class.forName(Class.java:315)<br/>
	at kieker.monitoring.core.controller.WriterController.newQueue(WriterController.java:238)<br/>
	... 7 more}}</p>

<p>To overcome this, one needs to add the jctools dependency:</p>

<p>{{       &lt;dependency&gt;<br/>
            &lt;groupId&gt;org.jctools&lt;/groupId&gt;<br/>
            &lt;artifactId&gt;jctools-core&lt;/artifactId&gt;<br/>
            &lt;version&gt;3.3.0&lt;/version&gt;<br/>
        &lt;/dependency&gt;}}</p>

<p>to the project or change the RecordQueueFQN e.g. by<br/>
<tt>-Dkieker.monitoring.core.controller.WriterController.RecordQueueFQN=java.util.concurrent.ArrayBlockingQueue</tt></p>

<p>I would recommend to either add the required class to the jar or to change the default queue implementation to <tt>java.util.concurrent.ArrayBlockingQueue</tt> by editing kieker.monitoring.default.properties. </p>

**Comment by rju** [comment]
author rju -- Thu, 20 May 2021 08:56:49 +0200
<p>Check why jctools must be included.</p>

**Comment by rju** [comment]
author rju -- Wed, 9 Jun 2021 00:51:47 +0200
<p>Added jctools to the artifacts.</p>
