### ISSUE TITLE
[KIEKER-1824] Broken example: probe-spring

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2015]
JIRA Issue: [KIEKER-1824] Broken example: probe-spring
Original Reporter: Andre van Hoorn
 *** 

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>avhAndrè van Hoorn-ThinkPad-T450s:~/Downloads/Kieker-release/kieker-1.14-bin/examples/monitoring/probe-spring $ ./gradlew runMonitoring

&gt; Task :runMonitoring
May 07, 2020 4:07:31 PM org.springframework.context.support.ClassPathXmlApplicationContext prepareRefresh
INFO: Refreshing org.springframework.context.support.ClassPathXmlApplicationContext77a567e1: startup date [Thu May 07 16:07:31 CEST 2020]; root of context hierarchy
May 07, 2020 4:07:31 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from class path resource [config/spring-config.xml]
Exception in thread "main" org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [/home/avh/Downloads/Kieker-release/kieker-1.14-bin/examples/monitoring/probe-spring/build/classes/java/main/kieker/examples/monitoring/spring/Catalog.class]; nested exception is org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: file [/home/avh/Downloads/Kieker-release/kieker-1.14-bin/examples/monitoring/probe-spring/build/classes/java/main/kieker/examples/monitoring/spring/Catalog.class]; nested exception is java.lang.IllegalArgumentException
        at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:290)
        at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:242)
        at org.springframework.context.annotation.ComponentScanBeanDefinitionParser.parse(ComponentScanBeanDefinitionParser.java:84)
        at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:73)
        at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1438)
        at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1428)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:195)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:139)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:108)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:493)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:390)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:334)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:209)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:243)
        at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:127)
        at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:93)
        at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130)
        at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:537)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:451)
        at org.springframework.context.support.ClassPathXmlApplicationContext.&lt;init&gt;(ClassPathXmlApplicationContext.java:139)
        at org.springframework.context.support.ClassPathXmlApplicationContext.&lt;init&gt;(ClassPathXmlApplicationContext.java:83)
        at kieker.examples.monitoring.spring.BookstoreStarter.main(BookstoreStarter.java:30)
Caused by: org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: file [/home/avh/Downloads/Kieker-release/kieker-1.14-bin/examples/monitoring/probe-spring/build/classes/java/main/kieker/examples/monitoring/spring/Catalog.class]; nested exception is java.lang.IllegalArgumentException
        at org.springframework.core.type.classreading.SimpleMetadataReader.&lt;init&gt;(SimpleMetadataReader.java:56)
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:80)
        at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:102)
        at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:266)
        ... 24 more
Caused by: java.lang.IllegalArgumentException
        at org.springframework.asm.ClassReader.&lt;init&gt;(Unknown Source)
        at org.springframework.asm.ClassReader.&lt;init&gt;(Unknown Source)
        at org.springframework.asm.ClassReader.&lt;init&gt;(Unknown Source)
        at org.springframework.core.type.classreading.SimpleMetadataReader.&lt;init&gt;(SimpleMetadataReader.java:53)
        ... 27 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runMonitoring'.
&gt; Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 2s
3 actionable tasks: 3 executed

</pre>
</div></div>

[KIEKER-1824]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author rju -- Fri, 8 May 2020 09:16:28 +0200
<p>I have the impression that this is a Java versions issue. The example is on Spring 3.2.8. The current Spring version ist 5.2.6. <br/>
Also 3.2.9 might work with Java 8, but this is debatable. At least version 4 would be required (see <a href="https://stackoverflow.com/questions/30072135/spring-3-2-x-with-java-8" class="external-link" rel="nofollow noreferrer">https://stackoverflow.com/questions/30072135/spring-3-2-x-with-java-8</a>).</p>

<p>Thus, we should let this be as is 1.14 and push all versions to present day versions in 1.15.</p>

**Comment by rju** [comment]
author avanhoorn -- Thu, 6 May 2021 09:35:14 +0200
<p>Double-check.</p>

**Comment by rju** [comment]
author rju -- Wed, 9 Jun 2021 11:28:47 +0200
<p><em>Updated this example. It runs in branch 1824.</em> </p>
