### ISSUE TITLE
[KIEKER-1823] User guide example: JPetStore example not working

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2016]
JIRA Issue: [KIEKER-1823] User guide example: JPetStore example not working
Original Reporter: Andre van Hoorn
 *** 
<p>The application already starts with a couple of exceptions, including some related to Oshi. </p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>avhAndrè van Hoorn-ThinkPad-T450s:~/Downloads/kieker-release/kieker-1.14/examples/JavaEEServletContainerExample/jetty $ java -jar start.jar

... 
Caused by: 
java.lang.ClassNotFoundException: oshi.SystemInfo
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:430)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:383)
	at kieker.monitoring.sampler.oshi.OshiSamplerFactory.&lt;init&gt;(OshiSamplerFactory.java:51)
	at kieker.monitoring.sampler.oshi.OshiSamplerFactory.&lt;clinit&gt;(OshiSamplerFactory.java:39)
	at kieker.monitoring.probe.servlet.SystemResourceUsageServletContextListener
...
</pre>
</div></div>

<p>When opening </p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>http://localhost:8080/jpetstore/
</pre>
</div></div>

<p>The following error is displayed: </p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>Not Found ERROR
custom 404 page 
</pre>
</div></div>

[KIEKER-1823]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Sat, 9 May 2020 20:46:57 +0200
<p>Apart from the Oshi-related issue, it looks like an update to a later issue Jetty version helps. Updated the version. Fixes in progress. </p>

**Comment by rju** [comment]
author André van Hoorn -- Mon, 11 May 2020 15:40:28 +0200
<p>The upgrade of the Jetty version lets test fail that used the old Jetty version: <a href="https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-monitoring/job/kieker/job/1.14-RC/47/" class="external-link" rel="nofollow noreferrer">https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-monitoring/job/kieker/job/1.14-RC/47/</a></p>

<p>I am trying to fix it and this is the status: </p>

<ul>
	<li>I created a variant of TestSpringMethodInterceptor that at least starts Jetty but then fails with a “java.lang.NoSuchMethodError: javax.servlet.ServletContext.createListener“:
	<ul>
		<li><div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>avhAndrè van Hoorn-ThinkPad-T450s:~/git_work/kieker (1.14-RC)*$ diff ./kieker-monitoring/test/kieker/test/monitoring/junit/probe/spring/executions/jetty/TestSpringMethodInterceptor2.java ./kieker-monitoring/test/kieker/test/monitoring/junit/probe/spring/executions/jetty/TestSpringMethodInterceptor.java
24,27d23
&lt; import org.eclipse.jetty.server.Handler;
&lt; import org.eclipse.jetty.server.Server;
&lt; import org.eclipse.jetty.webapp.WebAppContext;
&lt; //import org.eclipse.jetty.webapp.WebAppContext;
33a30
&gt; import org.springframework.context.support.FileSystemXmlApplicationContext;
52c49
&lt; public class TestSpringMethodInterceptor2 extends AbstractKiekerTest {
---
&gt; public class TestSpringMethodInterceptor extends AbstractKiekerTest {
58a56
&gt; 	private FileSystemXmlApplicationContext ctx;
61,62d58
&lt; 	private Server server = null;
&lt; 	
71c67
&lt; 	public TestSpringMethodInterceptor2() {
---
&gt; 	public TestSpringMethodInterceptor() {
76c72
&lt; 	public void startServer() {
---
&gt; 	public void startServer() throws IOException {
91,99c87,90
&lt; 		this.server = new Server();
&lt; 		Handler webAppHandler = new WebAppContext("test/kieker/test/monitoring/junit/probe/spring/executions/jetty/webapp/", "/bookstore");
&lt; 		server.setHandler(webAppHandler);
&lt; 		try {
&lt; 			server.start();
&lt; 			server.join();
&lt; 		} catch (Exception e) {
&lt; 			Assert.fail("Failed to start Jetty server");
&lt; 		}
---
&gt; 		// start the server
&gt; 		final URL configURL = TestSpringMethodInterceptor.class
&gt; 				.getResource("/kieker/test/monitoring/junit/probe/spring/executions/jetty/jetty.xml");
&gt; 		this.ctx = new FileSystemXmlApplicationContext(configURL.toExternalForm());
115a107
&gt; 		Assert.assertThat(this.ctx.isRunning(), CoreMatchers.is(true));
168a161
&gt; 		this.ctx.destroy();
173,177d165
&lt; 		try {
&lt; 			server.stop();
&lt; 		} catch (Exception e) {
&lt; 			Assert.fail("Failed to stop Jetty server");
&lt; 		}
</pre>
</div></div></li>
		<li>We seem to have an issue with an outdated servlet version flying around in the classpath (is 2.5 and should be 3.0.1+):
		<ul>
			<li><span class="image-wrap" style=""><img src="/rest/api/3/attachment/content/11214" height="150" width="321" style="border: 0px solid black" /></span></li>
			<li><span class="image-wrap" style=""><img src="/rest/api/3/attachment/content/11215" height="28" width="731" style="border: 0px solid black" /></span></li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p><a href="https://kieker-monitoring.atlassian.net/secure/ViewProfile.jspa?accountId=557058%3Ab81a6b7f-b4c8-4105-83ac-47b039a57a19" class="user-hover" rel="557058:b81a6b7f-b4c8-4105-83ac-47b039a57a19" data-account-id="557058:b81a6b7f-b4c8-4105-83ac-47b039a57a19" accountid="557058:b81a6b7f-b4c8-4105-83ac-47b039a57a19" rel="noreferrer">Reiner Jung</a> Any idea how we find out which dependency is causing <em>servlet-api-2.5</em> to be included? </p>

**Comment by rju** [comment]
author André van Hoorn -- Mon, 11 May 2020 16:49:11 +0200
<p>It looks like the Spring Interceptor test was broken/inactive already before: <a href="https://kieker-monitoring.atlassian.net/browse/KIEKER-1515" title="smart-link" class="external-link" rel="nofollow noreferrer">https://kieker-monitoring.atlassian.net/browse/KIEKER-1515</a> </p>

**Comment by rju** [comment]
author rju -- Mon, 11 May 2020 16:50:47 +0200
<p>When I check the dependencies with <tt>/gradlew -q dependencies --configuration compile</tt>, I get the following result:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
compile - Dependencies <span class="code-keyword">for</span> source set <span class="code-quote">'main'</span> (deprecated, use <span class="code-quote">'implementation '</span> instead).
+--- ch.qos.logback:logback-classic:1.1.7
|    +--- ch.qos.logback:logback-core:1.1.7
|    \--- org.slf4j:slf4j-api:1.7.20 -&gt; 1.7.30
+--- org.slf4j:slf4j-api:1.7.30
\--- org.codehaus.groovy:groovy-all:3.0.2
     +--- org.codehaus.groovy:groovy:3.0.2
     +--- org.codehaus.groovy:groovy-ant:3.0.2
     |    +--- org.codehaus.groovy:groovy:3.0.2
     |    +--- org.apache.ant:ant:1.10.7
     |    |    \--- org.apache.ant:ant-launcher:1.10.7
     |    +--- org.apache.ant:ant-junit:1.10.7
     |    |    \--- org.apache.ant:ant:1.10.7 (*)
     |    +--- org.apache.ant:ant-launcher:1.10.7
     |    +--- org.apache.ant:ant-antlr:1.10.7
     |    \--- org.codehaus.groovy:groovy-groovydoc:3.0.2
     |         +--- org.codehaus.groovy:groovy:3.0.2
     |         +--- com.github.javaparser:javaparser-core:3.15.13
     |         +--- org.codehaus.groovy:groovy-templates:3.0.2
     |         |    +--- org.codehaus.groovy:groovy:3.0.2
     |         |    \--- org.codehaus.groovy:groovy-xml:3.0.2
     |         |         \--- org.codehaus.groovy:groovy:3.0.2
     |         \--- org.codehaus.groovy:groovy-docgenerator:3.0.2
     |              +--- org.codehaus.groovy:groovy-templates:3.0.2 (*)
     |              +--- org.codehaus.groovy:groovy:3.0.2
     |              \--- com.thoughtworks.qdox:qdox:1.12.1
     +--- org.codehaus.groovy:groovy-astbuilder:3.0.2
     |    \--- org.codehaus.groovy:groovy:3.0.2
     +--- org.codehaus.groovy:groovy-cli-picocli:3.0.2
     |    +--- org.codehaus.groovy:groovy:3.0.2
     |    \--- info.picocli:picocli:4.1.4
     +--- org.codehaus.groovy:groovy-console:3.0.2
     |    +--- org.codehaus.groovy:groovy:3.0.2
     |    +--- org.codehaus.groovy:groovy-templates:3.0.2 (*)
     |    \--- org.codehaus.groovy:groovy-swing:3.0.2
     |         \--- org.codehaus.groovy:groovy:3.0.2
     +--- org.codehaus.groovy:groovy-datetime:3.0.2
     |    \--- org.codehaus.groovy:groovy:3.0.2
     +--- org.codehaus.groovy:groovy-docgenerator:3.0.2 (*)
     +--- org.codehaus.groovy:groovy-groovydoc:3.0.2 (*)
     +--- org.codehaus.groovy:groovy-groovysh:3.0.2
     |    +--- org.codehaus.groovy:groovy-templates:3.0.2 (*)
     |    +--- org.codehaus.groovy:groovy:3.0.2
     |    +--- org.codehaus.groovy:groovy-console:3.0.2 (*)
     |    +--- org.codehaus.groovy:groovy-xml:3.0.2 (*)
     |    \--- jline:jline:2.14.6
     +--- org.codehaus.groovy:groovy-jmx:3.0.2
     |    \--- org.codehaus.groovy:groovy:3.0.2
     +--- org.codehaus.groovy:groovy-json:3.0.2
     |    \--- org.codehaus.groovy:groovy:3.0.2
     +--- org.codehaus.groovy:groovy-jsr223:3.0.2
     |    \--- org.codehaus.groovy:groovy:3.0.2
     +--- org.codehaus.groovy:groovy-macro:3.0.2
     |    \--- org.codehaus.groovy:groovy:3.0.2
     +--- org.codehaus.groovy:groovy-nio:3.0.2
     |    \--- org.codehaus.groovy:groovy:3.0.2
     +--- org.codehaus.groovy:groovy-servlet:3.0.2
     |    +--- org.codehaus.groovy:groovy:3.0.2
     |    +--- org.codehaus.groovy:groovy-templates:3.0.2 (*)
     |    \--- org.codehaus.groovy:groovy-xml:3.0.2 (*)
     +--- org.codehaus.groovy:groovy-sql:3.0.2
     |    \--- org.codehaus.groovy:groovy:3.0.2
     +--- org.codehaus.groovy:groovy-swing:3.0.2 (*)
     +--- org.codehaus.groovy:groovy-templates:3.0.2 (*)
     +--- org.codehaus.groovy:groovy-test:3.0.2
     |    +--- org.codehaus.groovy:groovy:3.0.2
     |    \--- junit:junit:4.13
     |         \--- org.hamcrest:hamcrest-core:1.3
     +--- org.codehaus.groovy:groovy-test-junit5:3.0.2
     |    +--- org.codehaus.groovy:groovy:3.0.2
     |    +--- org.junit.platform:junit-platform-launcher:1.6.0
     |    |    \--- org.junit.platform:junit-platform-engine:1.6.0
     |    |         +--- org.opentest4j:opentest4j:1.2.0
     |    |         \--- org.junit.platform:junit-platform-commons:1.6.0
     |    \--- org.junit.jupiter:junit-jupiter-engine:5.6.0
     |         +--- org.junit.platform:junit-platform-engine:1.6.0 (*)
     |         \--- org.junit.jupiter:junit-jupiter-api:5.6.0
     |              +--- org.opentest4j:opentest4j:1.2.0
     |              \--- org.junit.platform:junit-platform-commons:1.6.0
     +--- org.codehaus.groovy:groovy-testng:3.0.2
     |    +--- org.codehaus.groovy:groovy:3.0.2
     |    \--- org.testng:testng:6.14.3
     |         \--- com.beust:jcommander:1.72
     \--- org.codehaus.groovy:groovy-xml:3.0.2 (*)
</pre>
</div></div>

<p>As you can see here, only <tt>rg.codehaus.groovy:groovy-servlet:3.0.2</tt> is listed with servlet in the name.</p>

<p>Jetty itself contains <tt>./jetty/lib/servlet-api-3.1.jar</tt> </p>

<p>I found a reference in <tt>./jetty/lib/org.apache.taglibs.taglibs-standard-spec-1.2.5.jar</tt> <tt>./jetty/lib/apache-jstl/org.apache.taglibs.taglibs-standard-impl-1.2.5.jar</tt><br/>
And an optional reference to 2.3 in apache commons.</p>

<p>Thus, the current jetty setup introduces this dependency.</p>

**Comment by rju** [comment]
author André van Hoorn -- Mon, 11 May 2020 17:28:11 +0200
<p>Ok, thanks for checking. Actually, I have even removed the dependency to the local Jetty libs and used the ones obtained via Gradle/Maven. We definitely need to look at outdated libs in the build.gradle of the monitoring component. </p>

**Comment by rju** [comment]
author rju -- Mon, 11 May 2020 17:57:45 +0200
<p>Definitely. </p>
