### ISSUE TITLE
[KIEKER-1507] NPE while Compiling Trace.irl

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2330]
JIRA Issue: [KIEKER-1507] NPE while Compiling Trace.irl
Original Reporter: Christian Wulf
 *** 

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
java.lang.NullPointerException
	at kieker.develop.rl.typing.TypeResolution.findType(TypeResolution.java:76)
	at kieker.develop.rl.typing.TypeResolution.findType(TypeResolution.java:89)
	at kieker.develop.rl.typing.TypeResolution.findType(TypeResolution.java:86)
	at kieker.develop.rl.generator.java.record.ConstantConstructionModule.lambda$0(ConstantConstructionModule.java:40)
	at org.eclipse.xtext.xbase.lib.internal.BooleanFunctionDelegate.apply(BooleanFunctionDelegate.java:41)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:647)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.base.Joiner.appendTo(Joiner.java:107)
	at com.google.common.base.Joiner.appendTo(Joiner.java:152)
	at com.google.common.base.Joiner.join(Joiner.java:193)
	at com.google.common.base.Joiner.join(Joiner.java:183)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.join(IteratorExtensions.java:414)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.join(IteratorExtensions.java:398)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.join(IterableExtensions.java:360)
	at kieker.develop.rl.generator.java.record.ConstantConstructionModule.createDefaultConstants(ConstantConstructionModule.java:50)
	at kieker.develop.rl.generator.java.record.EventTypeGenerator.createOutputModel(EventTypeGenerator.java:156)
	at kieker.develop.rl.generator.java.record.EventTypeGenerator.createOutputModel(EventTypeGenerator.java:1)
	at kieker.develop.rl.generator.AbstractTypeGenerator.generate(AbstractTypeGenerator.java:50)
	at kieker.develop.rl.generator.AbstractTypeGenerator.generate(AbstractTypeGenerator.java:1)
	at kieker.develop.rl.generator.RecordLangGenerator.lambda$7(RecordLangGenerator.java:188)
	at java.lang.Iterable.forEach(Unknown Source)
	at kieker.develop.rl.generator.RecordLangGenerator.lambda$4(RecordLangGenerator.java:195)
	at java.lang.Iterable.forEach(Unknown Source)
	at kieker.develop.rl.generator.RecordLangGenerator.processTypes(RecordLangGenerator.java:197)
	at kieker.develop.rl.generator.RecordLangGenerator.runGenerators(RecordLangGenerator.java:160)
	at kieker.develop.rl.generator.RecordLangGenerator.doGenerate(RecordLangGenerator.java:73)
	at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:43)
	at org.eclipse.xtext.generator.GeneratorDelegate.generate(GeneratorDelegate.java:34)
	at org.eclipse.xtext.builder.BuilderParticipant.handleChangedContents(BuilderParticipant.java:564)
	at org.eclipse.xtext.builder.BuilderParticipant.handleChangedContents(BuilderParticipant.java:549)
	at org.eclipse.xtext.builder.BuilderParticipant.doGenerate(BuilderParticipant.java:534)
	at org.eclipse.xtext.builder.BuilderParticipant.doBuild(BuilderParticipant.java:280)
	at org.eclipse.xtext.builder.BuilderParticipant.build(BuilderParticipant.java:238)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:161)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:69)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:291)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:267)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:161)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

</pre>
</div></div>

[KIEKER-1507]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author rju -- Tue, 6 Feb 2018 15:17:36 +0100
<p>How can this issue be recreated?</p>

**Comment by rju** [comment]
author Unknown -- Tue, 20 Feb 2018 08:36:00 +0100
<p>I don't know anymore. However, the log shows that this NPE occurs when generating the Trace.irl with the Eclipse Plugin. Moreover, it indicates the source of the exception:<br/>
<tt>kieker.develop.rl.typing.TypeResolution.findType(TypeResolution.java:76)</tt></p>

**Comment by rju** [comment]
author rju -- Tue, 20 Feb 2018 12:26:13 +0100
<p>I cannot reproduce the error on my machine anymore. Most likely, I fixed it. You can test the next update of the IRL tomorrow.</p>

**Comment by rju** [comment]
author rju -- Thu, 10 May 2018 18:32:30 +0200
<p>Seems to be fixed.</p>
