### ISSUE TITLE
[KIEKER-1482] Certificate issues in Docker build containers (OpenJDK 6)

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2355]
JIRA Issue: [KIEKER-1482] Certificate issues in Docker build containers (OpenJDK 6)
Original Reporter: Thomas F. Düllmann
 *** 
<p>Probably due to certificate changes on the gradle website, the certificate store inside the Docker container with Ubuntu 15.04 and OpenJDK6 does not contain the required certificates.<br/>
This leads to issues when the Gradle wrapper script tries to download the gradle distribution file via HTTPS:<br/>
_Downloading <a href="https://services.gradle.org/distributions/gradle-2.2.1-bin.zip" class="external-link" rel="nofollow noreferrer">https://services.gradle.org/distributions/gradle-2.2.1-bin.zip</a></p>

<p>Exception in thread "main" javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br/>
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)<br/>
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1836)<br/>
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:287)<br/>
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:281)<br/>
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1279)<br/>
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:202)<br/>
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:848)<br/>
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:784)<br/>
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1012)<br/>
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1320)<br/>
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1347)<br/>
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1331)<br/>
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:440)<br/>
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)<br/>
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2180)<br/>
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1425)<br/>
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)<br/>
	at org.gradle.wrapper.Download.downloadInternal(Download.java:56)<br/>
	at org.gradle.wrapper.Download.download(Download.java:42)<br/>
	at org.gradle.wrapper.Install$1.call(Install.java:57)<br/>
	at org.gradle.wrapper.Install$1.call(Install.java:44)<br/>
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)<br/>
	at org.gradle.wrapper.Install.createDist(Install.java:44)<br/>
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)<br/>
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)<br/>
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br/>
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:386)<br/>
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:293)<br/>
	at sun.security.validator.Validator.validate(Validator.java:260)<br/>
	at sun.security.validator.Validator.validate(Validator.java:236)<br/>
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:147)<br/>
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:230)<br/>
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:270)<br/>
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1258)<br/>
	... 20 more<br/>
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br/>
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:197)<br/>
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:255)<br/>
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:381)<br/>
	... 27 more_</p>

<p>This issue is reproducible using the Docker container on a local machine.</p>

<p>It is not possible to switch to a newer Ubuntu version as the OpenJDK 6 package is not available there.</p>

<p><a href="https://kieker-monitoring.atlassian.net/secure/ViewProfile.jspa?accountId=christian.wulf" rel="noreferrer">christian.wulf</a><br/>
<a href="https://kieker-monitoring.atlassian.net/secure/ViewProfile.jspa?accountId=557058%3A9e328f65-6e51-4aca-812b-82e63a91a0ae" class="user-hover" rel="557058:9e328f65-6e51-4aca-812b-82e63a91a0ae" data-account-id="557058:9e328f65-6e51-4aca-812b-82e63a91a0ae" accountid="557058:9e328f65-6e51-4aca-812b-82e63a91a0ae" rel="noreferrer">Andre van Hoorn</a></p>

[KIEKER-1482]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Wed, 30 Nov 2016 14:29:36 +0100
<p>Is it possible to update the cert when starting the container?</p>

**Comment by rju** [comment]
author Thomas F. Düllmann -- Wed, 30 Nov 2016 22:20:39 +0100
<p>This issue was solved by changing the build environment from OpenJDK 6 to OpenJDK 7.<br/>
Further changes:</p>
<ul>
	<li>Raised Findbugs warning threshold to 18 (from 10) as the detection classification of the Findbugs version compatible with OpenJDK 7 is higher.</li>
	<li>As javadoc in OpenJDK 7 seems to be more restrictive regarding character sets, special characters in the comments lead to failing builds. These few unmappable characters were removed/replaced.</li>
</ul>


<p>My most recent <ins>guess</ins> is, that the SSL/HTTPS issue might have been caused by more recent security features (e.g., Ciphers) in the newly deployed certificates of the Gradle website. This could explain why downloading dependencies could fail because of Java in the context of encryption.</p>

<p><b><ins>Closing</ins></b> the ticket.</p>

**Comment by rju** [comment]
author André van Hoorn -- Thu, 1 Dec 2016 09:17:14 +0100
<p>Thanks a lot, Thomas! </p>

<p>BTW: Have a look at the nice linking to GitHub commits, merges, pull request in this ticket in the right column in the "development" section.</p>
