### ISSUE TITLE
[KIEKER-1461] Jenkins nightly builds fail occasionally due to failing tests

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2376]
JIRA Issue: [KIEKER-1461] Jenkins nightly builds fail occasionally due to failing tests
Original Reporter: Thomas F. Düllmann
 *** 
<p>There seem to be some tests that fail from time to time. To find out what the actual issue is, I will start collecting such tests here:<br class="atl-forced-newline" />
<br class="atl-forced-newline" /></p>

<ul>
	<li><p><b>kieker.test.tools.junit.writeRead.jmx.BasicJMXWriterReaderTest &gt; testSimpleLog</b> (<a href="https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-nightly-release/2839" class="external-link" rel="nofollow noreferrer">https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-nightly-release/2839</a>)</p>
<blockquote><p>java.lang.AssertionError: Unexpected set of records expected:&lt;[1467166260873651642;0;0;0;public Book bookstore.Bookstore.searchBook(long);bookstore.Bookstore, 1467166260873714804;1;0;1;public Book bookstore.Bookstore.searchBook(long);bookstore.Bookstore;private Book bookstore.Catalog.getBook(long);bookstore.Catalog, 1467166260873727219;2;0;2;private Book bookstore.Catalog.getBook(long);bookstore.Catalog, 1467166260873738879;3;0;3;private Book bookstore.Catalog.getBook(long);bookstore.Catalog, 1467166260873750491;4;0;4;public Book bookstore.Bookstore.searchBook(long);bookstore.Bookstore;private Order[] bookstore.CRM.getOrders(long);bookstore.CRM, 1467166260873762001;6;0;5;private Order[] bookstore.CRM.getOrders(long);bookstore.CRM;private Book bookstore.Catalog.getBook(long);bookstore.Catalog, 1467166260873773301;7;0;6;private Book bookstore.Catalog.getBook(long);bookstore.Catalog, 1467166260873784723;8;0;7;private Book bookstore.Catalog.getBook(long);bookstore.Catalog, 1467166260873796053;11;0;8;public Book bookstore.Bookstore.searchBook(long);bookstore.Bookstore, 1467166260873807605]&gt; but was:&lt;[]&gt;<br/>
        at org.junit.Assert.fail(Assert.java:88)<br/>
        at org.junit.Assert.failNotEquals(Assert.java:743)<br/>
        at org.junit.Assert.assertEquals(Assert.java:118)<br/>
        at kieker.test.tools.junit.writeRead.jmx.BasicJMXWriterReaderTest.inspectRecords(BasicJMXWriterReaderTest.java:138)</p></blockquote></li>
</ul>

<ul>
	<li>Count: 4 <b>kieker.test.monitoring.junit.probe.adaptiveMonitoring.sigar.TestCPUsCombinedPercSampler &gt; testDeactivationAndReactivation</b> (<a href="https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-nightly-release/2841" class="external-link" rel="nofollow noreferrer">https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-nightly-release/2841</a>)
<blockquote>
<p>    java.lang.AssertionError: Unexpected 2 times numCPUs triggering events after being re-enabled. Found 0 (numCPUs = 8) expected:&lt;0&gt; but was:&lt;16&gt;<br/>
        at org.junit.Assert.fail(Assert.java:88)<br/>
        at org.junit.Assert.failNotEquals(Assert.java:743)<br/>
        at org.junit.Assert.assertEquals(Assert.java:118)<br/>
        at org.junit.Assert.assertEquals(Assert.java:555)<br/>
        at kieker.test.monitoring.junit.probe.adaptiveMonitoring.sigar.TestCPUsCombinedPercSampler.testDeactivationAndReactivation(TestCPUsCombinedPercSampler.java:93)</p></blockquote>
<p>(<a href="https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-nightly-release/2837" class="external-link" rel="nofollow noreferrer">https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-nightly-release/2837</a>)</p>
<blockquote>
<p>java.lang.AssertionError: Unexpected number of triggering events before disabling expected:&lt;3&gt; but was:&lt;2&gt;<br/>
        at org.junit.Assert.fail(Assert.java:88)<br/>
        at org.junit.Assert.failNotEquals(Assert.java:743)<br/>
        at org.junit.Assert.assertEquals(Assert.java:118)<br/>
        at org.junit.Assert.assertEquals(Assert.java:555)<br/>
        at kieker.test.monitoring.junit.probe.adaptiveMonitoring.sigar.TestMemSwapUsageSampler.testDeactivationAndReactivation(TestMemSwapUsageSampler.java:93)</p></blockquote>
<p>(<a href="https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-nightly-release/2836" class="external-link" rel="nofollow noreferrer">https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-nightly-release/2836</a> and <a href="https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-nightly-release/2835" class="external-link" rel="nofollow noreferrer">https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-nightly-release/2835</a>)</p>
<blockquote>
<p>java.lang.AssertionError: Unexpected number of triggering events before disabling expected:&lt;0&gt; but was:&lt;1&gt;<br/>
        at org.junit.Assert.fail(Assert.java:88)<br/>
        at org.junit.Assert.failNotEquals(Assert.java:743)<br/>
        at org.junit.Assert.assertEquals(Assert.java:118)<br/>
        at org.junit.Assert.assertEquals(Assert.java:555)<br/>
        at kieker.test.monitoring.junit.probe.adaptiveMonitoring.sigar.TestCPUsCombinedPercSampler.testDeactivationAndReactivation(TestCPUsCombinedPercSampler.java:77)</p></blockquote>
<p><br class="atl-forced-newline" /></p></li>
</ul>

<ul>
	<li>Count: 2 <b>kieker.test.monitoring.junit.probe.adaptiveMonitoring.mxbean.TestCompilationSampler &gt;  testAdaptiveMonitoring</b> (<a href="https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-nightly-release/2844" class="external-link" rel="nofollow noreferrer">https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-nightly-release/2844</a> and <a href="https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-nightly-release/2840" class="external-link" rel="nofollow noreferrer">https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-nightly-release/2840</a>)
<blockquote>
<p>kieker.test.monitoring.junit.probe.adaptiveMonitoring.mxbean.TestCompilationSampler &gt; testAdaptiveMonitoring FAILED<br/>
    java.lang.AssertionError: Unexpected number of triggering events before disabling expected:&lt;4&gt; but was:&lt;0&gt;<br/>
        at org.junit.Assert.fail(Assert.java:88)<br/>
        at org.junit.Assert.failNotEquals(Assert.java:743)<br/>
        at org.junit.Assert.assertEquals(Assert.java:118)<br/>
        at org.junit.Assert.assertEquals(Assert.java:555)<br/>
        at kieker.test.monitoring.junit.probe.adaptiveMonitoring.mxbean.TestCompilationSampler.checkNumEventsBeforeMonitoringDisabled(TestCompilationSampler.java:51)</p></blockquote></li>
</ul>

<ul>
	<li><b>kieker.test.monitoring.junit.probe.adaptiveMonitoring.mxbean.TestMemorySampler &gt; testAdaptiveMonitoring</b> (<a href="https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-nightly-release/2856" class="external-link" rel="nofollow noreferrer">https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-nightly-release/2856</a>)
<blockquote>
<p>kieker.test.monitoring.junit.probe.adaptiveMonitoring.mxbean.TestMemorySampler &gt; testAdaptiveMonitoring FAILED<br/>
    java.lang.AssertionError: Unexpected number of triggering events before disabling expected:&lt;4&gt; but was:&lt;0&gt;<br/>
        at org.junit.Assert.fail(Assert.java:88)<br/>
        at org.junit.Assert.failNotEquals(Assert.java:743)<br/>
        at org.junit.Assert.assertEquals(Assert.java:118)<br/>
        at org.junit.Assert.assertEquals(Assert.java:555)<br/>
        at kieker.test.monitoring.junit.probe.adaptiveMonitoring.mxbean.TestMemorySampler.checkNumEventsBeforeMonitoringDisabled(TestMemorySampler.java:51)</p></blockquote></li>
</ul>

[KIEKER-1461]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author Thomas F. Düllmann -- Tue, 5 Jul 2016 12:37:23 +0200
<p>The tests seem to fail in the checkscript run only.</p>

**Comment by rju** [comment]
author André van Hoorn -- Wed, 6 Sep 2017 09:18:34 +0200
<p>The list has been created before migrating the pipeline. Create a new ticket if builds fail sporadically again. </p>
