### ISSUE TITLE
[KIEKER-1446] SyncDbWriter does not work with MySQL 5.7

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2391]
JIRA Issue: [KIEKER-1446] SyncDbWriter does not work with MySQL 5.7
Original Reporter: Sven Ulrich
 *** 
<p><span class="error">&#91;postmigration Trac-&gt;Jira&#93;</span></p>

<p>Hello,</p>

<p>i tried to use the SyncDbWriter. But the creation of index table fails with the following error message:</p>

<p>Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '1024), classname SET (1024))' at line 1<br/>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)<br/>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)<br/>
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)<br/>
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)<br/>
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)<br/>
	at com.mysql.jdbc.Util.getInstance(Util.java:387)<br/>
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939)<br/>
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)<br/>
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)<br/>
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)<br/>
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)<br/>
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2547)<br/>
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2505)<br/>
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:840)<br/>
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:740)<br/>
	at kieker.monitoring.writer.database.DBWriterHelper.createIndexTable(DBWriterHelper.java:248)<br/>
	at kieker.monitoring.writer.database.SyncDbWriter.&lt;init&gt;(SyncDbWriter.java:83)<br/>
	... 14 more<br/>
06.04.2016 14:40:43 kieker.monitoring.core.controller.MonitoringController cleanup<br/>
INFO: Shutting down Monitoring Controller (KIEKER)<br/>
06.04.2016 14:40:43 kieker.monitoring.core.registry.ControlFlowRegistry &lt;clinit&gt;<br/>
INFO: First threadId will be 0</p>

<p>The following things were used:<br/>
Java 8<br/>
Kieker 1.12 (kieker-1.12-aspectj.jar)<br/>
mysql-connector-java-5.1.38-bin.jar</p>

<p>The method createIndexTable() in the class tries to execute the following query <br/>
CREATE TABLE kieker (tablename SET (1024), classname SET (1024)); <br/>
which fails.</p>

<p>Kind Regards,<br/>
Sven</p>

[KIEKER-1446]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Thu, 5 May 2016 08:42:49 +0200
<p><a href="https://kieker-monitoring.atlassian.net/secure/ViewProfile.jspa?accountId=557058%3Aee9d3989-211a-4372-9519-293f7aaff64b" class="user-hover" rel="557058:ee9d3989-211a-4372-9519-293f7aaff64b" data-account-id="557058:ee9d3989-211a-4372-9519-293f7aaff64b" accountid="557058:ee9d3989-211a-4372-9519-293f7aaff64b" rel="noreferrer">Dominic Parga Cacheiro</a>: Could you have a look at this? First step would be reproducing the problem with the SyncDBWriter and MySQL (5.7). </p>

**Comment by rju** [comment]
author Dominic Parga Cacheiro -- Thu, 5 May 2016 14:12:52 +0200
<p><a href="https://kieker-monitoring.atlassian.net/secure/ViewProfile.jspa?accountId=557058%3A9e328f65-6e51-4aca-812b-82e63a91a0ae" class="user-hover" rel="557058:9e328f65-6e51-4aca-812b-82e63a91a0ae" data-account-id="557058:9e328f65-6e51-4aca-812b-82e63a91a0ae" accountid="557058:9e328f65-6e51-4aca-812b-82e63a91a0ae" rel="noreferrer">Andre van Hoorn</a> Okay, I will look at it after the weekend.</p>
