### ISSUE TITLE
[KIEKER-1440] IRL compiler fails to generate Kieker records

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2397]
JIRA Issue: [KIEKER-1440] IRL compiler fails to generate Kieker records
Original Reporter: Andre van Hoorn
 *** 
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>avhAndrè van Hoorn-ThinkPad-T450s:~/git_work/kieker$ ./gradlew generateRecords
JAR to delete: ArchivePublishArtifact kieker:jar:jar:
:kieker-common:generateRecords
0    [main] INFO  trumentation.rl.cli.StandaloneSetup  - Registering platform uri '/home/avh/git_work/kieker'
Mon Feb 15 20:51:48 CET 2016 - [main] Product-specified preferences called before plugin is started
Exception in thread "main" com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, org.eclipse.emf.common.util.WrappedException: java.lang.ArrayIndexOutOfBoundsException: 3
  at org.eclipse.xtext.common.services.TerminalsGrammarAccess.&lt;init&gt;(TerminalsGrammarAccess.java:32)
  at org.eclipse.xtext.common.services.TerminalsGrammarAccess.class(TerminalsGrammarAccess.java:32)
  while locating org.eclipse.xtext.common.services.TerminalsGrammarAccess
    for parameter 1 at de.cau.cs.se.instrumentation.rl.services.RecordLangGrammarAccess.&lt;init&gt;(RecordLangGrammarAccess.java:1079)
  at de.cau.cs.se.instrumentation.rl.services.RecordLangGrammarAccess.class(RecordLangGrammarAccess.java:1079)
  while locating de.cau.cs.se.instrumentation.rl.services.RecordLangGrammarAccess
  while locating org.eclipse.xtext.IGrammarAccess
    for field at org.eclipse.xtext.linking.lazy.LazyLinker.grammarAccess(LazyLinker.java:272)
  while locating org.eclipse.xtext.linking.lazy.LazyLinker
  while locating org.eclipse.xtext.linking.ILinker
    for field at org.eclipse.xtext.resource.XtextResource.linker(XtextResource.java:391)
  while locating org.eclipse.xtext.linking.lazy.LazyLinkingResource
  while locating org.eclipse.xtext.resource.XtextResource
Caused by: org.eclipse.emf.common.util.WrappedException: java.lang.ArrayIndexOutOfBoundsException: 3
	at org.eclipse.xtext.parser.BaseEPackageAccess.loadResource(BaseEPackageAccess.java:57)
	at org.eclipse.xtext.parser.BaseEPackageAccess.loadGrammarFile(BaseEPackageAccess.java:44)
	at org.eclipse.xtext.service.GrammarProvider.getGrammar(GrammarProvider.java:60)
	at org.eclipse.xtext.common.services.TerminalsGrammarAccess.internalFindGrammar(TerminalsGrammarAccess.java:37)
	at org.eclipse.xtext.common.services.TerminalsGrammarAccess.&lt;init&gt;(TerminalsGrammarAccess.java:33)
	at org.eclipse.xtext.common.services.TerminalsGrammarAccess$$FastClassByGuice$$66750cdb.newInstance(&lt;generated&gt;)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
      m.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)

...

</pre>
</div></div>

<p>Reiner Jung: Any idea? </p>

[KIEKER-1440]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author rju -- Thu, 21 Apr 2016 21:49:40 +0200
<p>The error is produced by class JarModelGlobalScopeProvider which uses an reference to the workspace. However, workspaces do not exist in the standalone generator. Therefore, I switched this back to TypeGlobalScopeProvider. The problem with this solution is that now the standalone generator cannot understand jars containing Kieker records. This is not an issue for the Kieker build script, but it is caused by a deeper issue that the present CLI compiler setup should be reworked as an OSGi/RCP commandline application or find a less hacky way to determine the active project in JarModelGlobalScopeProvider.</p>

<p>Anyway, this issue has been fixed in master.</p>
