### ISSUE TITLE
[KIEKER-1439] TestSpringMethodInterceptorInterceptorIsEntryPoint includes file not found

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2398]
JIRA Issue: [KIEKER-1439] TestSpringMethodInterceptorInterceptorIsEntryPoint includes file not found
Original Reporter: Andre van Hoorn
 *** 
<p>See log</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>
kieker.test.monitoring.junit.probe.spring.executions.TestSpringMethodInterceptorInterceptorIsEntryPoint STANDARD_ERROR
    Feb 15, 2016 3:53:55 PM kieker.monitoring.writer.AbstractAsyncThread run
    SEVERE: Writer thread will halt
    java.io.FileNotFoundException: /opt/kieker/kieker-monitoring/build/junit5431888169924518489/kieker-20160215-155355044-UTC-dce053da61ac-KIEKER/kieker.map (No such file or directory)
    	at java.io.FileOutputStream.openAppend(Native Method)
    	at java.io.FileOutputStream.&lt;init&gt;(FileOutputStream.java:210)
    	at kieker.monitoring.writer.filesystem.map.MappingFileWriter.write(MappingFileWriter.java:72)
    	at kieker.monitoring.writer.filesystem.async.AbstractFsWriterThread.consume(AbstractFsWriterThread.java:128)
    	at kieker.monitoring.writer.AbstractAsyncThread.run(AbstractAsyncThread.java:119)
    Feb 15, 2016 3:53:55 PM kieker.monitoring.core.controller.MonitoringController terminateMonitoring
    INFO: Controller shutting down in 1000 milliseconds
</pre>
</div></div>

<p>Doesn't look like this is intended. Double-check.</p>

**Comment by rju** [comment]
author André van Hoorn -- Thu, 21 Apr 2016 21:45:15 +0200
<p>For Jetty: </p>


<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>kieker.test.monitoring.junit.probe.spring.executions.jetty.TestSpringMethodInterceptor STANDARD_ERROR
    Feb 15, 2016 3:53:55 PM kieker.monitoring.writer.AbstractAsyncThread run
    SEVERE: Writer thread will halt
    java.io.FileNotFoundException: /opt/kieker/kieker-monitoring/build/junit1934602726060339875/kieker-20160215-155355065-UTC-dce053da61ac-KIEKER/kieker-20160215-155355075-UTC-000-Thread-32.dat (No such file or directory)
    	at java.io.FileOutputStream.open(Native Method)
    	at java.io.FileOutputStream.&lt;init&gt;(FileOutputStream.java:212)
    	at java.io.FileOutputStream.&lt;init&gt;(FileOutputStream.java:99)
    	at kieker.monitoring.writer.filesystem.async.FsWriterThread.prepareFile(FsWriterThread.java:107)
    	at kieker.monitoring.writer.filesystem.async.AbstractFsWriterThread.consume(AbstractFsWriterThread.java:133)
    	at kieker.monitoring.writer.AbstractAsyncThread.run(AbstractAsyncThread.java:119)
    Feb 15, 2016 3:53:55 PM kieker.monitoring.core.controller.MonitoringController terminateMonitoring
    INFO: Controller shutting down in 1000 milliseconds

</pre>
</div></div>
