### ISSUE TITLE
[KIEKER-1438] testTCPClientConnector test is failing in Travis-CI

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2399]
JIRA Issue: [KIEKER-1438] testTCPClientConnector test is failing in Travis-CI
Original Reporter: Thomas F. Düllmann
 *** 
<p><span class="error">&#91;Post-migration of ticket from Trac&#93;</span></p>

<p>Even though the jenkins builds seem to be stable now, the Travis-CI build has a failing test:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>kieker.test.tools.junit.bridge.TestTCPClientConnector &gt; testTCPClientConnector FAILED
    java.lang.AssertionError: Connector initialization failed: Connection refused
        at org.junit.Assert.fail(Assert.java:88)
        at kieker.test.tools.junit.bridge.AbstractConnectorTest.initialize(AbstractConnectorTest.java:87)
        at kieker.test.tools.junit.bridge.TestTCPClientConnector.testTCPClientConnector(TestTCPClientConnector.java:60)
</pre>
</div></div>

<p>I guess we have to check whether there are any limitations in Travis that might be at play here.</p>

[KIEKER-1438]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Thu, 21 Apr 2016 21:35:43 +0200
<p>Travis-CI is executing the build inside a Docker container, right? Is it possible to reproduce this locally by executing the build in a container?</p>

**Comment by rju** [comment]
author Thomas F. Düllmann -- Thu, 21 Apr 2016 21:36:39 +0200
<p>Replying to <span class="error">&#91;comment:1 avh&#93;</span>:<br/>
&gt; Travis-CI is executing the build inside a Docker container, right? Is it possible to reproduce this locally by executing the build in a container?</p>

<p>I cannot reproduce this issue locally. I used the same docker container for my local test and the build succeeded.</p>

**Comment by rju** [comment]
author André van Hoorn -- Tue, 8 Aug 2017 21:49:50 +0200
<p>Can be closed as Travis is not a topic at this time. </p>

**Comment by rju** [comment]
author André van Hoorn -- Tue, 8 Aug 2017 21:51:03 +0200
<p>Not using Travis any more. </p>
