### ISSUE TITLE
[KIEKER-1369] Build problem IRL in gradle script

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2431]
JIRA Issue: [KIEKER-1369] Build problem IRL in gradle script
Original Reporter: Reiner Jung
 *** 
<p>When using <tt>./gradlew generateRecords</tt> the build fails with a long list of errors which look like the text below. This is when executed with Java 8. With Java 7 the error is "wrong major version 52." indicating that at least Java 8 must be used, which is a necessity due to the move to Eclipse Mars.</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre> Error injecting constructor, org.eclipse.emf.common.util.WrappedException: java.lang.ArrayIndexOutOfBoundsException: 3
  at org.eclipse.xtext.common.services.TerminalsGrammarAccess.&lt;init&gt;(TerminalsGrammarAccess.java:32)
  at org.eclipse.xtext.common.services.TerminalsGrammarAccess.class(TerminalsGrammarAccess.java:32)
  while locating org.eclipse.xtext.common.services.TerminalsGrammarAccess
    for parameter 1 at de.cau.cs.se.instrumentation.rl.services.RecordLangGrammarAccess.&lt;init&gt;(RecordLangGrammarAccess.java:1079)
  at de.cau.cs.se.instrumentation.rl.services.RecordLangGrammarAccess.class(RecordLangGrammarAccess.java:1079)
  while locating de.cau.cs.se.instrumentation.rl.services.RecordLangGrammarAccess
  while locating org.eclipse.xtext.IGrammarAccess
    for field at org.eclipse.xtext.conversion.impl.AbstractIDValueConverter.grammarAccess(AbstractIDValueConverter.java:118)
  while locating org.eclipse.xtext.conversion.impl.IDValueConverter
  while locating org.eclipse.xtext.conversion.impl.AbstractIDValueConverter
    for field at org.eclipse.xtext.common.services.DefaultTerminalConverters.idValueConverter(DefaultTerminalConverters.java:24)
  at org.eclipse.xtext.common.services.DefaultTerminalConverters.class(DefaultTerminalConverters.java:24)
  while locating org.eclipse.xtext.common.services.DefaultTerminalConverters
  while locating org.eclipse.xtext.conversion.IValueConverterService
    for field at org.eclipse.xtext.linking.impl.LinkingHelper.valueConverter(LinkingHelper.java:32)
  while locating org.eclipse.xtext.linking.impl.LinkingHelper
    for field at org.eclipse.xtext.linking.lazy.LazyLinkingResource.linkingHelper(LazyLinkingResource.java:425)
  while locating org.eclipse.xtext.linking.lazy.LazyLinkingResource
  while locating org.eclipse.xtext.resource.XtextResource
Caused by: org.eclipse.emf.common.util.WrappedException: java.lang.ArrayIndexOutOfBoundsException: 3
	at org.eclipse.xtext.parser.BaseEPackageAccess.loadResource(BaseEPackageAccess.java:57)
	at org.eclipse.xtext.parser.BaseEPackageAccess.loadGrammarFile(BaseEPackageAccess.java:44)
	at org.eclipse.xtext.service.GrammarProvider.getGrammar(GrammarProvider.java:60)
	at org.eclipse.xteon.services.TerminalsGrammarAccess.internalFindGrammar(TerminalsGrammarAccess.java:37)
	at org.eclipse.xtext.common.services.TerminalsGrammarAccess.&lt;init&gt;(TerminalsGrammarAccess.java:33)
	at org.eclipse.xtext.common.services.TerminalsGrammarAccess$$FastClassByGuice$$66750cdb.newInstance(&lt;generated&gt;)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.injernal.FactoryProxy.get(FactoryProxy.java:54)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:53)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:94)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:737)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:53)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:94)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:53)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:94)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:53)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:94)
	google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
	at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
	at org.eclipse.xtext.resource.XtextResourceFactory.createResource(XtextResourceFactory.java:19)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.createResource(ResourceSetImpl.java:434)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandCreateResource(ResourceSetImpl.java:243)
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:196)
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:26)
	at de.cau.cs.se.instrumentation.rl.cli.IRLParser.getResource(IRLParser.java:246)
	at de.cau.cs.se.instrumentation.rl.cli.IRLParser.directoryWalkerResource(IRLParser.java:205)
	at de.cau.cs.se.instrumentation.rl.cli.IRLParser.directoryWalkerResource(IRLParser.java:198)
	at de.cau.cs.se.instrumentation.rl.cli.IRLParser.directoryWalkerResource(IRLParser.java:198)
	at de.cau.cs.se.instrumentation.rl.cli.IRLParser.compileAll(IRLParser.java:182)
	at de.cau.cs.se.instrumentation.rl.cli.CLICompilerMain.main(CLICompilerMain.java:153)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectInputStream.getEStructuralFeatureData(BinaryResourceImpl.java:2125)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectInputStream.loadEObject(BinaryResourceImpl.java:2521)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectInputStream.loadFeatureValue(BinaryResourceImpl.java:2545)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectInputStream.loadEObject(BinaryResourceImpl.java:2522)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectInpm.loadEObjects(BinaryResourceImpl.java:2222)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectInputStream.loadFeatureValue(BinaryResourceImpl.java:2555)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectInputStream.loadEObject(BinaryResourceImpl.java:2522)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectInputStream.loadEObjects(BinaryResourceImpl.java:2222)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectInputStream.loadFeatureValue(BinaryResourceImpl.java:2555)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectInputStream.loadEObject(BinaryResourceImpl.java:2522)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectInputStream.loadResource(BinaryResourceImpl.java:2205)
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad(XMLResourceImpl.java:219)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1518)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1297)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:201)
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:26)
	at org.eclipse.xtext.parser.BaseEPackageAccess.loadResource(BaseEPackageAccess.java:52)
	... 62 more

33 errors
	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)
	at org.eclipse.xtext.resource.XtextResourceFactory.createResource(XtextResourceFactory.java:19)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.createResource(ResourceSetImpl.java:434)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandCreateResource(ResourceSetImpl.java:243)
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:196)
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSesource(SynchronizedXtextResourceSet.java:26)
	at de.cau.cs.se.instrumentation.rl.cli.IRLParser.getResource(IRLParser.java:246)
	at de.cau.cs.se.instrumentation.rl.cli.IRLParser.directoryWalkerResource(IRLParser.java:205)
	at de.cau.cs.se.instrumentation.rl.cli.IRLParser.directoryWalkerResource(IRLParser.java:198)
	at de.cau.cs.se.instrumentation.rl.cli.IRLParser.directoryWalkerResource(IRLParser.java:198)
	at de.cau.cs.se.instrumentation.rl.cli.IRLParser.compileAll(IRLParser.java:182)
	at de.cau.cs.se.instrumentation.rl.cli.CLICompilerMain.main(CLICompilerMain.java:153)
</pre>
</div></div>

[KIEKER-1369]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author rju -- Wed, 23 Aug 2017 11:06:17 +0200
<p>Bug does no longer exist.</p>
