### ISSUE TITLE
[KIEKER-1404] Add record reader and writer for AMQP

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2452]
JIRA Issue: [KIEKER-1404] Add record reader and writer for AMQP
Original Reporter: Holger Knoche
 *** 
<p>AMQP is a standardized protocol for message queues, which is, for instance, used natively by RabbitMQ. This ticket proposes the creation of a reader/writer pair which allows to send monitoring records using an AMQP queue (without the need for a JMS wrapper).</p>

[KIEKER-1404]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Thu, 13 Aug 2015 09:28:07 +0200
<p>See also 
    <span class="jira-issue-macro resolved" data-jira-key="KIEKER-931" >
                <a href="https://kieker-monitoring.atlassian.net/browse/KIEKER-931" class="jira-issue-macro-key issue-link"  title="Feature wish: Add alternative MOM writer/reader (e.g., RabbitMQ)" >
            <img class="icon" src="https://kieker-monitoring.atlassian.net/images/icons/issuetypes/genericissue.png" />
            KIEKER-931
        </a>
                                                    <span class="aui-lozenge aui-lozenge-subtle aui-lozenge-success jira-macro-single-issue-export-pdf">Done</span>
            </span>
</p>

**Comment by rju** [comment]
author holgerknoche -- Mon, 24 Aug 2015 23:34:13 +0200
<p>AMQP reader and writer are created and checked in on branch amqp-capability. I have prepared an appendix-AMQP example (based on the appendix-JMS example) and will add it as soon as I have finished the accompanying Gradle script.</p>

**Comment by rju** [comment]
author holgerknoche -- Fri, 28 Aug 2015 22:06:21 +0200
<p>The example and corresponding extension to the user guide have been committed to the branch amqp-capability.</p>

**Comment by rju** [comment]
author André van Hoorn -- Fri, 4 Sep 2015 03:21:26 +0200
<p>Reopening because not in the master/release branch, yet. Otherwise we loose track of this issue. </p>

<p>Thomas: Could you merge it into the release branch and test the functionality based on the (new) user guide example?</p>

**Comment by rju** [comment]
author Thomas F. Düllmann -- Fri, 11 Sep 2015 15:07:09 +0200
<p>Replying to <span class="error">&#91;holger.knoche|comment:7&#93;</span>:<br/>
&gt; The AMQPReader was too eager to create a connection to the AMQP server. I moved large parts of the initialization code (thread and connection creation) to the init() method and made the formerly final attributes volatile. Please update the amqp-capability branch and try again. It should work now without any adjustments.<br/>
&gt; Please note that the RabbitMQ client expects an "amqp:" URI. The stack trace indicates that you used a "tcp:" URI.</p>

<p>Thank you, that seems to work now.</p>

<p>By default the web interface is not enabled in RabbitMQ. To enable it, it is necessary to enable the <tt>rabbitmq_management</tt> plugin (<tt>rabbitmq-plugins enable rabbitmq_management</tt>). Afterwards it is possible to access the web interface via <tt><a href="http://localhost:15672" class="external-link" rel="nofollow noreferrer">http://localhost:15672</a></tt>.</p>

<p>When testing the example (chapter D.1.3 and D.2) it was not completely clear to me what settings are preconfigured already and what settings I have to change to make the example work.<br/>
The default values in the <tt>AMQPAnalysisStarter</tt>, <tt>build.gradle</tt> and <tt>kieker.monitoring.properties</tt> were different than those that either RabbitMQ or the userguide propose:</p>
<ul>
	<li>RabbitMQ default port: <tt>5672</tt></li>
	<li>RabbitMQ default credentials: <tt>guest:guest</tt></li>
	<li>User guide queue name: <tt>kieker</tt></li>
</ul>


<p>Although having tested several combinations it didn't work out for me yet.<br/>
I always ended up having a similar error message like this:</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>$ ./gradlew -i -S runAnalysisAMQP
[..]
amqp-uri:amqp://guest:guest127.0.0.1:5672/virtualhost
amqp-queue-name:kieker

Sep 11, 2015 3:04:25 PM kieker.analysis.analysisComponent.AbstractAnalysisComponent handleInitializationError
SEVERE: An error occurred initializing the AMQP reader: java.io.IOException
Sep 11, 2015 3:04:25 PM kieker.analysis.AnalysisController terminate
INFO: Error during analysis. Terminating ...
Sep 11, 2015 3:04:25 PM kieker.analysis.AnalysisController terminate
SEVERE: Error during shutdown.
java.lang.NullPointerException
	at kieker.analysis.plugin.reader.amqp.AMQPReader.terminate(AMQPReader.java:216)
	at kieker.analysis.plugin.AbstractPlugin.shutdown(AbstractPlugin.java:578)
	at kieker.analysis.AnalysisController.terminate(AnalysisController.java:550)
	at kieker.analysis.AnalysisController.run(AnalysisController.java:464)
	at kieker.examples.userguide.appendixAMQP.AMQPAnalysisStarter.main(AMQPAnalysisStarter.java:59)

kieker.analysis.exception.AnalysisConfigurationException: Reader 'AMQPReader-1' (AMQPReader) failed to initialize.
	at kieker.analysis.AnalysisController.run(AnalysisController.java:465)
	at kieker.examples.userguide.appendixAMQP.AMQPAnalysisStarter.main(AMQPAnalysisStarter.java:59)
:runAnalysisAMQP (Thread[main,5,main]) completed. Took 3.361 secs.

BUILD SUCCESSFUL
</pre>
</div></div>

<p>The credentials are valid and the queue exists.</p>

**Comment by rju** [comment]
author holgerknoche -- Fri, 11 Sep 2015 19:20:41 +0200
<p>Thanks for the hint regarding the management UI, I have added the appropriate instructions to the user guide. In addition, I simplified the default URI in the example configuration. I suspect that the only thing that kept the example from working in your case was the virtual host declaration; the URI <tt>amqp://guest:guest127.0.0.1:5672</tt> would probably have worked. Since I changed the example URI to <tt>amqp://guest:guest127.0.0.1</tt>, the example should work immediately for you.</p>

**Comment by rju** [comment]
author Thomas F. Düllmann -- Sun, 13 Sep 2015 14:38:53 +0200
<p>Thanks.<br/>
I merged the <tt>1.12</tt> branch into the <tt>amqp-capability</tt> branch and tested the example. I just had to fix the URL in the <tt>build.gradle</tt> file too to make it work. Additionally I added some information about the RabbitMQ default management UI URL and its default credentials to the userguide.</p>

<p>A merge request for merging the <tt>amqp-capability</tt> branch into the <tt>1.12</tt> branch has been created:<br/>
<a href="https://build.se.informatik.uni-kiel.de/gitlab/kieker/kieker/merge_requests/45" class="external-link" rel="nofollow noreferrer">https://build.se.informatik.uni-kiel.de/gitlab/kieker/kieker/merge_requests/45</a></p>

**Comment by rju** [comment]
author André van Hoorn -- Thu, 17 Sep 2015 13:54:54 +0200
<p>Replying to <span class="error">&#91;thomas.duellmann|comment:10&#93;</span>:<br/>
&gt; Thanks.<br/>
&gt; I merged the <tt>1.12</tt> branch into the <tt>amqp-capability</tt> branch and tested the example. I just had to fix the URL in the <tt>build.gradle</tt> file too to make it work. Additionally I added some information about the RabbitMQ default management UI URL and its default credentials to the userguide.<br/>
&gt; <br/>
&gt; A merge request for merging the <tt>amqp-capability</tt> branch into the <tt>1.12</tt> branch has been created:<br/>
&gt; <a href="https://build.se.informatik.uni-kiel.de/gitlab/kieker/kieker/merge_requests/45" class="external-link" rel="nofollow noreferrer">https://build.se.informatik.uni-kiel.de/gitlab/kieker/kieker/merge_requests/45</a></p>

<p>Thomas: Thanks. Given the merge conflict reported by GitLab: could you "manually" merge it into the 1.12 branch? You should have the right to merge into the 1.12 without a GitLab merge request. </p>

**Comment by rju** [comment]
author Thomas F. Düllmann -- Thu, 17 Sep 2015 20:25:31 +0200
<p>I merged the <tt>AMQP-capability</tt> branch into <tt>1.12</tt> in changeset:75a84524d91cc72081b0ad3314b95a03d86f8cf9</p>

**Comment by rju** [comment]
author André van Hoorn -- Fri, 18 Sep 2015 15:47:18 +0200
<p>Added cleanup in build script for AMQP example in changeset:7d39dd57247102ed7869f1b57a47ad810dc6c7b6/kieker-git</p>

**Comment by rju** [comment]
author André van Hoorn -- Fri, 18 Sep 2015 16:01:56 +0200
<p>The branch <tt>amqp-capability</tt> can be deleted, right?</p>
