### ISSUE TITLE
[KIEKER-1418] Regression tests for Kieker's logging infrastructure

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2471]
JIRA Issue: [KIEKER-1418] Regression tests for Kieker's logging infrastructure
Original Reporter: Andre van Hoorn
 *** 
<p>The Kieker logger tries to automatically detect and use logging libraries that are already used by the system under monitoring. In case the a certain logger to be used by Kieker shall be enforced, we provide the configuration property <tt>kieker.common.logging.Log</tt>, e.g., passing {{ &#45;Dkieker.common.logging.Log=JDK}} to the JVM to enforce the use of the standard JDK logger. </p>

<p>As far as I know, we currently do not have regression tests to make sure that the auto-detection mechanism works properly. </p>

<p>In the following case, a problem occurred together with the Commons Logging library. Using the afore-mentioned parameter (enforcing the JDK logger), the problem was "solved".</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at kieker.common.logging.LogImplCommonsLogging.&lt;init&gt;(LogImplCommonsLogging.java:49)
	at kieker.common.logging.LogFactory.getLog(LogFactory.java:92)
	at kieker.common.logging.LogFactory.getLog(LogFactory.java:74)
	at kieker.common.logging.LogFactory.&lt;clinit&gt;(LogFactory.java:48)
	at kieker.monitoring.core.controller.AbstractController.&lt;clinit&gt;(AbstractController.java:31)
        ...
</pre>
</div></div>

<p>Just for the records, the context of failing part (line 49) in <tt>LogImplCommonsLogging</tt>: </p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>41	/**
42	 * Creates a new instance of this class using the given parameters.
43	 *
44	 * param name
45	 *            The name of the logger to be used.
46	 */
47	protected LogImplCommonsLogging(final String name) {
48		if (JDK14PATCH) {
49			this.log = org.apache.commons.logging.impl.Jdk14LoggerPatched.getLog(name);
50		} else {
51			this.log = org.apache.commons.logging.LogFactory.getLog(name);
52		}
53	}
</pre>
</div></div>

[KIEKER-1418]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author rju -- Wed, 9 Jun 2021 11:36:39 +0200
<p>As we have replaced the Kieker logging facilities with standard logging facilities that is Simple Logging Facilities 4 Java (slf4j) and logback as default implementation, this ticket might be obsolete.</p>
