### ISSUE TITLE
[KIEKER-1296] InvalidREvaluationResultException should not inherit from NullPointerException

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2514]
JIRA Issue: [KIEKER-1296] InvalidREvaluationResultException should not inherit from NullPointerException
Original Reporter: Teerat Pitakrat
 *** 
<p>Currently this exception is unchecked. If thrown, it propagates through the whole architecture up to the next catch block.<br/>
Simply extending Exception should be ok.</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>Jan 28, 2015 2:45:10 PM kieker.tools.opad.filter.TimeSeriesPointAggregatorFilter (TimeSeriesPointAggregatorFilter-3) deliver
WARNING: Caught exception when sending data from kieker.tools.opad.filter.TimeSeriesPointAggregatorFilter: OutputPort aggregatedTSPoint to de.uni_stuttgart.rss.spm.ComponentPredictionModelFilter's InputPort inputMonitoringData
kieker.tools.util.InvalidREvaluationResultException: Got a null result for evaluation input: "var_17384 &lt;&lt;- auto.arima(var_17383,parallel="true")"
	at kieker.tools.util.RBridgeControl.evalWithR(RBridgeControl.java:78)
	at kieker.tools.tslib.forecast.AbstractRForecaster.forecast(AbstractRForecaster.java:180)
	at de.uni_stuttgart.rss.cpm.ArimaCPM.predictFailureProbability(ArimaCPM.java:172)
	at de.uni_stuttgart.rss.spm.ComponentPredictionModelFilter.inputMonitoringData(ComponentPredictionModelFilter.java:91)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at kieker.analysis.plugin.AbstractPlugin.deliver(AbstractPlugin.java:212)
	at kieker.tools.opad.filter.TimeSeriesPointAggregatorFilter.calculateAndDeliverAggregationValue(TimeSeriesPointAggregatorFilter.java:189)
	at kieker.tools.opad.filter.TimeSeriesPointAggregatorFilter.processInput(TimeSeriesPointAggregatorFilter.java:153)
	at kieker.tools.opad.filter.TimeSeriesPointAggregatorFilter.inputTSPoint(TimeSeriesPointAggregatorFilter.java:122)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at kieker.analysis.plugin.AbstractPlugin.deliver(AbstractPlugin.java:212)
	at de.uni_stuttgart.rss.spm.ComponentNameAndResponseTimeExtractor.inputOperationExecutionRecord(ComponentNameAndResponseTimeExtractor.java:86)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at kieker.analysis.plugin.AbstractPlugin.deliver(AbstractPlugin.java:212)
	at kieker.analysis.plugin.reader.filesystem.FSReader.read(FSReader.java:147)
	at kieker.analysis.AnalysisController$1.run(AnalysisController.java:486)
	at java.lang.Thread.run(Thread.java:745)
</pre>
</div></div>

[KIEKER-1296]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author teeratpitakrat -- Wed, 28 Jan 2015 15:44:15 +0100
<p>Seems to be fixed in 1541-opad-experiment branch.</p>
