### ISSUE TITLE
[KIEKER-1266] Gradle - Include Gradle wrapper scripts

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2528]
JIRA Issue: [KIEKER-1266] Gradle - Include Gradle wrapper scripts
Original Reporter: Andre van Hoorn
 *** 
<p>Gradle provides these shell and batch scripts called <tt>gradlew{.bat</tt>}</p>

[KIEKER-1266]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author André van Hoorn -- Mon, 5 Jan 2015 11:42:49 +0100
<p>See instructions in Gradle (2.2.1) User Guide Chapter 62 "The Gradle Wrapper"</p>

<p>"The Gradle Wrapper (henceforth referred to as the “wrapper”) is the preferred way of starting a Gradle build.<br/>
The wrapper is a batch script on Windows, and a shell script for other operating systems. When you start a<br/>
Gradle build via the wrapper, Gradle will be automatically downloaded and used to run the build.</p>

<p>The wrapper is something you check into version control. By distributing the wrapper should with your project,<br/>
anyone can work with it without needing to install Gradle beforehand. Even better, users of the build are<br/>
guaranteed to use the version of Gradle that the build was designed to work with. Of course, this is also great for<br/>
continuous integration servers (i.e. servers that regularly build your project) as it requires no configuration on<br/>
the server."</p>

<p>Implemented the following changes in changeset:ff782cbec292cd38b8a84763530608122bbdf391/kieker-git</p>

<p>Added the wrapper script by<br/>
1. Adding the following task to our <tt>build.gradle</tt> file:<br/>
   {{</p>
{
	task wrapper(type: Wrapper) \{
		gradleVersion = '2.2.1'
		}
<p>   }}}<br/>
2. Executing the task:<br/>
   {{</p>
{
   avhAndrè van Hoorn-ThinkPad-RSS:0:~/git_work/kieker &lt;1533-gradle&gt;* $ gradle wrapper
   }
<p>}}<br/>
3. Adding the downloaded files to the Git:<br/>
   {{</p>
{
   avhAndrè van Hoorn-ThinkPad-RSS:0:~/git_work/kieker &lt;1533-gradle&gt;* $ git add gradlew gradlew.bat
   }
<p>}}</p>

<p>The script can now be used by calling <tt>./gradlew(.bat)</tt> and the usual Gradle options. On the first call of the script, the specified Gradle version is downloaded in installed (under *NIX into the <tt>/home/avh/.gradle/wrapper/dists/</tt> directory).</p>

<p>TODOs:<br/>
1. Decide on the required version &#45;-&#45; I've used the latest stable version, i.e., 2.2.1. However, maybe a major version number will do<br/>
2. Use <tt>gradlew</tt> script in CI server? (See excerpt from User Guide above, stating that the script is "the preferred way of starting a Gradle build")<br/>
3. Test on Windows (I don't see a problem here)<br/>
4. Add to examples accordingly.<br/>
5. Deploy with source archive</p>

**Comment by rju** [comment]
author André van Hoorn -- Mon, 5 Jan 2015 12:16:02 +0100
<p>Just recognized that the task automatically creates the <tt>gradlew(.bat)</tt> files also in the subdirectories &#45;-&#45; which makes perfect sense, of course. Hence, added these files in changeset:8da7b254e07825d8dcb01c671138626a8164b21c/kieker-git</p>

**Comment by rju** [comment]
author André van Hoorn -- Mon, 16 Feb 2015 16:55:56 +0100
<p>Seems like the <tt>gradle</tt> directories need to be added to VCS otherwise</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>avhAndrè van Hoorn-ThinkPad-RSS:0:~/git_work/kieker &lt;master&gt; $ ./gradlew 
Exception in thread "main" java.lang.NoClassDefFoundError: org/gradle/wrapper/GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: org.gradle.wrapper.GradleWrapperMain.  Program will exit.
</pre>
</div></div>
