### ISSUE TITLE
[KIEKER-1272] Null values should be handled by RBridgeControl

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2538]
JIRA Issue: [KIEKER-1272] Null values should be handled by RBridgeControl
Original Reporter: Teerat Pitakrat
 *** 
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>java.lang.NullPointerException
	at kieker.tools.util.RBridgeControl.eDblArr(RBridgeControl.java:163)
	at kieker.tools.tslib.forecast.AbstractRForecaster.forecast(AbstractRForecaster.java:159)
	at de.uni_stuttgart.rss.cpm.ArimaCPM.predictFailureProbability(ArimaCPM.java:159)
	at de.uni_stuttgart.rss.spm.ComponentPredictionModelFilter.inputMonitoringData(ComponentPredictionModelFilter.java:91)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at kieker.analysis.plugin.AbstractPlugin.deliver(AbstractPlugin.java:212)
	at kieker.tools.opad.filter.TimeSeriesPointAggregatorFilter.calculateAndDeliverAggregationValue(TimeSeriesPointAggregatorFilter.java:187)
	at kieker.tools.opad.filter.TimeSeriesPointAggregatorFilter.processInput(TimeSeriesPointAggregatorFilter.java:151)
	at kieker.tools.opad.filter.TimeSeriesPointAggregatorFilter.inputTSPoint(TimeSeriesPointAggregatorFilter.java:120)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at kieker.analysis.plugin.AbstractPlugin.deliver(AbstractPlugin.java:212)
	at de.uni_stuttgart.rss.spm.ComponentNameAndResponseTimeExtractor.inputOperationExecutionRecord(ComponentNameAndResponseTimeExtractor.java:89)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at kieker.analysis.plugin.AbstractPlugin.deliver(AbstractPlugin.java:212)
	at kieker.analysis.plugin.reader.filesystem.FSReader.read(FSReader.java:147)
	at kieker.analysis.AnalysisController$1.run(AnalysisController.java:486)
	at java.lang.Thread.run(Thread.java:745)
</pre>
</div></div>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>	public double[] eDblArr(final String input) {
		try {
			final REXPVector res = (REXPVector) this.evalWithR(input);
163			return res.asDoubles();
		} catch (final REXPMismatchException e) {
			return new double[0];
		}
	}
</pre>
</div></div>

<p><tt>res</tt> seems to be null.</p>

[KIEKER-1272]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author Thomas F. Düllmann -- Fri, 14 Nov 2014 01:29:09 +0100
<p>I added NullPointer handling from <tt>evalWithR(String)</tt> in changeset:3b1dc534e386599eb56068980fe68512903aca96/kieker-git in the branch <tt>KIEK-1258-opad-experiment</tt>: <a href="https://kieker-monitoring.atlassian.net/changeset/3b1dc534e386599eb56068980fe68512903aca96/kieker-git/src/tools/kieker/tools/util/RBridgeControl.java" class="external-link" rel="nofollow noreferrer">https://kieker-monitoring.atlassian.net/changeset/3b1dc534e386599eb56068980fe68512903aca96/kieker-git/src/tools/kieker/tools/util/RBridgeControl.java</a></p>

<p>Please check whether this solves the issue in your case.</p>

**Comment by rju** [comment]
author Thomas F. Düllmann -- Sat, 15 Nov 2014 13:31:40 +0100
<p>After the merge request has been processed, the fix will be in the master ( changeset:59af835b72cc11ae2a1fe1e340895e5a6bc104b0/kieker-git )</p>

<p><a href="https://build.se.informatik.uni-kiel.de/gitlab/kieker/kieker/merge_requests/17" class="external-link" rel="nofollow noreferrer">https://build.se.informatik.uni-kiel.de/gitlab/kieker/kieker/merge_requests/17</a></p>

**Comment by rju** [comment]
author nils-christian -- Thu, 20 Nov 2014 15:25:13 +0100
<p>Is this still topical? Fix has been merged as far as I know.</p>
