### ISSUE TITLE
[KIEKER-1177] chapter 5.1.1 AspectJ monitoring error: unable to add stackmap attributes. null

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2583]
JIRA Issue: [KIEKER-1177] chapter 5.1.1 AspectJ monitoring error: unable to add stackmap attributes. null
Original Reporter: Tobias Oestreicher
 *** 
<p>When following the coding instructions given in chapter 5.1.1, listing 5.4, an AspectJ error occurs as seen below. The meta-files of the example were testet unmodified and modified. Both ways did not lead to any non-faulty result. Using the compiled files of the development environment(Eclipse) the problem can be avoided, but compiling under Windows like discribed in the userguide causes an error.</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>D:\Repositories\kieker\examples\userguide\ch5--trace-monitoring-aspectj&gt;java -javaagent:lib\kieker-1.9_aspectj.jar -classpath build\ kieker.examples.userguide.ch5bookstore.BookstoreStarter
Sep 18, 2014 3:24:28 PM kieker.monitoring.probe.aspectj.AspectJLoader noConfigurationFileAvailable
INFORMATION: Using Kieker's AspectJLoader. This is not recommended for multi-classloader environments such as JavaEE and OSGI.
Sep 18, 2014 3:24:28 PM kieker.monitoring.probe.aspectj.AspectJLoader noConfigurationFileAvailable
INFORMATION: To disable Kieker's AspectJLoader use the additional VM parameter '-Dkieker.monitoring.skipDefaultAOPConfig
uration=true'.
AspectJ Internal Error: unable to add stackmap attributes. null
Exception in thread "main" java.lang.VerifyError: Expecting a stackmap frame at branch target 9
Exception Details:
Location:
kieker/examples/userguide/ch5bookstore/BookstoreStarter.extractNumRequestsFromArgs_aroundBody6([Ljava/lang/String;Lorg/aspectj/lang/JoinPoint;)I 1: ifnull
Reason:
Expected stackmap frame at this location.
Bytecode:
0000000: 2ac6 0008 2abe 9a00 0504 ac2a 0332 b800
0000010: 17ac 4db2 0007 bb00 0859 b700 0912 19b6
0000020: 000b 2a03 32b6 000b b600 0db6 000e b200
0000030: 0712 1ab6 000e 04ac
Exception Handler Table:
bci [11, 17] =&gt; handler: 18
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Unknown Source) 
at java.lang.Class.getMethod0(Unknown Source)
at java.lang.Class.getMethod(Unknown Source)
at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
</pre>
</div></div>

[KIEKER-1177]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author Jan Waller -- Fri, 19 Sep 2014 13:14:47 +0200
<p>Seems to be a problem with the used AspectJ version and Java 1.8. We currently investigate the issue.</p>

**Comment by rju** [comment]
author nils-christian -- Fri, 19 Sep 2014 13:40:33 +0200
<p>I can confirm that this issue occurs when using JDK 1.8 for compiling. With Kieker 1.10-SNAPSHOT (and therefore AspectJ 1.8) the issue does not occur.</p>

<p>Possible solutions:</p>
<ul>
	<li>Use JDK 1.7 for compilation</li>
	<li>Use Kieker 1.10 (release October 2014)</li>
	<li>Use a newer AspectJ version (1.8)</li>
</ul>


<p>Already fixed in current snapshot.</p>
