### ISSUE TITLE
[KIEKER-1183] Nullpointer exception when starting logging timestamp converter CLI tool

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2605]
JIRA Issue: [KIEKER-1183] Nullpointer exception when starting logging timestamp converter CLI tool
Original Reporter: Andre van Hoorn
 *** 
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>avhAndrè van Hoorn-ThinkPad-RSS:0:~/git_work/kieker &lt;master&gt; $ bin/convertLoggingTimestamp.sh
Exception in thread "main" java.lang.NullPointerException
        at kieker.tools.loggingTimestampConverter.LoggingTimestampConverterTool.readPropertiesFromCommandLine(LoggingTimestampConverterTool.java:63)
        at kieker.tools.AbstractCommandLineTool.start(AbstractCommandLineTool.java:58)
        at kieker.tools.loggingTimestampConverter.LoggingTimestampConverterTool.main(LoggingTimestampConverterTool.java:47)
</pre>
</div></div>

<p>Somehow related to CLI issue in 
    <span class="jira-issue-macro resolved" data-jira-key="KIEKER-1173" >
                <a href="https://kieker-monitoring.atlassian.net/browse/KIEKER-1173" class="jira-issue-macro-key issue-link"  title="Erroneous &quot;--&quot; instead of &quot;-&quot; for short parameters in usage output of CLI tools" >
            <img class="icon" src="https://kieker-monitoring.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />
            KIEKER-1173
        </a>
                                                    <span class="aui-lozenge aui-lozenge-subtle aui-lozenge-success jira-macro-single-issue-export-pdf">Done</span>
            </span>
?</p>

[KIEKER-1183]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author nils-christian -- Mon, 13 Oct 2014 10:58:32 +0200
<p>This is an issue again:</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>&gt;convertLoggingTimestamp.bat
Exception in thread "main" java.lang.NullPointerException
        at kieker.tools.loggingTimestampConverter.LoggingTimestampConverterTool.readPropertiesFromCommandLine(LoggingTimestampConverterTool.java:64)
        at kieker.tools.AbstractCommandLineTool.start(AbstractCommandLineTool.java:73)
        at kieker.tools.loggingTimestampConverter.LoggingTimestampConverterTool.main(LoggingTimestampConverterTool.java:47)
</pre>
</div></div>

<p>André: While fixing 
    <span class="jira-issue-macro resolved" data-jira-key="KIEKER-1168" >
                <a href="https://kieker-monitoring.atlassian.net/browse/KIEKER-1168" class="jira-issue-macro-key issue-link"  title="Issues in console output of TraceAnalysis tool" >
            <img class="icon" src="https://kieker-monitoring.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />
            KIEKER-1168
        </a>
                                                    <span class="aui-lozenge aui-lozenge-subtle aui-lozenge-success jira-macro-single-issue-export-pdf">Done</span>
            </span>
 you disabled the required-check in d6be606f01bff79fc2cc0aa1f1ce38bf747f31f6.</p>
