### ISSUE TITLE
[KIEKER-1219] Exception when using option 'maximal trace duration' in Trace Analysis GUI

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2620]
JIRA Issue: [KIEKER-1219] Exception when using option 'maximal trace duration' in Trace Analysis GUI
Original Reporter: Nils Christian Ehmke
 *** 
<p>Using the 'maximal trace duration' option in the GUI results usually in an exception:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at kieker.tools.traceAnalysis.gui.AdditionalOptionsStep.addSelectedTraceAnalysisParameters(AdditionalOptionsStep.java:192)
	at kieker.tools.traceAnalysis.TraceAnalysisGUI.startTraceAnalysis(TraceAnalysisGUI.java:227)
	...
</pre>
</div></div>

[KIEKER-1219]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author Imported User 11 -- Mon, 18 Aug 2014 20:57:45 +0200
<p>This Exception occurred because of the try to cast the maxTraceDurationInput (Integer) to Long. <br/>
The cast to a Long value is not necessary because the limit of a maxTraceDuration value as a Integer is sufficient. In the TraceAnalysisTool class it is generally used as a Integer. </p>

<p>In the TraceReconstructionFilter class though it is declared as long. </p>
