### ISSUE TITLE
[KIEKER-1115] Forward reference in kax files unsupported

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#2729]
JIRA Issue: [KIEKER-1115] Forward reference in kax files unsupported
Original Reporter: Oliver Kabierschke
 *** 
<p>If the pipes and filters structure contains a cycle, the WebGUI fails parsing the generated kax file.</p>

<p>The thrown error is:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>
kieker.webgui.common.exception.AnalysisInitializationException: An error occured while instantiating the analysis.
[...]
Caused by: net.vidageek.mirror.exception.ReflectionProviderException: Could not invoke method loadFromFile
	at net.vidageek.mirror.provider.java.PureJavaMethodReflectionProvider.invoke(PureJavaMethodReflectionProvider.java:45)
	at net.vidageek.mirror.invoke.MethodHandlerByMethod.withArgs(MethodHandlerByMethod.java:54)
	at net.vidageek.mirror.invoke.MethodHandlerByName.withArgs(MethodHandlerByName.java:46)
	at kieker.webgui.service.impl.utility.Analysis.&lt;init&gt;(Analysis.java:86)
	... 103 more
Caused by: java.io.IOException: The given file '...\kieker-webgui-1.8_binaries\bin\data\Forward-Reference-Bug\Forward-Reference-Bug.kax' is not a valid kax-configuration file.
	at kieker.analysis.AnalysisController.loadFromFile(AnalysisController.java:947)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.vidageek.mirror.provider.java.PureJavaMethodReflectionProvider.invoke(PureJavaMethodReflectionProvider.java:38)
	... 106 more
Caused by: org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: org.eclipse.emf.ecore.xmi.UnresolvedReferenceException: Unresolved reference '8'. (file:/.../kieker-webgui-1.8_binaries/bin/data/Forward-Reference-Bug/Forward-Reference-Bug.kax, 5, 56)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource(ResourceSetImpl.java:406)
	at kieker.analysis.AnalysisController.loadFromFile(AnalysisController.java:931)
	... 111 more
Caused by: org.eclipse.emf.ecore.xmi.UnresolvedReferenceException: Unresolved reference '8'. (file:/.../kieker-webgui-1.8_binaries/bin/data/Forward-Reference-Bug/Forward-Reference-Bug.kax, 5, 56)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.handleForwardReferences(XMLHandler.java:1149)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.endDocument(XMLHandler.java:1223)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:175)
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad(XMLResourceImpl.java:240)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1505)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1284)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	... 113 more
</pre>
</div></div>

<p>A example kax file, that produces this error, is attached.</p>

[KIEKER-1115]: https://kieker-monitoring.atlassian.net/browse/KIEKER-1115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rju** [comment]
author nils-christian -- Mon, 31 Mar 2014 18:32:48 +0200
<p>I cannot confirm this. Neither with 1.9-SNAPSHOT nor with 1.8. Please provide the detailed steps you perform to trigger this exception (import the file, e.g.).</p>

**Comment by rju** [comment]
author Oliver Kabierschke -- Mon, 31 Mar 2014 18:59:57 +0200
<p>To reproduce the exception I used the two Kieker filters <em>TeeFilter</em> and <em>CountingFilter</em>.<br/>
I connected the output port of the <em>TeeFilter</em> with the one of the <em>CountingFilter</em> and then the "relayedEvents" port of the <em>CountingFilter</em> with the input port of the <em>TeeFilter</em>. When I tried to start the analyse, the described exception was thrown.</p>

<p>I hope this helps.</p>

**Comment by rju** [comment]
author nils-christian -- Thu, 3 Apr 2014 13:16:54 +0200
<p>I still cannot confirm this <br class="atl-forced-newline" />- even with a freshly downloaded WebGUI. However, I did recognize another bug (
    <span class="jira-issue-macro resolved" data-jira-key="KIEKER-1043" >
                <a href="https://kieker-monitoring.atlassian.net/browse/KIEKER-1043" class="jira-issue-macro-key issue-link"  title="AnalysisControllerThread blocks with invalid configuration" >
            <img class="icon" src="https://kieker-monitoring.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />
            KIEKER-1043
        </a>
                                                    <span class="aui-lozenge aui-lozenge-subtle aui-lozenge-success jira-macro-single-issue-export-pdf">Done</span>
            </span>
). Does the exception occur when using a newly compiled version from the 1.9 branch? Can you reproduce this by using simply the <tt>AnalysisController.loadFromFile</tt> method instead of using the whole WebGUI?</p>

**Comment by rju** [comment]
author Jan Waller -- Tue, 8 Apr 2014 11:21:42 +0200
<p>So worksforme?</p>

**Comment by rju** [comment]
author André van Hoorn -- Tue, 8 Apr 2014 14:57:32 +0200
<ul>
	<li>Just tried to reproduce this (1.8 release) but did not "succeed".</li>
	<li>However, Oliver showed this to me and I've seen the error message on his machine ...</li>
</ul>

**Comment by rju** [comment]
author nils-christian -- Tue, 8 Apr 2014 16:45:41 +0200
<p>Some more details would be nice. Well, we already have the kax file in question. What about the machine? The OS? The used Kieker version? etc</p>

<p>At the moment this is indeed a worksforme.</p>

**Comment by rju** [comment]
author nils-christian -- Tue, 15 Apr 2014 13:35:24 +0200
<p>As suggested by Jan: Worksforme until proven otherwise.</p>
