### ISSUE TITLE
[KIEKER-954] Kieker data bridge script fails

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#896]
JIRA Issue: [KIEKER-954] Kieker data bridge script fails
Original Reporter: Reiner Jung
 *** 
<p>The Kieker Data Bridge script fails with a</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Predicate
	at kieker.tools.bridge.cli.CLIServerMain.main(CLIServerMain.java:187)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Predicate
	at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
	... 1 more
</pre>
</div></div>
<p>exception.</p>

## Checklist:

**Comment by rju** [comment]
author rju -- Fri, 22 Nov 2013 12:35:17 +0100
<p>Cause of this problem are missing jars. javasist.jar and guava-0.15.jar we should add them to the distribution.</p>

**Comment by rju** [comment]
author André van Hoorn -- Fri, 22 Nov 2013 13:08:34 +0100
<p>Is release 1.8 concerned? In this case, please change version number of this ticket. If the script is part of the release, it should be made part of the check script (I can take care of this if you provide an example call) and listed as to be tested during release creation (wiki:DevGuide#CreatingaRelease).</p>

**Comment by rju** [comment]
author rju -- Fri, 22 Nov 2013 13:14:47 +0100
<p>The script is part of the release. I'll add these two libraries to the Kieker lib repository including the LICENSE files.</p>

**Comment by rju** [comment]
author Jan Waller -- Mon, 25 Nov 2013 09:52:30 +0100
<p>Please change the name of the <tt>javasist.jar</tt> to <tt>javasist-VERSION.jar</tt> and adjust both <tt>.LICENSE</tt> files to our formating and to correct contents.</p>

**Comment by rju** [comment]
author Jan Waller -- Tue, 26 Nov 2013 13:36:33 +0100
<p>Replying to <span class="error">&#91;jwa|comment:4&#93;</span>:<br/>
&gt; Please change the name of the <tt>javasist.jar</tt> to <tt>javasist-VERSION.jar</tt> and adjust both <tt>.LICENSE</tt> files to our formating and to correct contents.</p>

<p>There are also other libraries from the KiekerBridge project without correct LICENSE files.</p>

**Comment by rju** [comment]
author rju -- Tue, 26 Nov 2013 13:41:27 +0100
<p>Version for javassist is added. Which other libraries do not match the naming scheme?<br/>
guava-0.15.jar<br/>
reflections-0.9.9-RC1.jar </p>

**Comment by rju** [comment]
author Jan Waller -- Tue, 26 Nov 2013 13:58:22 +0100
<p>Their .LICENSE files miss their header (lib name, homepage, ...)</p>
